---
title: The Best Pecorino Romano Cheese
---

The Best Pecorino Romano Cheese
Is Pecorino Romano from Italy worth seeking out, or can domestic options do the job?

Lisa McManus
By Lisa McManus ･ Published Mar. 1, 2018. Appears in Cook's Country TV Season 15: Seafood Two Ways
Save

Top Picks


See Everything We Tested
Sign up for the Well-Equipped Cook newsletter
Shop smarter with our ATK Reviews team's expert guides and recommendations.

Enter Your Email
Sign Me Up
By providing your email above, you agree to our Terms of Service and Privacy Policy.

What You Need to Know
Pecorino Romano is like the seasoned character actor who improves dozens of movies but never quite gets recognition. It’s one of the oldest cheeses in the world, named for its origins in ancient Rome, and its firm, slightly oily, crystalline texture and salty, funky flavor deserve fresh consideration out of the shadow of its more famous cousin, Parmigiano‑Reggiano. In the test kitchen, we use it in a number of salads, vegetable dishes, soups, and frittatas, not to mention classic Italian pasta dishes such as cacio e pepe, pasta all'amatriciana, and lasagna, where its rich, complex flavor is a quiet powerhouse.

But does it matter which cheese you bring home? We chose seven nationally available versions. In supermarkets, you’ll find cheese labeled Pecorino Romano and Romano sold side by side, so we included both. In blind tastings, we asked panels to evaluate the cheeses both plain and cooked in our recipe for Spaghetti with Pecorino and Black Pepper (Cacio e Pepe). To help us understand our preferences, we sent samples to an independent laboratory to measure their pH and compared the nutrition content provided on product labels.

Tasters evaluate samples of Romano and Pecorino Romano during a blind taste test.
Tasters evaluate samples of Romano and Pecorino Romano during a blind taste test.
Pecorino Romano versus Romano: What’s the Difference?

With Denominazione di Origine Protetta (DOP) status in the European Union, the cheese called Pecorino Romano can be made only in Lazio (the province that includes Rome), in Grosseto in Tuscany, and on the island of Sardinia, where most of it is produced today. It’s made with sheep’s milk (pecora means “sheep” in Italian) from local flocks that is heated and curdled with rennet from local lambs. Then the cheese is pressed, rubbed repeatedly with salt, stamped with identifying marks, and aged, all according to the standards of a consortium that oversees its production. This results in a unique cheese that is important in central and southern Italian and Italian American cooking. As early as 1911, Italian immigrants were ordering it shipped to America. Today, Italy produces 25,000 tons of the cheese per year; 60 percent of that is exported, and the top buyer is the United States. Perhaps surprisingly, Pecorino Romano accounts for a third of all Italian cheese exported to America. American cheesemakers, however, lacking access to sheep’s milk on an industrial scale, make Romano cheese with cow’s milk.

tester grating a block of cheese and small cups of pasta and cheese ready for the tasting
The simple dish cacio e pepe relies heavily on the flavor of Pecorino cheese, so it was the perfect recipe in which to compare the various cheeses in a cooked application.
In both blind tastings, plain and in pasta, our tasters preferred imported Pecorino Romanos over domestic Romanos. While we didn’t dislike the domestic cheeses, our consensus was that they were simply not the same: milder, softer, less aromatic, and more like Swiss cheese than sharper, funkier, more crumbly, crystalline Pecorino Romano. Soft texture and mild flavor were understandable, since cheese becomes firmer and its flavor more complex the longer it is aged; our domestic Romanos were aged for as little as five months, compared with more than eight months for the imports. And the two lowest-ranked domestic cheeses had the lowest pH in the lineup, which indicates younger cheese; this higher acidity can lead to a slightly sour flavor and a pebbly texture that our tasters noticed when we sampled the cheeses plain. The imports contained more sodium, providing a deeply savory taste—and our winner had the most sodium of all. (It’s meant to be salty: Italian cooks often reduce salt in dishes where Pecorino Romano is prominent.) Finally, the basic flavor profiles of the domestic and imported cheeses didn’t match up.

Cow’s-Milk versus Sheep’s-Milk Cheese
Simply put, cow’s milk and sheep’s milk make different cheeses. Sheep’s milk has many short-chain and medium-chain fatty acids, while cow’s milk contains long-chain fatty acids, so they break down into different aroma compounds, explained Sarah Hoffmann, founder of Green Dirt Farm in Weston, Missouri, which produces small-batch sheep’s-milk cheeses. Certain fatty acids that create the gamy, funky taste of goat cheese appear in very small concentrations in sheep’s milk, too, but they’re absent from cow’s milk, she said.

Diagram showing the texture difference between romano and pecorino romano cheese
Domestic cheeses labeled “Romano” are an entirely different breed of cheese than the Italian imports bearing the name “Pecorino Romano.”
Domestic Romano cheesemakers try to re-create some of the pungency of Pecorino Romano by adding lipase to the cow’s milk, explained Dean Sommer, senior food technologist for the Center for Dairy Research at the University of Wisconsin–Madison. This enzyme digests and breaks down dairy fat into fatty acids and glycerol, and in the process, it lends flavor and aroma to the cheese. In Sommer’s opinion, while this does create “strong” flavors, it doesn’t quite succeed in making cow’s-milk Romano taste like Pecorino Romano. Instead, he said, the result is “very similar to aged provolone cheese.” Anna Thomas Bates, co-owner of sheep’s-milk cheese producer Landmark Creamery in Albany, Wisconsin, agreed: “You just can’t duplicate the chemical makeup of sheep’s milk.”

Why Sheep?
Much of the rocky, arid terrain around the Mediterranean is not ideal for cattle. Smaller herd animals such as sheep and goats are better adapted for navigating and foraging for the sparse vegetation, so sheep’s- and goat’s-milk cheeses are the natural product in these regions. Some of the more famous sheep’s-milk cheeses include feta and halloumi from Greece, Manchego and Idiazabal from Spain, and Roquefort from France. In Italy, every sheep’s-milk cheese is called “Pecorino,” since the word pecora simply means “sheep.” Its second name—such as Romano or Toscano—designates its particular origin and/or style.

In the United States, we lack this tradition of sheep’s-milk cheese, said Hoffman. “From the 1600s in America, cheese was a commodity, made to be shipped to the Caribbean in trade for rum,” she said. “If you’re coming at it from the standpoint of trying to make money, you’re going to go for the animal that will produce the most milk, and that’s the cow. Sheep are very low-volume milk producers relative to other animals. You get one-quarter of what a goat produces and one-tenth of what a cow produces.


Sheep’s milk is renowned for its excellent composition for cheese making, with nearly twice the protein, fat, calcium, and solids of cow’s milk and an ability to develop complex, rich, fruity, toasted-nut, caramel, toffee, and even browned butter–like flavors as the cheese ages. So why don’t domestic cheese manufacturers make an effort to produce more sheep’s milk and age it more to make firmer, more flavorful Romano?

There are a few reasons. First, a sheep produces about one-tenth the volume of milk that a cow does, Hoffmann explained, so it’s much more expensive. Basic “commodity” cow’s milk costs about $0.15 per pound in the United States, while organic, grass-fed versions sell for $0.35 per pound, said Bates. Compare that with sheep’s milk, at $0.80 to $1.20 per pound, respectively. Second, American sheep breeds produce even less milk than those in Europe. (Federal bans on importing higher-yield breeds were lifted in 2017, so this is beginning to change.) Third, “aging is an expensive undertaking for producers, as it ties up inventory for long stretches of time—often months or years,” said Nora Weiser, executive director of the American Cheese Society (ACS). “So while I feel we’ll see more sheep’s-milk cheeses from smaller and specialty producers, it may not be something that big U.S. companies gravitate toward.” Still, sheep’s-milk cheeses are trending: More American consumers are seeking them out, and more domestic artisan cheesemakers are making them, Weiser said, noting that an ACS study showed a 40-percent increase in domestic sheep’s-milk cheese production between 2010 and 2016. ACS added a sheep’s-milk cheese category to its competition in 2017 for the first time, reflecting the growing number of entrants.

What's That Black Stuff on the Rind?

The black substance on the rinds of some Pecorino Romano cheeses is a food-safe paint that is sprayed on. You should scrape it off before grating or using the rind as flavoring, to avoid getting the black color in your dishes. If you do eat some, it won’t hurt you, and it’s flavorless, said Michele Buster, vice president and founder of New York–based Forever Cheese, importer of black-rinded Fulvi Pecorino Romano. While we’re all for tradition, we’re grateful that some things have changed with the times: Buster said the color is a modern take on the ancient practice of protectively coating the rind with mud.

As for our lineup, we recommend all of the imported Italian Pecorino Romano cheeses, but our top choice was the “pungent, salty, and sharp” Boar’s Head Pecorino Romano, which is widely available and moderately priced. (Note: This cheese is made in Italy following DOP guidelines, but because the wheels are cut and repackaged in the United States, the wedges are considered non-DOP, a Boar’s Head spokesperson confirmed.) In a pinch, a domestic Romano will do, but if you are like our tasters, you may regret not having the extra richness and complexity that Pecorino Romano brings to the table.

chart comparing pecorino romano to parmigiano-reggiano cheese
How We Tested
Winning Traits

04:35
America's Test Kitchen
Pecorino Romano
Watch Now
Everything We Tested
Expand All
Recommended

Winner
Boar's Head Pecorino Romano
“Delicious! Rich, complex, deeply savory, with a long finish” and a “crystalline” crunch, this imported sheep's-milk Pecorino Romano sold under the Boar's Head banner was “dense, nicely dry, salty in a fruity, fatty kind of way” and was our tasters' overall favorite. It also had by far the highest sodium level in our lineup, adding to its savory appeal. In pasta, it was “smooth,” “pungent, salty, and sharp,” with “the perfect taste and creamy texture I've been looking for! Silky, tangy, cheesy, creamy, assertive.”


Locatelli Pecorino Romano
“Full-flavored, complex, crystalline, crumbly, pungent, salty; just right,” this imported sheep's-milk Pecorino Romano had a “lovely sheepy, briny flavor” that was “Robust! Salty! Addictive!” and “deeply savory, almost meaty, with a fatty richness” and a “slightly crumbly texture.” Tasters found it “funky, but in a good way.” In spaghetti, it was “silky,” “velvety,” “creamy and buttery” —the “strong, lovely cheese flavor makes this dish sing.”


Best Buy
Pecorino Romano by Zerto
With “lots of crystals,” this “salty, rich, funky” cheese was “almost crunchy” and “pleasingly pungent” when nibbled plain, coming across as “creamy and milky and salty without being overbearing.” Its “coarse texture” was described as “perfect for grating.” “It's like the other great Pecorinos but a touch more subdued instead of knock-you-out salty/funky.” In spaghetti, the cheese's flavor was “a little mild” compared with those of other samples, but it helped achieve a “good balance of salt and cheese and pepper, all working in harmony.”


Genuine Fulvi Pecorino Romano
With “a little kick!” and “some funk on the finish,” this imported Pecorino Romano won fans. “Oh, this is just lovely,” wrote one taster. “Firm and crumbly yet also creamy. It's grassy and fruity, with sweet winey notes and some crystalline crunch.” On spaghetti, the fruity notes came through in a “velvety,” “nutty” sauce.

Recommended with reservations

Sartori Cheese Romano
With “pleasant,” “mild,” “sweet,” “nutty” flavor, this domestic cow's-milk Romano was “very soft” and “not as pungent as it should be,” “very buttery and Parmesan-like,” like “unhole-y Swiss.” “This isn't a bad cheese,” wrote a taster. “It's mild, creamy, and toothsome, with good milkiness.” But others noted that it “could stand to be saltier.” In pasta, it had “nice saucy-ness” and was “smooth, creamy,” making for “kid-friendly noodles, for sure,” but was “really overwhelmed by the pepper.”


Stella Romano Cheese
This cheese was a bit too “mild overall,” reminiscent of “gouda,” “Gruyère,” or “cheddar.” It was “buttery, creamy, but missing the funk and crumbliness” tasters sought. “I miss the salty bite!” wrote one. “Lacks the intensity I expect, but I don't dislike the sweet, nutty, caramel-y flavor.” A few complained about the texture, noting that it “breaks into pellets.” In pasta, it was “perfectly creamy” and “light,” but its flavor was “muted.”


Bel Gioioso Romano
“Mildly salty,” “fruity,” “soft and slightly creamy,” with a “pebbly” texture when broken and a slightly “sour” flavor with “some tanginess to the finish,” this domestic cow's-milk Romano “eats like cheddar,” “provolone,” or “Swiss cheese.” “This is missing that gritty saltiness I crave,” one taster noted. Others summed it up: “Inoffensive but not beguiling.” In spaghetti, it had “no bite or much saltiness” and “could be more flavorful.”

*All products reviewed by America’s Test Kitchen are independently chosen, researched, and reviewed by our editors. We buy products for testing at retail locations and do not accept unsolicited samples for testing. We list suggested sources for recommended products as a convenience to our readers but do not endorse specific retailers. When you choose to purchase our editorial recommendations from the links we provide, we may earn an affiliate commission. Prices are subject to change.

Reviews You Can Trust
The mission of America’s Test Kitchen Reviews is to find the best equipment and ingredients for the home cook through rigorous, hands-on testing. Have a question or suggestion? Send us an email at atkreviews@americastestkitchen.com. We appreciate your feedback!

The Expert
Author: Lisa McManus
by
Lisa McManus
Executive Editor, ATK Reviews

Lisa McManus is an executive editor for ATK Reviews, cohost of Gear Heads on YouTube, host of Cook's Illustrated's Equipment Review videos, and a cast member—the gadget expert—on TV's America's Test Kitchen. A passionate home cook, sometime waitress, and longtime journalist, she graduated from Columbia University's Graduate School of Journalism and worked at magazines and newspapers in New York and California before returning like a homing pigeon to New England. In 2006 she got her dream job at ATK reviewing kitchen equipment and ingredients and has been pretty thrilled about it ever since. Her favorite thing is to go somewhere new and find something good to eat.