---
title: Treatise on the Emendation of the Intellect
author: Baruch Spinoza
---


## Treatise on the Emendation of the Intellect

### EDITORIAL PREFACE

THE _Treatise on the Emendation of the Intellect_ (TdIE), a short, difficult,
but fascinating discourse on method, was first published in Spinoza’s _Opera
posthuma_ in 1677. But as the editors of that collection tell us in their
preface, both its style and its content show it to be one of Spinoza’s
earliest works. If the reference in Letter 6 to a “whole short work”
(_integrum opusculum_) is indeed to this treatise, as scholars have generally
assumed,[1](part0013.html#ch1fn1) then a draft of it must have existed at
least by early in 1662, and quite likely Spinoza wrote it before
that.[2](part0013.html#ch1fn2)

Various forward references in Spinoza’s notes to this treatise indicate that
at some stage of his work on it Spinoza conceived it as introductory to
another work, to be called (perhaps) _Philosophy_ , a work which would have
discussed in a systematic way topics in philosophical theology (II/29, n. z),
philosophy of mind (II/15, n. o), epistemology (II/14, nn. k and l), ethics
(II/6, n. a; II/7, n. b; II/8, n. c), and perhaps much else (cf. II/9, n. d).
Some of the references suggest a work more like the _Short Treatise_ than the
_Ethics_ ,[3](part0013.html#ch1fn3) and Gebhardt argued that the “short work”
referred to in Letter 6 was a two-part work, with the TdIE as a methodological
prolegomenon to the more systematic KV. According to Gebhardt (I/407), the
Latin original of the KV was already in existence when Spinoza began writing
the TdIE around the time of Letter 6. But if what I have suggested above is
correct (see n. 2), then Gebhardt must be wrong at least about the date of
composition of the TdIE. Mignini would argue that Gebhardt is wrong also in
thinking that the TdIE was an integral part of the short work Spinoza refers
to in Letter 6. Emphasizing the incompleteness of our text of the TdIE, he
contends that it could not have been correctly described in Letter 6 as
_having been composed_ and that it is earlier than the KV, not merely in date
of composition, but also in the stage of the development of Spinoza’s thought
that it represents.[4](part0013.html#ch1fn4) If Mignini’s arguments for the
priority of the TdIE are not conclusive, he has, I think, at least established
that there is no reason to regard the KV as the earlier
work.[5](part0013.html#ch1fn5) So at this stage the position would seem to be
that, if the TdIE is not in fact earlier that the KV, it was probably written
at about the same time as the KV and as an introduction to it.

In its importance for the study of the development of Spinoza’s thought, the
_Treatise on the Intellect_ invites comparison with Descartes’ _Regulae_. Both
are early, unfinished works that show the direction of their author’s thought
at a formative stage, that indicate the problems concerning him and the
solutions he was inclined toward. Both discuss certain important themes more
fully than does any work their author later published. But both works also
need to be read with the consciousness that the lines of thought presented in
them may not have proved ultimately to be satisfactory to the author.

For example, some have argued that in this treatise Spinoza has not fully
emancipated himself from Descartes on the distinction between will and
intellect,[6](part0013.html#ch1fn6) and it seems clear that he does tend to
confuse mind and intellect.[7](part0013.html#ch1fn7) I would argue that the
discussion of the four kinds of knowledge is not clearly thought
out.[8](part0013.html#ch1fn8) And Joachim has suggested that the whole work
may have been intended only to present a popular, imprecise exposition of
Spinoza’s thought on these topics.[9](part0013.html#ch1fn9)

The most important question, perhaps, is whether the whole concept of method,
as Spinoza here presents it, is not incoherent, and so doomed to
failure.[10](part0013.html#ch1fn10) On the one hand, the truth is supposed to
require no sign, and having a true idea is supposed to be sufficient to remove
doubt (§ 36); on the other, the method is supposed, among other things, to
teach us what a true idea is, and how to distinguish it from other perceptions
(§ 37).

But whatever reservations we may have about the doctrine of this work, it is
clear that _in the main_ it continued to satisfy Spinoza for some years. A
letter to Bouwmeester in 1666 (Letter 37) repeats some of the _Treatise’s_
main themes—that the intellect, unlike the body, is not subject to chance,
external causes, but has the power of forming clear and distinct ideas; that
it is necessary above all to distinguish between the intellect and the
imagination (this being identified with distinguishing between true ideas and
all the rest, the false, fictitious and doubtful). And an interchange with
Tschirnhaus in 1675 (Letters 59 and 60) indicates that Spinoza had
communicated something similar to him informally, and had given Tschirnhaus
some reason to expect that before long he would publish his treatise on
method.

Naturally, then, there have been a variety of suggestions as to why the
_Treatise_ never was published in Spinoza’s lifetime. The editors of the
_Opera posthuma_ remark that the importance of the topic, the deep
contemplations and extensive knowledge it required, made Spinoza’s progress
with it very slow. Appuhn suggests that Spinoza broke off the composition
because he could not see any satisfactory solution to the problems raised at
the end (§§ 102-103, 106-110), and that he did not return to finish it because
he came to think it more important to concentrate on his other works on moral
and political philosophy (the _Ethics_ , the _Theological-Political Treatise_
, and the _Political Treatise_). Koyré, on the other hand, tends to emphasize
the difficulty raised in § 46 (see the note to II/18/1-2). Ironically,
Joachim’s excellent commentary on this work itself remained unfinished at his
death because he was unable to resolve to his satisfaction the problem of how
Spinoza meant to conclude the _Treatise_.

If the character of this work as unfinished, highly problematic, and only
posthumously published invites comparison with Descartes’ _Regulae_ , the
apparently autobiographical character of the opening sections equally invites
comparison with the _Discourse on Method_. The tone of the two works is quite
different, of course. The dissatisfaction Descartes presents as leading him to
philosophy is with the uncertainty of the learning that had been imparted to
him as a student. Spinoza’s dissatisfaction is with the insufficiency of the
ends men commonly pursue.

Of course scholars have doubted whether these opening passages should be taken
as strictly autobiographical (just as they have doubted the accuracy of
Descartes’ account of his life in the _Discourse_). As Koyré remarks (Koyré 2,
xix), the theme _de vero bono et de contemptu mundi_ is as old as the world
itself. Various Stoic authors (e.g., Marcus Aurelius and Seneca) have been
cited. And Elbogen calls attention to the work of a medieval Jewish author,
Shem Tov Falaquera, whose _Ha-Mevak-kesh_ similarly offers knowledge as the
path to salvation. However that may be, it remains, as Koyré also remarks,
highly significant that Spinoza should begin a treatise on method by
reflecting on the true good.

The paragraph numbers in brackets are those introduced by Bruder and are
included for ease in making and following references. Lettered footnotes are
Spinoza’s, numbered footnotes are mine. I have adopted the lettering of
Gebhardt’s edition, though (even allowing for differences in the Latin
alphabet) it is not entirely consecutive.

### [II/4] NOTICE TO THE READER1

THIS _Treatise on the Emendation of the Intellect_ etc., which we give you
here, kind reader, in its unfinished [NS: and defective] state, was written by
the author many years ago now. He always intended to finish it. But hindered
by other occupations, and finally snatched away by death, he was unable to
bring it to the desired conclusion. But since it contains many excellent and
useful things, which—we have no doubt—will be of great benefit to anyone
sincerely seeking the truth, we did not wish to deprive you of them. And so
that you would be aware of, and find less difficult to excuse, the many things
that are still obscure, rough, and unpolished, we wished to warn you of them.
Farewell.

### [II/5] Treatise on the Emendation of the Intellect [5] and on the way by which it is best directed toward the true knowledge of things2

[1] AFTER experience had taught me that all the things which regularly occur
in ordinary life are empty and futile, and I saw that all the [10] things
which were the cause or object of my fear had nothing of good or bad in
themselves, except insofar as [my] mind was moved by them, I resolved at last
to try to find out whether there was anything which would be the true good,
capable of communicating itself, and which alone would affect the mind, all
others being rejected—whether there [15] was something which, once found and
acquired, would continuously give me the greatest joy, to eternity.

[2] I say that _I resolved at last_ —for at first glance it seemed ill-advised
to be willing to lose something certain for something then uncertain. I saw,
of course, the advantages that honor and wealth bring, and that I would be
forced to abstain from seeking them, if I wished to devote [20] myself
seriously to something new and different; and if by chance the greatest
happiness lay in them, I saw that I should have to do without it. But if it
did not lie in them, and I devoted my energies only to acquiring them, then I
would equally go without it.

[3] So I wondered whether perhaps it would be possible to reach my new goal—or
at least the certainty of attaining it—without changing [25] the conduct and
plan of life which I shared with other men. Often I tried this, but in vain.
For most things which present themselves in life, and which, to judge from
their actions, men think to be the highest [II/6] good, may be reduced to
these three: wealth, honor, and sensual pleasure.[3](part0013.html#ch1fn13)
The mind is so distracted by these three that it cannot give the slightest
thought to any other good.

[4] For as far as sensual pleasure is concerned, the mind is so caught up in
it, as if at peace in a [true] good, that it is quite prevented from thinking
of anything else. But after the enjoyment of sensual pleasure [5] is past, the
greatest sadness follows. If this does not completely engross, still it
thoroughly confuses and dulls the mind.

The mind is also distracted not a little by the pursuit of honors and wealth,
particularly when the latter[a](part0013.html#ch1fn14) is sought only for its
own sake, because it is assumed to be the highest good. [5] But the mind is
far [10] more distracted by honor. For this is always assumed to be good
through itself and the ultimate end toward which everything is directed.

Nor do honor and wealth have, as sensual pleasure does, repentance as a
natural consequence. The more each of these is possessed, the more joy is
increased, and hence the more we are spurred on to increase [15] them. But if
our hopes should chance to be frustrated, we experience the greatest sadness.
And finally, honor has this great disadvantage: to pursue it, we must direct
our lives according to other men’s powers of understanding—fleeing what they
commonly flee and [20] seeking what they commonly seek.

[6] Since I saw that all of these things stood in the way of my working toward
this new goal, indeed were so opposed to it that one or the other must be
given up, I was forced to ask what would be more useful to me. For as I say, I
seemed to be willing to lose the [25] certain good for the uncertain one. But
after I had considered the matter a little, I first found that, if I devoted
myself to this new plan of life, and gave up the old, I would be giving up a
good by its nature uncertain (as we can clearly infer from what has been said)
for one uncertain not by its nature (for I was seeking a permanent good) but
only in respect to its attainment.

[30] [7] By persistent meditation, however, I came to the conclusion that, if
only I could resolve, wholeheartedly,[4](part0013.html#ch1fn15) [to change my
plan of life], I would be giving up certain evils for a certain good. For I
saw that I [II/7] was in the greatest danger, and that I was forced to seek a
remedy with all my strength, however uncertain it might be—like a man
suffering from a fatal illness, who, foreseeing certain death unless he
employs a remedy, is forced to seek it, however uncertain, with all [5] his
strength. For all his hope lies there. But all those things men ordinarily
strive for, not only provide no remedy to preserve our being, but in fact
hinder that preservation, often cause the destruction of those who possess
them,[b](part0013.html#ch1fn16) and always cause the destruction of those who
are possessed by them.[5](part0013.html#ch1fn17)

[10] [8] There are a great many examples of people who have suffered
persecution to the death on account of their wealth, or have exposed
themselves to so many dangers to acquire wealth that they have at last paid
the penalty for their folly with their life. Nor are there fewer examples of
people who, to attain or defend honor, have suffered most [15] miserably. And
there are innumerable examples of people who have hastened their death through
too much sensual pleasure.

[9] Furthermore, these evils seemed to have arisen from the fact that all
happiness or unhappiness was placed in the quality of the object to which we
cling with love. For strife will never arise on account of [20] what is not
loved, nor will there be sadness if it perishes, nor envy if it is possessed
by another, nor fear, nor hatred—in a word, no disturbances of the mind.
Indeed, all these happen only in the love of those things that can perish, as
all the things we have just spoken of can do.

[10] But love toward the eternal and infinite thing feeds the mind [25] with a
joy entirely exempt from sadness.[6](part0013.html#ch1fn18) This is greatly to
be desired, and to be sought with all our strength.

But not without reason did I use these words _if only I could resolve in
earnest_.[7](part0013.html#ch1fn19) For though I perceived these things [NS:
this evil] so clearly in my mind, I still could not, on that account, put
aside all greed, [30] desire for sensual pleasure and love of esteem.

[11] I saw this, however: that so long as the mind was turned toward these
thoughts, it was turned away from those things, and was thinking seriously
about the new goal. That was a great comfort to me. For I saw that those evils
would not refuse to yield to remedies. And [II/8] although in the beginning
these intervals were rare, and lasted a very short time, nevertheless, after
the true good became more and more known to me, the intervals became more
frequent and longer—especially after I saw that the acquisition of money,
sensual pleasure, and [5] esteem are only obstacles so long as they are sought
for their own sakes, and not as means to other things. But if they are sought
as means, then they will have a limit, and will not be obstacles at all. On
the contrary, they will be of great use in attaining the end on account of
which they are sought, as we shall show in its place.

[10] [12] Here I shall only say briefly what I understand by the true good,
and at the same time, what the highest good is. To understand this properly,
it must be noted that good and bad are said of things only in a certain
respect, so that one and the same thing can be called both good and bad
according to different respects. The same applies [15] to perfect and
imperfect. For nothing, considered in its own nature, will be called perfect
or imperfect, especially after we have recognized that everything that happens
happens according to the eternal order, and according to certain laws of
Nature.

[13] But since human weakness does not grasp that order by its own thought,
and meanwhile man conceives a human nature much stronger [20] and more
enduring[8](part0013.html#ch1fn20) than his own, and at the same time sees
that nothing prevents his acquiring such a nature, he is spurred to seek means
that will lead him to such a perfection. Whatever can be a means to his
attaining it is called a true good; but the highest good is to arrive—together
with other individuals if possible—at the enjoyment [25] of such a nature.
What that nature is we shall show in its proper place: that it is the
knowledge[c](part0013.html#ch1fn21) of the union that the mind has with the
whole of Nature.[9](part0013.html#ch1fn22)

[14] This, then, is the end I aim at: to acquire such a nature, and to strive
that many acquire it with me. That is, it is part of my happiness [30] to take
pains that many others may understand as I understand, so that their intellect
and desire agree entirely with my intellect and desire. To do this it is
necessary,[d](part0013.html#ch1fn23) _first_ to understand as much of Nature
[II/9] as suffices for acquiring such a nature; _next_ , to form a society of
the kind that is desirable, so that as many as possible may attain it as
easily and surely as possible.

[15] _Third_ , attention must be paid to Moral Philosophy and to Instruction
[5] concerning the Education of children. Because Health is no small means to
achieving this end, _fourthly_ , the whole of Medicine must be worked out. And
because many difficult things are rendered easy by ingenuity, and we can gain
much time and convenience in this life, _fifthly_ , Mechanics is in no way to
be despised.

[10] [16] But before anything else we must devise a way of healing the
intellect, and purifying it, as much as we can in the beginning, so that it
understands things successfully, without error and as well as
possible.[10](part0013.html#ch1fn24) Everyone will now be able to see that I
wish to direct all the sciences toward one end[e](part0013.html#ch1fn25) and
goal, viz. that we should achieve, as we [15] have said, the highest human
perfection. So anything in the sciences which does nothing to advance us
toward our goal must be rejected as useless—in a word, all our activities and
thoughts are to be directed to this end.

[17] But while we pursue this end, and devote ourselves to bringing [20] the
intellect back[11](part0013.html#ch1fn26) to the right path, it is necessary
to live. So we are forced, before we do anything else, to assume certain rules
of living as good:

1\. To speak according to the power of understanding of ordinary people, and
do whatever does not interfere with our attaining our [25] purpose. For we can
gain a considerable advantage, if we yield as much to their understanding as
we can. In this way, they will give a favorable hearing to the truth.

2\. To enjoy pleasures just so far as suffices for safeguarding our health.

[30] 3\. Finally, to seek money, or anything else, just so far as suffices for
sustaining life and health, and conforming to those customs of the community
that do not conflict with our aim.

[18] Having laid down these rules, I come now to what must be [35] done first,
before all else: emending[12](part0013.html#ch1fn27) the intellect and
rendering it [II/10] capable of understanding things in the way the attainment
of our end requires. To do this, the order we naturally have requires me to
survey here all the modes of perceiving which I have had up to now for
affirming or denying something without doubt, so that I may choose [5] the
best of all, and at the same time begin to know my powers and the nature that
I desire to perfect.

[19] If I consider them accurately, I can reduce them all to
four[13](part0013.html#ch1fn28) main kinds:

1\. There is the Perception we have from report or from some [10] conventional
sign.[14](part0013.html#ch1fn29)

2\. There is the Perception we have from random
experience,[15](part0013.html#ch1fn30) that is, from experience that is not
determined by the intellect. But it has this name only because it comes to us
by chance, and we have no other experiment that opposes it. So it remains with
[15] us unshaken.

3\. There is the Perception that we have when the essence of a thing is
inferred from another thing, but not adequately. This happens, either
[f](part0013.html#ch1fn31)when we infer the cause from some effect, or when
something is inferred from some universal, which some property always
accompanies.[17](part0013.html#ch1fn33)

[20] 4\. Finally, there is the Perception we have when a thing is perceived
through its essence alone, or through knowledge of its proximate cause.

[20] I shall illustrate all of these with examples. I know only from report my
date of birth, and who my parents were, and similar things, which I have never
doubted. By random experience I know that I [25] shall die, for I affirm this
because I have seen others like me die, even though they had not all lived the
same length of time and did not all die of the same illness. Again, I also
know by random experience that [II/11] oil is capable of feeding fire, and
that water is capable of putting it out. I know also that the dog is a barking
animal, and man a rational one. And in this way I know almost all the things
that are useful in life.

[21] But we infer [one thing][18](part0013.html#ch1fn36) from another in this
way: after we [5] clearly perceive that we feel such a body, and no other,
then, I say, we infer clearly that the soul is
united[g](part0013.html#ch1fn37) to the body, which union is the cause of such
a sensation; but we cannot understand absolutely from this
what[h](part0013.html#ch1fn38) that sensation and union are. Or after we have
come to know the nature of vision, and that it has the property that we see
[10] one and the same thing as smaller when we look at it from a great
distance than when we look at it from close up, we infer that the sun is
larger than it appears to be, and other things of the same
kind.[20](part0013.html#ch1fn39)

[22] Finally, a thing is perceived through its essence alone when, from the
fact that I know something, I know what it is to know something, [15] or from
the fact that I know the essence of the soul, I know that it is united to the
body. By the same kind of knowledge, we know that two and three are five, and
that if two lines are parallel to a third line, they are also parallel to each
other, etc. But the things I have so far been able to know by this kind of
knowledge have been very few.

[20] [23] That you may understand all these things better, I shall use only
one example. Suppose there are three numbers. Someone is seeking a fourth,
which is to the third as the second is to the first. Here merchants will
usually say that they know what to do to find the fourth number, because they
have not yet forgotten that procedure [25] which they simply heard from their
teachers, without any demonstration.

[II/12] Others will construct a universal axiom from an experience with simple
numbers, where the fourth number is evident through itself—as in the numbers
2, 4, 3, and 6. Here they find by trial that if the second is multiplied by
the third, and the product then divided by the first, the result is 6. Since
they see that this produces the same number [5] which they knew to be the
proportional number without this procedure, they infer that the procedure is
always a good way to find the fourth number in the proportion.

[24] But Mathematicians know, by the force of the demonstration of Proposition
19 in Book VII of Euclid, which [21](part0013.html#ch1fn40) numbers are
proportional to one another, from the nature of proportion, and its property,
[10] viz. that the product of the first and fourth numbers is equal to the
product of the second and third. Nevertheless, they do not see the adequate
proportionality of the given numbers. And if they do, they see it not by the
force of that Proposition, but intuitively, [NS: or] without going through any
procedure.

[25] To choose the best mode of perceiving from these, we are required [15] to
enumerate briefly the means necessary to attain our end:

1.[22](part0013.html#ch1fn41) To know exactly our nature, which we desire to
perfect, and at the same time,

2\. [To know] as much of the nature of things as is necessary,

(a) to infer rightly from it the differences, agreements and [20] oppositions
of things,

(b) to conceive rightly what they can undergo and what they cannot,

(c) to compare [the nature of things] with the nature and power of man.

This done, the highest perfection man can reach will easily manifest itself.

[25] [26] Having considered these requirements, let us see which mode of
perceiving we ought to choose.

As for the first, it is evident in itself that from report—apart from the fact
that it is a very uncertain thing—we do not perceive any essence of a thing,
as is clear from our example. And since the existence [30] of any singular
thing[23](part0013.html#ch1fn42) is not known unless its essence is known (as
we shall see afterwards), we can clearly infer from this that all the
certainty we have from report is to be excluded from the sciences. For no one
will ever be able to be affected by simple report, unless his own intellect
has gone before.

[II/13] [27] As for the second,[i](part0013.html#ch1fn43) again, no one should
be said to have the idea of that[24](part0013.html#ch1fn44) proportion which
he is seeking. Apart from the fact that it is a very uncertain thing, and
without end, in this way no one will ever perceive anything in natural things
except accidents. But these [5] are never understood clearly unless their
essences are known first. So that also is to be excluded.

[28] Concerning the third, on the other hand, we can, in a sense, say that we
have an idea of the thing, and that we can also make inferences without danger
of error. But still, it will not through itself [10] be the means of our
reaching our perfection.

[29] Only the fourth mode comprehends the adequate essence of the thing and is
without danger of error. For that reason, it is what we must chiefly use. So
we shall take care to explain how it is to be used, that we may understand
unknown things by this kind of knowledge [15] and do so as directly as
possible; [30] [NS: i.e.] after we know what Knowledge is necessary for us, we
must teach the Way and Method by which we may achieve this kind of knowledge
of the things that are to be known.

To do this, the first thing we must consider is that there is no infinite
regress here. That is, to find the best Method of seeking the [20] truth,
there is no need of another Method to seek the Method of seeking the truth, or
of a third Method to seek the second, and so on, to infinity. For in that way
we would never arrive at knowledge of the truth, or indeed at any knowledge.

Matters here stand as they do with corporeal tools,[25](part0013.html#ch1fn45)
where someone [25] might argue in the same way. For to forge iron a hammer is
needed; and to have a hammer, it must be made; for this another hammer, and
other tools are needed; and to have these tools too, other tools will be
needed, and so on to infinity; in this way someone might try, in vain, to
prove that men have no power of forging iron.

[30] [31] But just as men, in the beginning, were able to make the easiest
things with the tools they were born with (however laboriously and
imperfectly), and once these had been made, made other, more difficult things
with less labor and more perfectly, and so, proceeding [II/14] gradually from
the simplest works to tools, and from tools to other works and tools, reached
the point where they accomplished so many and so difficult things with little
labor, in the same way the intellect, by its inborn
power,[k](part0013.html#ch1fn46) makes intellectual tools for itself, by which
it [5] acquires other powers for other intellectual
works,[l](part0013.html#ch1fn47) and from these works still other tools, or
the power of searching further, and so proceeds by stages, until it reaches
the pinnacle of wisdom.

[32] It will be easy to see that this is the situation of the intellect,
provided we understand what the Method of seeking the truth is, and [10] what
those inborn tools are, which it requires only[26](part0013.html#ch1fn48) to
make other tools from them, so as to advance further. To show this, I proceed
as follows.

[33] A[27](part0013.html#ch1fn49) true idea[m](part0013.html#ch1fn50) (for we
have a true idea) is something different from its object. For a circle is one
thing and an idea of the circle [15] another—the idea of the circle is not
something which has a circumference and a center, as the circle does. Nor is
an idea of the body the body itself. And since it is something different from
its object, it will also be something intelligible through itself; that is,
the idea, as far as its formal essence is concerned, can be the object of
another objective essence, and this other objective essence in turn will also
be, considered [20] in itself, something real and intelligible, and so on,
indefinitely.

[34] Peter, for example, is something real; but a true idea of
Peter[28](part0013.html#ch1fn51) is an objective essence of Peter, and
something real in itself, and altogether different from Peter himself. So
since an idea of Peter is something real, having its own particular essence,
it will also be something intelligible, i.e., the object of a second idea,
which will have in [25] itself, objectively, whatever the idea of Peter has
formally; and in turn, the idea which is [the idea] of the idea of Peter has
again its essence, which can also be the object of another idea, and so on
indefinitely. Everyone can experience this, when he sees that he knows what
Peter is, and also knows that he knows, and again, knows that he knows that he
knows, etc.

[30] From this it is evident that to understand the essence of Peter, it is
[II/15] not necessary to understand an idea of Peter, much less an idea of an
idea of Peter. This is the same as if I said that, in order for me to know, it
is not necessary to know that I know, much less necessary to know that I know
that I know—no more than it is necessary to understand the essence of a circle
in order to understand the essence [5] of a
triangle.[n](part0013.html#ch1fn52) Indeed, in these ideas the opposite is the
case. For to know that I know, I must first know.

[35] From this it is clear that certainty is nothing but the objective essence
itself, i.e., the mode by which we are aware of the formal
essence[29](part0013.html#ch1fn53) is certainty itself. And from this, again,
it is clear that, for [10] the certainty of the truth, no other sign is needed
than having a true idea. For as we have shown, in order for me to know, it is
not necessary to know that I know. From which, once more, it is clear that no
one can know what the highest certainty is unless he has an adequate idea or
objective essence of some thing. For certainty and an objective essence are
the same thing.

[15] [36] Since truth, therefore, requires no sign, but it suffices, in order
to remove all doubt, to have the objective essences of things, or, what is the
same, ideas, it follows that the true Method is not to seek a sign of truth
after the acquisition of ideas, but the true Method is the way [20] that truth
itself, or the objective essences of things, or the ideas (all those signify
the same) should be sought[o](part0013.html#ch1fn54) in the proper order.

[37] Again, the Method must speak about Reasoning,
or[30](part0013.html#ch1fn55) about the intellection; i.e., Method is not the
reasoning itself by which we understand the causes of things, much less the
understanding of the causes of things; it is understanding what a true idea is
by distinguishing it [25] from the rest of the perceptions; by investigating
its nature, so that from that we may come to know our power of understanding
and so restrain the mind that it understands, according to that standard,
everything that is to be understood; and finally by teaching and constructing
certain rules as aids, so that the mind does not weary itself in useless
things.

[30] [38] From this it may be inferred that Method is nothing but a [II/16]
reflexive knowledge, or an idea of an idea; and because there is no idea of an
idea, unless there is first an idea, there will be no Method unless there is
first an idea. So that Method will be good which shows how the mind is to be
directed according the standard of a given true
idea.[31](part0013.html#ch1fn56)

[5] Next, since the relation between the two ideas is the same as the relation
between the formal essences of those ideas, it follows that the reflexive
knowledge of the idea of the most perfect Being will be more excellent than
the reflexive knowledge of any other ideas. That is, the most perfect Method
will be the one that shows how the mind is to be directed according to the
standard of the given idea of the most [10] perfect Being.

[39] From this you will easily understand how the mind, as it understands more
things, at the same time acquires other tools, with which it proceeds to
understand more easily. For, as may be inferred from what has been said,
before all else there must be a true idea in us, as an inborn tool; once this
true idea is understood, we understand [15] the difference between that kind
of perception and all the rest. Understanding that difference constitutes one
part of the Method.

And since it is clear through itself that the mind understands itself the
better, the more it understands of Nature, it is evident, from that that this
part of the Method will be more perfect as the mind understands more things,
and will be most perfect when the mind attends [20] to, _or_ reflects on,
knowledge of the most perfect Being.

[40] Next, the more the mind knows, the better it understands its own powers
and the order of Nature. The better the mind understands its own powers, the
more easily it can direct itself and propose rules to itself; the better it
understands the order of Nature, the more easily it can restrain itself from
useless pursuits. In these things, as [25] we have said, the whole of the
Method consists.

[41] Moreover, the idea is objectively in the same way as its object is
really. So if there were something in Nature that did not interact with other
things, and if there were an objective essence of that thing which would have
to agree completely with its formal essence, then [30] that objective essence
would not interact[p](part0013.html#ch1fn57) with other ideas, i.e., we could
not infer anything about it.[32](part0013.html#ch1fn58) And conversely, those
things that do interact with other things (as everything that exists in Nature
does) will be understood, and their objective essences will also have the same
interaction, i.e., other ideas will be deduced from them, and [II/17] these
again will interact with other ideas, and so the tools for proceeding further
will increase, which is what we were trying to demonstrate.

[42] Next, from what we have just said, that an idea must agree completely
with its formal essence, it is again evident that for our mind [5] to
reproduce completely the likeness of Nature,[33](part0013.html#ch1fn59) it
must bring all of its ideas forth from that idea which represents the source
and origin of the whole of Nature, so that that idea is also the source of the
other ideas.

[43] Here, perhaps, someone will be surprised that, having said that a good
Method is one which shows how the mind is to be directed [10] according to the
standard of a given true idea, we should prove this by reasoning. For that
seems to show that this is not known through itself. So it may be asked
whether our reasoning is good? If our reasoning is good, we must begin from a
given [true?] idea; and since to begin from a given [true?] idea requires a
demonstration, we must again prove our reasoning, and then once more prove
that other reasoning, [15] and so on to infinity.

[44] To this I reply that if, by some fate, someone had proceeded in this way
in investigating Nature, i.e., by acquiring other ideas in the proper order,
according to the standard of the given true idea, he would never have
doubted[q](part0013.html#ch1fn60) the truth he possessed (for as we have
shown, the truth makes itself manifest) and also everything would have flowed
to him of its own accord.[34](part0013.html#ch1fn61)

[20] But because this never or rarely happens, I have been forced to lay
things down in this way, so that what we cannot acquire by fate, we may still
acquire by a deliberate plan, and at the same time so that it would be evident
that to prove the truth and good reasoning, we require no tools except the
truth itself and good reasoning. For I have [25] proved, and still strive to
prove, good reasoning by good reasoning. [45] Moreover, in this way men become
accustomed to their own internal meditations.

But the reason why Nature is rarely investigated in the proper order, is,
first, that men have prejudices whose causes we shall explain afterwards in
our Philosophy. And then, the task requires a considerable [30] capacity for
making accurate distinctions (as we shall show later) and much effort.
Finally, there is the condition of human affairs, which are quite changeable,
as we have already shown. There are still other reasons, which we shall not go
into.

[II/18] [46] If, by chance, someone should ask why I did
[not][35](part0013.html#ch1fn62) immediately, before anything else, display
the truths of Nature in that order—for does not the truth make itself
manifest?—I reply to him […] and at the same time I warn him not to try to
reject these things as false because of Paradoxes that occur here and there;
he should first [5] deign to consider the order in which we prove them, and
then he will become certain that we have reached the truth; and this was the
reason why I have put these things first.

[47] But perhaps, afterwards, some Skeptic would still doubt both the first
truth itself and everything we shall deduce according to the [10] standard of
the first truth. If so, then either he will speak contrary to his own
conciousness, or we shall confess that there are men whose minds also are
completely blinded, either from birth, or from prejudices, i.e., because of
some external chance. For they are not even aware of themselves. If they
affirm or doubt something, they do not know that they affirm or doubt. They
say that they know nothing, [15] and that they do not even know that they know
nothing. And even this they do not say absolutely. For they are afraid to
confess that they exist, so long as they know nothing. In the end, they must
be speechless, lest by chance they assume something that might smell of truth.

[48] Finally, there is no speaking of the sciences with them. (For as far as
the needs of life and society are concerned, necessity forces them [20] to
suppose that they exist, and to seek their own advantage, and in taking oaths,
to affirm and deny many things.) For, if someone proves something to them,
they do not know whether the argument is a proof or not. If they deny, grant,
or oppose, they do not know that they deny, grant, or oppose. So they must be
regarded as automata, completely [25] lacking a mind.

[49] Let us now return to our subject. First [§§ 1-17], we have treated the
end toward which we strive to direct all our thoughts; second [§§ 18-29], we
learned which is the best perception, by whose aid we can reach our
perfection; third [§§ 30-48], we learned which is the first [30] path our mind
must enter on to begin well—which is to proceed in its investigation according
to certain laws, taking as a standard a given true idea.

If this is to be done properly, the Method must, first [§§ 50-90], show how to
distinguish a true idea from all other perceptions, and to restrain the mind
from those other perceptions; second [§§ 91-98], [35] teach rules so that we
may perceive things unknown according to such [II/19] a standard; third [§
99-?], establish an order, so that we do not become weary with trifles. When
we came to know this Method [§ 38], we saw, fourth, that it will be most
perfect when we have the idea of the most perfect Being. So in the beginning
we must take the greatest care [5] that we arrive at knowledge of such a Being
as quickly as possible.

[50] Let us begin, therefore, from the first part of the Method, which is, as
we have said, to distinguish and separate true ideas from all other
perceptions, and to restrain the mind from confusing false, fictitious, and
doubtful ideas with true ones. It is my intention to explain this fully here,
so as to engage my Readers in the thought of a thing so [10] necessary, and
also because there are many who doubt even true ideas, from not attending to
the distinction between a true perception and all others. So they are like men
who, when they were awake, used not to doubt that they were awake, but who,
after they once thought in a dream that they were certainly awake (as often
happens), and later [15] found that to be false, doubted even of their waking
states. This happens because they have never distinguished between the
dream[36](part0013.html#ch1fn63) and the waking state.

[51] In the meantime, I warn the reader that I shall not discuss the essence
of each perception, and explain it by its proximate[37](part0013.html#ch1fn64)
cause, because that pertains to Philosophy, but shall discuss only what the
[20] Method demands, i.e., what false, fictitious and doubtful ideas are
concerned with, and how we shall be freed from each of them. Let the first
inquiry, therefore, be about the fictitious idea.

[52] Since every perception is either of a thing considered as existing, or of
an essence alone, and since fictions occur more frequently [25] concerning
things considered as existing, I shall speak first of them—i.e., where
existence alone is feigned, and the thing which is feigned in such an act is
understood, _or_ assumed to be understood. E.g., I feign that Peter, whom I
know, is going home, that he is coming to visit me, and the
like.[r](part0013.html#ch1fn65) Here I ask, what does such an idea concern? I
[30] see that it concerns only possible, and not necessary or impossible
things.

[53] I call a thing impossible whose nature[38](part0013.html#ch1fn66) implies
that it would be contradictory for it to exist; necessary whose nature implies
that it [II/20] would be contradictory for it not to exist; and possible whose
existence,[39](part0013.html#ch1fn67) by its very nature, does not imply a
contradiction—either for it to exist or for it not to exist—but whose
necessity or impossibility of existence depends on causes unknown to us, so
long as we feign its [5] existence. So if its necessity or impossibility,
which depends on external causes, were known to us, we would have been able to
feign nothing concerning it.

[54] From this it follows that, if there is a God, or something omniscient, he
can feign nothing at all.[40](part0013.html#ch1fn68) For as far as We are
concerned, after I know that I exist,[s](part0013.html#ch1fn69) I cannot feign
either that I exist or that I do [10] not exist; nor can I feign an elephant
which passes through the eye of a needle; nor, after I know the nature of God,
can I feign either that he exists or that he does not
exist.[t](part0013.html#ch1fn70) The same must be understood of the Chimera,
whose nature implies that it would be contradictory for it to exist. From this
what I have said is evident: that the fiction of which we are speaking here
does not occur concerning eternal truths.[u](part0013.html#ch1fn71) [15] I
shall also show immediately that no fiction is concerned with eternal truths.

[55] But before proceeding further, I must note here in passing that the same
difference that exists between the essence of one thing and the essence of
another also exists between the actuality or existence of [20] the one thing
and the actuality or existence of the other. So if we wished to conceive the
existence of Adam, for example, through existence in general, it would be the
same as if, to conceive his essence, we attended to the nature of being, so
that in the end we defined him by saying that Adam is a being. Therefore, the
more generally existence [25] is conceived, the more confusedly also it is
conceived, and the more easily it can be ascribed fictitiously to anything.
Conversely, the more particularly it is conceived, then the more clearly it is
understood, and the more difficult it is for us, [even] when we do not attend
[II/21] to the order of Nature, to ascribe it fictitiously to anything other
than the thing itself.[41](part0013.html#ch1fn72) This is worth noting.

[56] Now we must consider those things that are commonly said to be feigned,
although we understood clearly that the thing is not really [5] as we feign
it. E.g., although I know that the earth is round, nothing prevents me from
saying to someone that the earth is a hemisphere and like half an orange on a
plate, or that the sun moves around the earth, and the like. If we attend to
these things, we shall see nothing that is not compatible with what we have
already said, provided we [10] note first that we have sometimes been able to
err, and now are conscious of our errors; and then, we can feign, or at least
allow, that other men are in the same error, or can fall into it, as we did
previously.

We can feign this, I say, so long as we see no impossibility and no [15]
necessity. Therefore, when I say to someone that the earth is not round, etc.,
I am doing nothing but recalling the error which I, perhaps, made, or into
which I could have fallen, and afterwards feigning, or allowing, that he to
whom I say this is still in the same error, or can fall into it. As I have
said, I feign this so long as I see no [20] impossibility and no necessity.
For if I had understood this, I could have feigned nothing at all, and it
would have had to be said only that I had done
something.[42](part0013.html#ch1fn73)

[57] It remains now to note also those things that are supposed in Problems.
This sometimes happens even concerning impossible things. E.g., when we say
“Let us suppose that this burning candle is not [25] now burning, or let us
suppose that it is burning in some imaginary space, _or_ where there are no
bodies.” Things like this are sometimes supposed, although this last is
clearly understood to be impossible.[43](part0013.html#ch1fn74) But when this
happens, nothing at all is feigned. For in the first case [II/22] I have done
nothing but recall to memory[x](part0013.html#ch1fn75) another candle that was
not burning (or I have conceived this candle without the flame), and what I
think about that candle, I understand concerning this one, so long as I do not
attend to the flame.

In the second case, nothing is done except to abstract the thoughts [5] from
the surrounding bodies so that the mind directs itself toward the sole
contemplation of the candle, considered in itself alone, so that afterwards it
infers that the candle has no cause for its destruction. So if there were no
surrounding bodies, this candle, and its flame, would remain immutable, or the
like. Here, then, there is no fiction, but[y](part0013.html#ch1fn76) [10] true
and sheer assertions.[44](part0013.html#ch1fn77)

[58] Let us pass now to fictions that concern either essences alone or
essences together with some actuality _or_ existence. The most important
consideration regarding them is that the less the mind understands and the
more things it perceives, the greater its power of feigning [15] is; and the
more things it understands, the more that power is diminished.

For example, as we have seen above, we cannot feign, so long as we are
thinking, that we are thinking and are not thinking; in the same way, after we
know the nature of body, we cannot feign an infinite [20] fly, or after we
know the nature of the soul,[z](part0013.html#ch1fn78) we cannot feign that it
is square, though there is nothing that cannot be put into words.

But as we have said, the less men know Nature, the more easily they can feign
many things, such as, that trees speak, that men are changed in a moment into
stones and into springs, that nothing becomes something, that even Gods are
changed into beasts and into [25] men, and infinitely many other things of
that kind.[45](part0013.html#ch1fn79)

[II/23] [59] Someone, perhaps, will think that fiction is limited by fiction,
but not by intellection.[46](part0013.html#ch1fn80) That is, after I have
feigned something, and willed by a certain freedom to assent that it exists in
nature in this way, this has the consequence that I cannot afterwards think it
in any [5] other way. For example, after I have feigned (to speak as they do)
that body has such a nature, and willed, from my freedom, to be convinced that
it really exists in this way, I can no longer feign an infinite fly; and after
I have feigned the essence of the soul, I can no longer feign that it is
square.

[60] But this needs to be examined. First, either they deny or they grant that
we can understand something. If they grant it, then necessarily [10] what they
say about fiction will also have to be said about intellection. But if they
deny it, let us—who know that we know something—see what they say.

Evidently, they say that the soul can sense and perceive in many ways, not
itself, nor the things that exist, but only those things that [15] are neither
in itself nor anywhere; that is, the soul can, by its own force alone, create
sensations or ideas, which are not of things; so they consider it, to some
extent, as like God.[47](part0013.html#ch1fn81)

Next, they say that we, or our soul, has such a freedom that it compels us, or
itself, indeed its own freedom. For after it has feigned something, and
offered its assent to it, it cannot think or feign it in any other way, and is
also compelled by that fiction so that even other [20] things are thought in
such a way as not to conflict with the first fiction, just as here too because
of their own fiction, they are forced to admit the absurdities which I review
here, and which we shall not bother to refute with any demonstrations.

[25] [61] Rather, leaving them to their madness, we shall take care to draw
from the words we have exchanged with them something true and to our purpose,
viz.:[a](part0013.html#ch1fn82) when the mind attends to a fictitious thing
which is false by its very nature, so that it considers it carefully, and
understands it, and deduces from it in good order the things to be deduced, it
will easily bring its falsity to light. And if the fictitious [II/24] thing is
true by its nature, then when the mind attends to it, so that it understands
it, and begins to deduce from it in good order the things that follow from it,
it will proceed successfully, without any interruption—just as we have seen
that, from the false fiction just mentioned, the intellect immediately applies
itself to show its absurdity, and the [5] other things deduced from that.

[62] So we ought not to fear in any way that we are [merely] feigning
something, if only we perceive the thing clearly and distinctly. For if by
chance we should say that men are changed in a moment into beasts, that is
said very generally, so that there is in the mind no concept, i.e., [10] idea,
_or_ connection of subject and predicate. For if there were any concept, the
mind would see together the means and causes, how and why such a thing was
done. And one does not attend to the nature of the subject and of the
predicate.

[63] Next, provided the first idea is not fictitious, and all the other ideas
are deduced from it, the haste to feign things will gradually [15] disappear.
And since a fictitious idea cannot be clear and distinct, but only confused,
and since all confusion results from the fact that the mind knows only in part
a thing that is a whole, or composed of many things, and does not distinguish
the known from the unknown (and besides, attends at once, without making any
distinction, to the many [20] things that are contained in each thing), from
this it follows, first, that if an idea is of some most simple thing, it can
only be clear and distinct. For that thing will have to become known, not in
part, but either as a whole or not at all.[48](part0013.html#ch1fn83)

[64] Secondly, it follows that if, in thought, we divide a thing that is
composed of many things into all its most simple parts, and attend [25] to
each of these separately, all confusion will disappear.

Thirdly, it follows that a fiction cannot be simple, but that it is made from
the composition of different confused ideas, which are different things and
actions existing in nature; or rather, from attending at
once,[b](part0013.html#ch1fn84) without assent, to such different ideas. For
if it were simple, [30] it would be clear and distinct, and consequently true.
And if it were made from the composition of distinct ideas, their composition
would [II/25] also be clear and distinct, and therefore true. For example,
once we know the nature of the circle, and also the nature of the square, we
cannot then compound these two and make a square circle, or a square soul, and
the like.

[5] [65] Let us sum up again briefly, and see why we do not need to fear that
the fiction will in any way be confused with true ideas. For as for the first
[fiction][49](part0013.html#ch1fn85) of which we spoke before, viz. where the
thing is clearly conceived, we saw that if that thing that is clearly
conceived (and also its existence) is, through itself, an eternal truth, we
[10] can feign nothing concerning such a thing. But if the existence of the
thing conceived is not an eternal truth, we need only to take care to compare
the existence of the thing with its essence, and at the same time attend to
the order of Nature.

As for the second fiction, we said that it consists in attending at once,
without assent, to different confused ideas, which are of different [15]
things and actions existing in Nature. We saw also that a most simple thing
cannot be feigned, but [only] understood, and also that a composite thing can
be understood, provided that we attend to the most simple parts of which it is
composed. Indeed we also cannot feign from them any actions that are not true;
for at the same time we will be forced to consider how and why such a thing
happened.

[20] [66] With these matters thus understood, let us pass now to the
investigation of the false idea so that we may see what it is concerned with,
and how we can take care not to fall into false perceptions. Neither of these
will be difficult for us now, after our investigation of the fictitious idea.
For between fictitious and false ideas there is no [25] other difference
except that the latter suppose assent; i.e. (as we have already noted), while
the presentations appear to him [who has the false idea], there appear no
causes from which he can infer (as he who is feigning can) that they do not
arise from things outside him. And this is hardly anything but dreaming with
open eyes, _or_ while we are awake. Therefore the false idea is concerned
with, or (to put it better) [30] is related to the existence of a thing whose
essence is known, _or_ to an essence, in the same way as a fictitious idea.

[67] [The false idea] that is related to existence is emended in the same way
as the fiction. For if the nature of the thing known presupposes necessary
existence, it is impossible for us to be deceived concerning the existence of
that thing. But if the existence of the thing is not an eternal truth (as its
essence is), so that[50](part0013.html#ch1fn86) its necessity or impossibility
[35] of existing depends on external causes, then take everything in [II/26]
the same way as we said when we were speaking of fictions. For it may be
emended in the same way.

[68] As for the other kind of false idea, which is related to essences, or
also to actions, such perceptions must always be confused, composed [5] of
different confused perceptions of things existing in nature—as when men are
persuaded that there are divinities in the woods, in images, in animals, etc.;
or that there are bodies from whose composition alone the intellect is made;
or that corpses reason, walk, and speak; or that God is deceived, and the
like. But ideas that are clear [10] and distinct can never be false. For the
ideas of things that are conceived clearly and distinctly, are either most
simple, or composed of most simple ideas, i.e., deduced from most simple
ideas. But that a most simple idea cannot be false, anyone can see—provided
that he knows what the true is, _or_ the intellect, and at the same time, what
the false is.

[15] [69] As for what constitutes the form of the true, it is certain that a
true thought is distinguished from a false one not only by an extrinsic, but
chiefly by an intrinsic denomination. For if some architect conceives a
building in an orderly fashion, then although such a building never existed,
and even never will exist, still the thought of it is true, [20] and the
thought is the same, whether the building exists or
not.[51](part0013.html#ch1fn87) On the other hand, if someone says, for
example, that Peter exists, and nevertheless does not know that Peter exists,
that thought, in respect to him is false, or, if you prefer, is not true, even
though Peter really exists. Nor is this statement, Peter exists, true, except
in respect to [25] him who knows certainly that Peter exists.

[70] From this it follows that there is something real in ideas, through which
the true are distinguished from the false. This will now have to be
investigated, so that we may have the best standard of truth (for we have said
that we must determine our thoughts from the given standard of a true idea,
and that method is reflexive knowledge), and [30] may know the properties of
the intellect. Nor must we say that this difference arises from the fact that
the true thought is knowing things through their first
causes.[52](part0013.html#ch1fn88) In this, indeed, it differs greatly from
the false, as I have explained it above. For that Thought is also called true
which involves objectively the essence of some principle that does not have a
cause, and is known through itself and in itself.

[35] [71] So the form of the true thought[53](part0013.html#ch1fn89) must be
placed in the same [II/27] thought itself without relation to other things,
nor does it recognize the object as its cause, but must depend on the very
power and nature of the intellect. For if we should suppose that the intellect
had perceived some new being, which has never existed (as some conceive [5]
God’s intellect, before he created things—for that perception, of course,
could not have arisen from any object), and that from such a perception it
deduced others legitimately, all those thoughts would be true, and determined
by no external object, but would depend only on the power and nature of the
intellect. So what constitutes the form of the [10] true thought must be
sought in the same thought itself, and must be deduced from the nature of the
intellect.

[72] To investigate this, therefore, let us consider some true idea, of which
we know most certainly that its object depends on our power of thinking, and
that it has no object in nature. For it is clear from what has already been
said that we shall be able more easily to investigate [15] what we wish to in
such an idea. E.g., to form the concept of a sphere, I feign a cause at will,
say that a semicircle is rotated around a center, and that the sphere is, as
it were, produced by this rotation. This idea, of course, is true, and even
though we may know that no sphere in nature was ever produced in this way,
nevertheless, this perception is true, and a very easy way of forming the
concept of a sphere.

[20] Now it must be noted that this perception affirms that the semicircle is
rotated, which affirmation would be false if it were not joined to the concept
of a sphere, or to a cause determining such a motion, _or_ absolutely, if this
affirmation were isolated. For then the mind would only tend to affirm of the
semicircle nothing but motion, which neither is contained in the concept of
the semicircle nor arises from the [25] concept of the cause determining the
motion. So falsity consists only in this: that something is affirmed of a
thing that is not contained in the concept we have formed of the thing, as
motion or rest of the semicircle.

From this it follows that simple thoughts cannot but be true; for example, the
simple idea of a semicircle, or of motion, or of quantity, [30] etc. Whatever
they contain of affirmation matches their concept, and does not extend itself
beyond [the concept]. So we may form simple ideas at will, without fear of
error.

[73] It only remains, then, to ask by what power our mind can form these
[simple ideas] and how far this power extends. For once this is [35]
discovered, we shall easily see the highest knowledge we can reach. It [II/28]
is certain that this power does not extend to infinity. For when we affirm of
a thing something not contained in the concept we form of it, that indicates a
defect of our perception, _or_ that we have thoughts, [5] _or_ ideas, which
are, as it were, mutilated and maimed. For we saw that the motion of a
semicircle is false when it is in the mind in isolation, but true if it is
joined to the concept of a sphere, or to the concept of some cause determining
such a motion. But if it is—as it seems at first[54](part0013.html#ch1fn90)—of
the nature of a thinking being to form true, _or_ [10] adequate, thoughts, it
is certain that inadequate ideas arise in us only from the fact that we are a
part of a thinking being, of which some thoughts wholly constitute our mind,
while others do so only in part.

[74] But we still need to consider something which was not worth [15] the
trouble of noting concerning fictions, and which gives rise to the greatest
deception—viz. when it happens that certain things that appear in the
imagination are also in the intellect, i.e., that they are conceived clearly
and distinctly. For then, so long as the distinct is not distinguished from
the confused, certainty, i.e., a true idea, is mixed up with what is not
distinct.

[20] For example, some of the Stoics heard, perhaps, the word _soul_ , and
also that the soul is immortal, which they only imagined confusedly; they also
both imagined and at the same time understood that the most subtle bodies
penetrate all others, and are not penetrated by any. Since they imagined all
these things at once—while remaining certain of this [25] axiom—they
immediately became certain that the mind was those most subtle
bodies[55](part0013.html#ch1fn91) and that those most subtle bodies were not
divided, etc.

[75] But we are freed from this also, as long as we strive to consider all our
perceptions according to the standard of a given true idea, being on guard, as
we said in the beginning, against those we have from report or from random
experience. Moreover, such a deception [30] arises from the fact that they
conceive things too abstractly. For it is sufficiently clear through itself
that I cannot apply what I conceive in its true object to something else.
Finally, it arises also from the fact that they do not understand the first
elements of the whole of Nature; so proceeding without order, and confusing
Nature with abstractions [35] (although they are true axioms), they confuse
themselves and overturn [II/29] the order of Nature. But we shall not need to
fear any such deception, if we proceed as far as we can in a manner that is
not abstract, and begin as soon as possible from the first elements, i.e.,
from the source and origin of Nature.[56](part0013.html#ch1fn92)

[5] [76][57](part0013.html#ch1fn93) But as for knowledge of the origin of
Nature, we need not have any fear of confusing it with abstractions. For when
things are conceived abstractly (as all universals are), they always have a
wider extension in our intellect than their particulars can really have in
nature. And then, since there are many things in nature whose difference [10]
is so slight that it almost escapes the intellect, it can easily happen, if
they are conceived abstractly, that they are confused. But since, as we shall
see later, the origin of Nature can neither be conceived abstractly, _or_
universally, nor be extended more widely in the intellect than it really is,
and since it has no likeness to changeable things, we [15] need fear no
confusion concerning its idea, provided that we have the standard of truth
(which we have already shown). For it is a unique and
infinite[z](part0013.html#ch1fn94) being, beyond which there is no
being.[a](part0013.html#ch1fn95)

[77] So far we have been speaking of the false idea. It remains now [20] to
investigate the doubtful idea—i.e., to ask what are the things that can lead
us into doubt, and at the same time, how doubt is removed. I am speaking of
true doubt in the mind, and not of what we commonly see happen, when someone
says in words that he doubts, although his mind does not doubt. For it is not
the business of the Method to emend that. That belongs rather to the
investigation of [25] stubbornness, and its emendation.

[78] There is no doubt in the soul, therefore, through the thing itself
concerning which one doubts. That is, if there should be only one idea in the
soul, then, whether it is true or false, there will be neither doubt nor
certainty, but only a sensation of a certain sort. For in itself [this idea]
is nothing but a sensation of a certain sort.

[30] But doubt will arise through another idea which is not so clear and
distinct that we can infer from it something certain about the thing [II/30]
concerning which there is doubt. That is, the idea that puts us in doubt is
not clear and distinct. For example, if someone has never been led, either by
experience or by anything else, to think about the deceptiveness of the
senses, he will never doubt whether the sun is larger or smaller than it
appears to be. So Country People are generally [5] surprised when they hear
that the sun is much larger than the earth. But in thinking about the
deceptiveness of the senses, doubt arises. I.e., [the person] knows that his
senses have sometimes deceived him, but he knows this only confusedly; for he
does not know how the senses deceive.[58](part0013.html#ch1fn96) And if
someone, after doubting, acquires a true knowledge of the senses and of how,
by their means, things at a [10] distance are presented, then the doubt is
again removed.

[79] From this it follows that, only so long as we have no clear and distinct
idea of God, can we call true ideas in doubt by supposing that perhaps some
deceiving God exists, who misleads us even in the things most certain. I.e.,
if we attend to the knowledge we have concerning [15] the origin of all things
and do not discover—by the same knowledge we have when, attending to the
nature of the triangle, we discover that its three angles equal two right
angles—anything that teaches us that he is not a deceiver [NS:, then the doubt
remains]. But if we have the kind of knowledge of God that we have of the
triangle, then all [20] doubt is removed. And just as we can arrive at such a
knowledge of the triangle, even though we may not know certainly whether some
supreme deceiver misleads us, so we can arrive at such a knowledge of God,
even though we may not know whether there is some supreme deceiver. Provided
we have that knowledge, it will suffice, as I have [25] said, to remove every
doubt that we can have concerning clear and distinct ideas.

[80] Further, if someone proceeds rightly, by investigating [first] those
things which ought to be investigated first, with no interruption in the
connection of things, and knows how to define problems
precisely,[59](part0013.html#ch1fn97) before striving for knowledge of them,
he will never have anything but the most certain ideas—i.e., clear and
distinct ideas. For [30] doubt is nothing but the suspension of the mind
concerning some affirmation or negation, which it would affirm or deny if
something did not occur to it, the ignorance of which must render its
knowledge of the thing imperfect. From this it is [to be] inferred that doubt
always arises from the fact that things are investigated without order.

[35] [81] These are the matters I promised to discuss in this first part of
[II/31] the Method. But to omit nothing that can lead to knowledge of the
intellect and its powers, I shall say a few words about memory and forgetting.
The most important consideration is that memory is strengthened both with the
aid of the intellect and also without its aid. [5] For regarding the first,
the more intelligible a thing is, the more easily it is retained; and
conversely, the less intelligible, the more easily forgotten. E.g., if I give
someone a large number of disconnected words, he will retain them with much
more difficulty than if I give him the same words in the form of a story.

[82] It is also strengthened without the aid the intellect, by the force [10]
with which the imagination, or what they call the common sense, is affected by
some singular corporeal thing. I say _singular_ , for the imagination is
affected only by singular things. If someone, e.g., has read only one
Comedy,[60](part0013.html#ch1fn98) he will retain it best so long as he does
not read several others of that kind, for then it will flourish in isolation
in the [15] imagination. But if there are several of the same kind, we imagine
them all together and they are easily confused. I say also _corporeal_ , for
the imagination is affected only by bodies. Therefore since the memory is
strengthened both by the intellect and also without the intellect, we may
infer that it is something different from the intellect, and that concerning
the intellect considered in itself there is neither memory nor forgetting.

[20] [83] What, then, will memory be? Nothing but a sensation of impressions
on the brain, together with the thought of a determinate
duration[d](part0013.html#ch1fn99) of the sensation, which recollection also
shows. For there the soul thinks of that sensation, but not under a continuous
duration. And so the idea of that sensation is not the duration itself of the
sensation, [25] i.e., the memory itself. But whether the ideas themselves
undergo some corruption, we shall see in [my] Philosophy.

If this seems quite absurd to anyone, it will suffice for our purpose if he
thinks that the more singular a thing is, the more easily it may be retained,
as the example of the Comedy just mentioned makes clear. [II/32] Further, the
more intelligible a thing is, the more easily it too is retained. So we cannot
but retain a thing that is most singular if only it is also intelligible.

[84] In this way, then, we have distinguished between a true idea [5] and
other perceptions, and shown that the fictitious, the false, and the other
ideas have their origin in the imagination, i.e., in certain sensations that
are fortuitous, and (as it were) disconnected; since they do not arise from
the very power of the mind, but from external causes, as the body (whether
waking or dreaming) receives various motions.

[10] But if you wish, take imagination any way you like here, provided it is
something different from the intellect, and in which the soul has the nature
of something acted on. For it is all the same, however you take it, after we
know that it is something random, by which the soul is acted on, and at the
same time know how we are freed from it with the help of the intellect. So let
no one be surprised that here, where I [15] have not yet proved that there is
a body, and other necessary things, I speak of the imagination, the body and
its constitution. For as I have said, it does not matter what I take it to be,
after I know that it is something random, etc.[62](part0013.html#ch1fn100)

[85] We have shown that a true idea is simple, or composed of [20] simple
ideas; that it shows how and why something is, or has been done; and that its
objective effects proceed in the soul according to the formal nature of its
object. This is the same as what the ancients said, i.e., that true knowledge
proceeds from cause to effect—except that so far as I know they never
conceived the soul (as we do here) as acting [25] according to certain laws,
like a spiritual automaton.

[86] From this we have acquired as much knowledge of our intellect as was
possible in the beginning, and such a standard of the true idea that now we do
not fear confusing true ideas with false or fictitious ones. Nor will we
wonder why we understand certain things that do [30] not fall in any way under
the imagination, why there are some things in the imagination which are
completely opposed to the intellect, and finally why there are others that
agree with the intellect; for we know that those activities by which
imaginations are produced happen according to other laws, wholly different
from the laws of the intellect, and that in imagination the soul only has the
nature of something acted on.

[35] [87] From this it is also established how easily they can fall into
[II/33] great errors, who have not accurately distinguished between
imagination and intellection. Such errors as: that extension must be in a
place, that it must be finite, that its parts must be really distinguished
from one another, that it is the first and only foundation of all things, [5]
that it occupies more space at one time than at another, and many other things
of the same kind, all of which are completely opposed to the truth, as we
shall show in the proper place.

[88] Next, since words are part of the imagination, i.e., since we feign many
concepts, in accordance with the random composition of [10] words in the
memory from some disposition of the body, it is not to be doubted that words,
as much as the imagination, can be the cause of many and great errors, unless
we are very wary of them.

[89] Moreover, they are established according to the pleasure and power of
understanding of ordinary people, so that they are only signs of things as
they are in the imagination, but not as they are in the [15] intellect. This
is clear from the fact that the names given to things that are only in the
intellect, and not in the imagination, are often negative (for example,
infinite, incorporeal, etc.), and also from the fact that they express
negatively many things that are really affirmative, and conversely (for
example, uncreated, independent, infinite, [20] immortal). Because the
contraries of these are much more easily imagined, they occurred first to the
earliest men, and they used positive names. We affirm and deny many things
because the nature of words—not the nature of things—allows us to affirm them.
And in our ignorance of this, we easily take something false to be true.

[25] [90] We avoid, moreover, another great cause of confusion which prevents
the intellect from reflecting on itself—viz. when we do not distinguish
between imagination and intellection, we think that the things we more easily
imagine are clearer to us, and think we understand what we imagine. Hence,
what should be put later we put first, [30] and so the true order of making
progress is overturned, and no conclusion is arrived at legitimately.

[91][e](part0013.html#ch1fn101) To arrive finally at the second part of this
Method, I shall set [II/34] forth first our aim in this Method, and then the
means to attain it. The aim, then, is to have clear and distinct ideas, i.e.,
such as have been made from the pure mind, and not from fortuitous motions of
the body. And then, so that all ideas may be led back to one, we shall [5]
strive to connect and order them so that our mind, as far as possible,
reproduces objectively the formal character of nature, both as to the whole
and as to the parts.

[92] As for the first, our ultimate end requires (as we have already said)
that the thing be conceived either through its essence alone or [10] through
its proximate cause. If the thing is in itself, _or_ , as is commonly said, is
the cause of itself, then it must be understood through its essence alone; but
if it is not in itself, but requires a cause to exist, then it must be
understood through its proximate cause. For really,
knowledge[f](part0013.html#ch1fn102) of the effect is nothing but acquiring a
more perfect knowledge of its cause.

[15] [93] Therefore, so long as we are dealing with the Investigation of
things, we must never infer anything from abstractions, and we shall take very
great care not to mix up the things that are only in the intellect with those
that are real. But the best conclusion will have to be drawn from some
particular affirmative essence, _or_ , from a true and [20] legitimate
definition. For from universal axioms alone the intellect cannot descend to
singulars, since axioms extend to infinity, and do not determine the intellect
to the contemplation of one singular thing rather than another.

[94] So the right way of discovery is to form thoughts from some given
definition. This will proceed the more successfully and easily, [25] the
better we have defined a thing. So the chief point of this second part of the
Method is concerned solely with this: knowing the conditions of a good
definition, and then, the way of finding good definitions. First, therefore, I
shall deal with the conditions of definition.

[95] To be called perfect, a definition will have to explain the inmost [30]
essence of the thing, and to take care not to use certain _propria_ in its
place. So as not to seem bent on uncovering the errors of others, I shall use
only the example of an abstract thing to explain this. For it [II/35] is the
same however it is defined. If a circle, for example, is defined as a figure
in which the lines drawn from the center to the circumference are equal, no
one fails to see that such a definition does not at all explain the essence of
the circle, but only a property of it. And though, as I have said, this does
not matter much concerning figures and other [5] beings of reason, it matters
a great deal concerning Physical and real beings, because the properties of
things are not understood so long as their essences are not known. If we
neglect them, we shall necessarily overturn the connection of the intellect,
which ought to reproduce the connection of Nature, and we shall completely
miss our goal.

[10] [96] These are the requirements which must be satisfied in Definition, if
we are to be free of this fault:

1\. If the thing is created, the definition, as we have said, will have to
include the proximate cause. E.g., according to this law, a circle would have
to be defined as follows: it is the figure that [15] is described by any line
of which one end is fixed and the other movable. This definition clearly
includes the proximate cause.[63](part0013.html#ch1fn103)

2\. We require a concept, _or_ definition, of the thing such that when it is
considered alone, without any others conjoined, all the thing’s properties can
be deduced from it (as may be seen in this definition [20] of the circle). For
from it we clearly infer that all the lines drawn from the center to the
circumference are equal.

That this is a necessary requirement of a definition is so plain through
itself to the attentive that it does not seem worth taking time to demonstrate
it, nor to show also, from this second requirement, that every definition must
be affirmative.

[25] I mean intellectual affirmation—it matters little whether the definition
is verbally affirmative; because of the poverty of language it will sometimes,
perhaps, [only] be able to be expressed negatively, although it is understood
affirmatively.

[97] These are the requirments for the definition of an uncreated thing:

1\. That it should exclude every cause, i.e., that the object should [30]
require nothing else except its own being for its
explanation.[64](part0013.html#ch1fn104)

2\. That, given the definition of this thing, there should remain no room for
the Question—does it exist?

3\. That (as far as the mind is concerned) it should have no substantives that
could be changed into adjectives, i.e., that it should not be explained
through any abstractions.

[35] 4\. Finally (though it is not very necessary to note this) it is required
[II/36] that all its properties be inferred[65](part0013.html#ch1fn105) from
its definition.

All these things are evident to those who attend to them accurately.

[98] I have also said that the best conclusion will have to be drawn from a
particular affirmative essence. For the more particular an idea [5] is, the
more distinct, and therefore the clearer it is. So we ought to seek knowledge
of particulars as much as possible.

[99] As for order, to unite and order all our perceptions, it is required, and
reason demands,[66](part0013.html#ch1fn106) that we ask, as soon as possible,
whether there is a certain being, and at the same time, what sort of being it
is, [10] which is the cause of all things, so that its objective essence may
also be the cause of all our ideas, and then our mind will (as we have
said)[67](part0013.html#ch1fn107) reproduce Nature as much as possible. For it
will have Nature’s essence, order, and unity objectively.

From this we can see that above all it is necessary for us always to [15]
deduce all our ideas from Physical things, _or_ from the real beings,
proceeding, as far as possible, according to the series of causes, from one
real being to another real being, in such a way that we do not pass over to
abstractions and universals, neither inferring something real from them, nor
inferring them from something real. For to do [20] either interferes with the
true progress of the intellect.

[100] But note that by the series of causes and of real beings I do not here
understand the series of singular, changeable things, but only the series of
fixed and eternal things. For it would be impossible for human weakness to
grasp the series of singular, changeable things, not [25] only because there
are innumerably many of them, but also because of the infinite circumstances
in one and the same thing, any of which can be the cause of its existence or
nonexistence. For their existence has no connection with their essence, _or_
(as we have already said) is not an eternal truth.

[30] [101] But there is also no need for us to understand their series. The
essences of singular, changeable things are not to be drawn from their series,
_or_ order of existing, since it offers us nothing but extrinsic
denominations, relations, or at most, circumstances, all of which are [35] far
from the inmost essence of things. That essence is to be sought [II/37] only
from the fixed and eternal things, and at the same time from the laws
inscribed in these things, as in their true codes, according to which all
singular things come to be, and are ordered. Indeed these singular, changeable
things depend so intimately, and (so to speak) essentially, on the fixed
things that they can neither be nor be conceived [5] without them. So although
these fixed and eternal things are singular, nevertheless, because of their
presence everywhere, and most extensive power, they will be to us like
universals, _or_ genera of the definitions of singular, changeable things, and
the proximate causes of all things.

[10] [102] But since this is so, there seems to be a considerable difficulty
in our being able to arrive at knowledge of these singular things. For to
conceive them all at once is a task far beyond the powers of the human
intellect. But to understand one before the other, the order must be sought,
as we have said, not from their series of existing, nor [15] even from the
eternal things. For there, by nature, all these things are at once. So other
aids will have to be sought beyond those we use to understand the eternal
things and their laws.

Nevertheless, this is not the place to treat them, nor is it necessary until
after we have acquired a sufficient knowledge of the eternal things [20] and
their infallible laws, and the nature of our senses has become known to us.
[103] Before we equip ourselves for knowledge of singular things, there will
be time to treat those aids, all of which serve to help us know how to use our
senses and to make, according to certain laws, and in order, the experiments
that will suffice to determine [25] the thing we are seeking, so that at last
we may infer from them according to what laws of eternal things it was made,
and its inmost nature may become known to us, as I shall show in its
place.[68](part0013.html#ch1fn108)

Here, to return to our theme, I shall only try to treat those things that seem
necessary for us to be able to arrive at knowledge of eternal things, and for
us to form their definitions according to the conditions [30] laid down above.
[104] To do this, we must recall what we said
above:[69](part0013.html#ch1fn109) when the mind attends to a thought—to weigh
it, and deduce from it, in good order, the things legitimately to be deduced
from it—if it is false, the mind will uncover the falsity; but if it is true,
the mind will [35] continue successfully, without any interruption, to deduce
true things [II/38] from it. This, I say, is required for our purpose. For our
thoughts cannot be determined from any other
foundation.[70](part0013.html#ch1fn110) [105] If, therefore, we wish to
investigate the first thing of all, there must be some foundation that directs
our thoughts to it.

[5] Next, because Method is reflexive knowledge itself, this foundation, which
must direct our thoughts, can be nothing other than knowledge of what
constitutes the form of truth, and knowledge of the intellect, and its
properties and powers. For once we have acquired this [knowledge], we shall
have the foundation from which we shall deduce our [10] thoughts and the way
by which the intellect, according to its capacity, will be able to reach the
knowledge of eternal things, with due regard, of course, to its own powers.

[106] But if forming true ideas pertains to the nature of thought, as shown in
the first part, here we must investigate what we understand [15] by the powers
of the intellect. Since the chief part of our Method is to understand as well
as possible the powers of the intellect, and its nature, we are necessarily
forced, by what I have taught in this second part of the Method, to deduce
these from the very definition of thought and intellect.

[107] But so far we have had no rules for discovering definitions. [20] And
because we cannot give them unless the nature, _or_ definition, of the
intellect, and its power are known, it follows that either the definition of
the intellect must be clear through itself, or else we can understand nothing.
It is not, however, absolutely clear through itself; but because its
properties (like all the things we have from intellect) [25] cannot be
perceived clearly and distinctly unless their nature is known, if we attend to
the properties of the intellect that we understand clearly and distinctly, its
definition will become known through itself. We shall, therefore, enumerate
the properties of the intellect here, and consider them, and begin to deal
with out innate tools.[g](part0013.html#ch1fn111)

[30] [108] The properties of the intellect which I have chiefly noted, and
understand clearly, are these:

1\. That it involves certainty, i.e., that the intellect knows that things are
formally as they are contained objectively in itself.

2\. That it perceives certain things, _or_ forms certain ideas, absolutely,
[II/39] and forms certain ideas from others. For it forms the idea of quantity
absolutely, without attending to other thoughts, but it forms the ideas of
motion only by attending to the idea of quantity.

3\. Those that it forms absolutely express infinity, but determinate [5] ideas
it forms from others. For if it perceives the idea of a quantity through a
cause, then it determines [that idea] through [the idea] of a
quantity,[71](part0013.html#ch1fn112) as when it perceives that a body arises
from the motion of some plane, a plane from the motion of a line, and finally,
a line from the motion of a point. These perceptions do not help to understand
the quantity, but only to determine it. [10] This is evident from the fact
that we conceive them as arising from the motion, although the motion is not
perceived unless the quantity is perceived, and also because we can continue
the motion to form a line to infinity, which we could not do at all, if we did
not have the idea of infinite quantity.

[15] 4\. It forms positive ideas before negative ones.

5\. It perceives things not so much under duration as under a certain species
of eternity, and in an infinite number—or rather, to perceive things, it
attends neither to number nor to duration; but when it imagines things, it
perceives them under a certain [20] number, determinate duration and quantity.

6\. The clear and distinct ideas that we form seem to follow so from the
necessity of our nature alone that they seem to depend absolutely on our power
alone. But with confused ideas it is quite the contrary—they are often formed
against our will.

[25] 7\. The mind can determine in many ways the ideas of things that the
intellect forms from others—as, for example, to determine the plane of an
ellipse, it feigns that a pen attached to a cord is moved around two centers,
or conceives infinitely many points always having the same definite relation
to some given straight line, or a [30] cone cut by some oblique plane, so that
the angle of inclination is greater than the angle of the cone’s vertex, or in
infinite other ways.

8\. The more ideas express of the perfection of some object, the more perfect
they are. For we do not admire the architect who has designed a chapel so much
as one who has designed a notable [35] temple.

[II/40] [109] I shall not linger over the other things that are referred to
thought, such as love, joy, etc. For they contribute nothing to our present
purpose, nor can they be conceived unless the intellect is perceived. For if
perception is altogether taken away, then all these are taken away.

[5] [110] False and fictitious ideas have nothing positive (as we have shown
abundantly) through which they are called false or fictitious, but they are
considered as such only from a defect of our knowledge. So false and
fictitious ideas, as such, can teach us nothing concerning the essence of
thought. It is rather to be sought from the positive [10] properties just
surveyed, i.e., we must now establish something common from which these
properties necessarily follow, _or_ such that when it is given, they are
necessarily given, and when it is taken away, they are taken away.

The rest is lacking.



[1](part0012.html#ch1fn-1) Spinoza describes his _opusculum_ as being devoted
to the question “how things began to be and by what connection they depend on
the first cause … and also on the emendation of the intellect.” This strongly
suggests that our TdIE was part of the _opusculum_. But Mignini has cast doubt
on this. See the annotation at IV/36/13.

[2](part0012.html#ch1fn-2) I would be inclined to say earlier than Letter 2 at
least, i.e., before September 1661, for reasons suggested in the annotation at
II/9/12. Cf. Mignini 2, 106. If, as Mignini thinks, the TdIE is earlier than
the KV, and if, as he also thinks, the first draft of the KV was written
around the middle of 1660 (see Mignini 1, 239), then the TdIE would have been
written a good deal earlier than the spring of 1662.

[3](part0012.html#ch1fn-3) Notably II/29, n. z. On the other hand, some of the
things promised in the forward references do not appear in our version of the
KV any more than they do in E, e.g., the extended discussion of wealth
foreshadowed in II/6, n. a.

[4](part0012.html#ch1fn-4) Mignini contends that the teaching of the KV is
closer to that of E than is the teaching of the TdIE in regard to the
following topics: the nature of the intellect and the doctrine of method, the
theory of the kinds of knowledge, the nature of fictions, the will, final
causation and perfection. This is not the place for a discussion of his
arguments, but I will observe that my own attempt to study the development of
Spinoza’s thought about truth (Curley 9), an attempt made before I was aware
of Mignini’s work, would have proceeded more smoothly had I adopted his
chronology.

[5](part0012.html#ch1fn-5) This, essentially, is the judgment of M. Matheron,
in a recent review of Mignini’s work (_Bulletin de l’Association des Amis de
Spinoza_ , no. 10, 1983): “Si les arguments positifs avancés par Mignini, bien
qu’ils donnent beaucoup à penser, ne sont _peut-être_ tout à fait convaincants
(personellement j’avoue hésiter encore sur ce point), ses arguments négatifs,
en revanche, sont décisifs: nous admettions tous comme allant de soi, parce
qu’on nous l’avait enseigné, que le C.T.[i.e., KV] était antérieur au TRE
[i.e., TdIE], et Mignini _démontre_ qu’il n’y avait à cela _absolument aucune
raison_!”

[6](part0012.html#ch1fn-6) See Joachim 2, 59, and cf. Mignini 2, 140. Joachim
construes this as a survival of Cartesian doctrines advocated in the KV.
Mignini, it seems, regards it as evidence of the priority of the TdIE to the
KV. I myself am not satisfied with the evidence that Spinoza adopts the
Cartesian distinction between will and intellect either in the TdIE or in the
KV. For example, it seems to me that § 78 of the TdIE effectively anticipates
Spinoza’s critique of the Cartesian doctrine of suspense of judgment in E
IIP49S. And I take it that KV II, xiv, also criticizes the Cartesian
distinction, though on different grounds.

[7](part0012.html#ch1fn-7) See the annotation at II/9/12.

[8](part0012.html#ch1fn-8) See Curley 2; cf. Joachim 2, 24-33.

[9](part0012.html#ch1fn-9) Cf. Joachim 2, 89-90.

[10](part0012.html#ch1fn-10) So Joachim argues at any rate. Cf. Joachim 2,
102-111.

[1](part0012.html#ch1fn-11) By the editors of the _Opera posthuma_.

[2](part0012.html#ch1fn-12) The translation of this title is disputed. The
Latin for the main title is _Tractatus de Intellectus Emendatione_ , the Dutch
_Handeling van de Verbetering van’t Verstant_. Joachim (2, 1) argued that no
English term could reproduce the _exact_ implications of the Latin, but
recommended “Purification of the Intellect” as rightly suggesting a project of
restoring the intellect to its “natural perfection, by eliminating from it …
ideas which are not _its own_ but have come to it from an external source.”
DeDeugd’s criticism of Joachim (1, 50-57), while rightly pointing out that the
Dutch version cannot plausibly bear that meaning, gives insufficient weight to
§ 16. Eisenberg (3) argues that no term can reproduce the exact implications
of the Latin, since Spinoza’s phrase has no _exact_ implications. At the time
of writing this work Spinoza inconsistently conceived of the intellect both as
inherently pure and as needing purification. He did not clearly distinguish
between the mind, which cannot be entirely freed of external influences, and
the intellect, which has no need to be. No translation will solve such
difficulties.

The subtitle in the NS reads: “and at the same time of the means of making it
perfect.”

[a](part0012.html#ch1fn-13) I could explain this more fully and distinctly, by
distinguishing wealth that is sought for its own sake, or for the sake of
honor, or for the sake of sensual pleasure or for the sake of health and the
advancement of the arts and sciences. But I reserve this for its own place;
such an exact investigation is not appropriate here.

[3](part0012.html#ch1fn-14) The choice of this particular trinity is probably
influenced by Aristotle. Cf. the _Nicomachean Ethics_ I, 4, and the _Short
Treatise_ II, v, 6.

[4](part0012.html#ch1fn-15) “ _Modò possem penitùs deliberare_.” _Deliberare_
can mean ‘ _to deliberate_ ’ and most translators have given us something like
“If only I could reflect thoroughly [on the matter].” But _deliberare_ can
also mean ‘to decide as a consequence of deliberation’ and I follow Koyré in
thinking that to be the meaning here. When Spinoza comments on this phrase in
§ 10 it seems clear that he thinks of his difficulty as more volitional than
intellectual. Cf. E IVP14.

[b](part0012.html#ch1fn-16) These things are to be demonstrated more
accurately.

[5](part0012.html#ch1fn-17) The NS has: “often cause the destruction of those
who possess them (if one may speak thus), and always of those who are
possessed by wealth.” It seems likely that the parenthesis is an addition by
the translator and bears on the notion of being possessed by wealth.

[6](part0012.html#ch1fn-18) OP: “Sed amor erga rem aeternam, & infinitam solâ
laetitiâ pascit animum, ipsaque omnis tristitiae est expers”; NS: “Maar de
liefde tot d’eeuwige en oneindige zaak voed de geest [margin: mens] met
blÿschap alleen, en is van alle droefheit uitgesloten.” The translation of
this important passage is disputed. Joachim (2, 18, n.4) notes that various
translators have rendered it as if it were the love that was exempt from
sadness (which makes the Latin ungrammatical, but is what the Dutch implies).
He, however, sees here a foreshadowing of the doctrine that God is exempt from
sadness. (I.e., _ipsa_ refers not to _amor_ , but the eternal and infinite
thing.) This is possible, both grammatically and philosophically, but Joachim
surely goes too far when he contends that this interpretation is necessary to
explain why love for God feeds the mind with unmixed joy. Appuhn, Koyré, and
Caillois all take _ipsa_ to refer to _laetitia_ , an alternative Joachim does
not discuss, and to my mind the one most likely.

[7](part0012.html#ch1fn-19) “ _Modò possem seriò deliberare_.” In referring
back to II/6/21 Spinoza does not in fact quote himself exactly.

[8](part0012.html#ch1fn-20) Wendel and Cassirer thought it necessary to emend
this passage so that it would read: “man conceives a nature much stronger than
his own human nature.” But I find Gebhardt’s arguments against this conclusive
(II/322-323). The text as it stands is supported by the NS and paralleled by
passages both in the _Short Treatise_ (II,4; I/60/21ff.) and the _Ethics_ (IV,
Pref., II/208). Koyré (2, 98-99) is right to remark that the passage is a
difficult one on any reading, but his comments do not seem to me to stress
sufficiently the necessity both of man’s conceiving such a stronger nature and
of his striving to attain it.

[c](part0012.html#ch1fn-21) These things will be explained more fully in their
place.

[d](part0012.html#ch1fn-22) Note that here I take the trouble only to
enumerate the sciences necessary for our purpose, without attending to their
order.

[e](part0012.html#ch1fn-23) In the sciences there is only one end, toward
which they must all be directed.

[9](part0012.html#ch1fn-24) If this is taken, as it may be, to mean “knowledge
that man is a part of nature, and subject to its universal laws,” then the
doctrine is very Stoic. Cf. Marcus Aurelius, _Meditations_ , VII, 9-13; X,6.
But the passage is also one which, more than any other perhaps, encourages the
interpretation of Spinoza as a mystic.

[10](part0012.html#ch1fn-25) That the intellect requires purification
(_expurgatio_) is a Baconian doctrine. Cf. the _Novum Organum_ (Bacon, I, 139
= IV, 27). For healing (_medendi_) the NS has simply “improving” (verbeteren).
Eisenberg (3, 175) argues that passages like this one are symptomatic of a
tendency to confuse the intellect with the mind “at least during much of the
time that he wrote the treatise.” And since, in Letter 2 (IV/8-9), Spinoza is
quite critical of Bacon for not distinguishing the intellect from the mind,
and for supposing that the intellect is deceived by its own nature, it seems
likely that, by the time of writing that letter (September 1661), Spinoza
would have regarded passages like this as unsatisfactory. Note that in that
letter Spinoza criticizes Bacon for comparing the intellect to an uneven
mirror (cf. Bacon, I, 164). A similar comparison occurs in the purification of
the intellect passage cited above, except that there it is the mind that is
compared to an uneven mirror. See also Mignini 2, 106.

[11](part0012.html#ch1fn-26) Latin: “ _intellectum … redigamus_.” NS: “ _het
verstant … te brengen_.” But the language of purification in the preceding
paragraph seems to justify the suggestion of returning to an original state of
rectitude.

[12](part0012.html#ch1fn-27) NS: “ _zuiveren_ ,” purify.

[13](part0012.html#ch1fn-28) NS: “ _three_ ”; but it goes on to enumerate four
kinds, as the OP does. Gebhardt thought this might naturally be explained on
the assumption that in an earlier draft of the _Treatise_ Spinoza had divided
the kinds of ‘knowledge’ into three (as in the _Short Treatise_ and the
_Ethics_) rather than four. He also took it as evidence that the Dutch
translation was made, not from the text of the _Opera posthuma_ , but from an
independent, earlier manuscript, in which revisions were not consistently
carried out. For counter-argument see Mignini 2, 126-127.

[14](part0012.html#ch1fn-29) On the translation here, and on the
classification generally, see Joachim 2, 24-33, and Curley 2, 25-59.

[15](part0012.html#ch1fn-30) As Joachim notes, this passage echoes one in
Bacon, _Novum Organum_ I, 100 (Bacon, I,203 [= IV, 95]). He also calls
attention to aphorisms 25, 70, and 105. Perhaps Bacon’s influence is also to
be seen in Descartes’ _Regulae_ , AT X, 427.

[f](part0012.html#ch1fn-31) When this happens, we understand nothing about the
cause except what we consider in the effect. This is sufficiently evident from
the fact that then the cause is explained only in very general terms, e.g.,
_Therefore there is something, Therefore there is some power, etc_. Or also
from the fact that the terms express the cause negatively, _Therefore it is
not this, or that, etc_. In the second case something clearly conceived is
attributed to the cause on account of the effect, as we shall show in an
example; but nothing is attributed to it except _propria_ , not the essence of
a particular thing.[16](part0013.html#ch1fn32)

[16](part0013.html#ch1fn-32) OP: “In secundo casu aliquid causae tribuitur
propter effectum, quod clarè conciptur, ut in exemplo ostendimus; verùm nihil
praeter propria, non verò rei essentia particularis.” This note has more than
its share of difficulties. (1) What does _in secundo casu_ refer to? Eisenberg
suggests that it _could_ be translated “in a (more) favorable case,” adding a
third case to the two already mentioned in the note, but neither he nor I
thinks it very likely. Or it could be translated as I have it and refer to the
case described in the immediately preceding sentence. But this does not make
much sense of the note. Or it could refer to the second case mentioned in the
text, in spite of the fact that the note as a whole is attached to the first
disjunct. I opt for the third alternative. (2) What is the antecedent of _quod
clare concipitur?_ Eisenberg thinks it is obviously _effectus_ , in spite of
the gender difficulties. I follow Joachim in taking it to be _aliquid_. (3)
What does _particularis_ modify? Most translators have favored _essentia_. I
follow the NS (along with Joachim and Eisenberg) in making it modify _rei_ ,
though grammar is neutral on the question. See also the note on _proprium_ in
the English-Latin-Dutch section of the Glossary-Index.

[17](part0012.html#ch1fn-33) OP: “vel cùm concluditur ab aliquo universali,
quod semper aliqua proprietas concomitatur”; the NS in effect supplies _causa_
as the subject of _concluditur_ : “when one infers the cause from some
universal which is always accompanied by some property.” Elwes takes the
_quod_ clause as subject: “when it is inferred from some general proposition
that some property is always present.” Koyré has: “when one draws a conclusion
from the fact that a universal is always accompanied by a certain property.”
Interpreting Spinoza’s note f as I do, I would say that the something which is
inferred is a clearly conceived property of a cause, though this is
inconsistent with the general description of this kind of knowledge at
II/10/16. I am not much moved by the latter consideration, since the second
example given in § 21 is also inconsistent with the general description. See
the discussions in Joachim 2, 30-32, and Curley 2, 40-49.

[g](part0012.html#ch1fn-37) We see clearly from this example what I have just
noted. For we understand nothing through that union except the sensation
itself, that is, the effect,[19](part0013.html#ch1fn40a) from which we
inferred the cause, concerning which we understand nothing.

[h](part0012.html#ch1fn-38) Although such a conclusion is certain, it is still
not sufficiently safe, unless we take the greatest care. For those who do not
take such care will immediately fall into errors. When things are conceived so
abstractly, and not through their true essence, they are immediately confused
by the imagination. What in itself is one, men imagine to be many. For to the
things they conceive abstractly, separately, and confusedly, they give names
which they use to signify other more familiar things. Hence they imagine these
things in the same way as they are accustomed to imagine the things to which
the names were first given.

[18](part0012.html#ch1fn-36) I follow Appuhn, Koyré et al., in supplying “one
thing” here; parallelism with II/10/16 would require the “essence of a thing,”
but the strict accuracy of that description is put in some doubt both by the
second example Spinoza gives and by his note to II/10/17.

[19](part0013.html#ch1fn-40a) OP: _effectus_ , which is ungrammatical, given
seventeenth-century conventions about the use of accents. Gebhardt emends to:
_effectûs_ , “of the effect.” But most translators have preferred to emend to
_effectum_ , which is supported by the NS, and which I take to be correct.

[20](part0012.html#ch1fn-39) Cf. § 78.

[21](part0012.html#ch1fn-40) OP: “ _quales_ ,” ‘what kind of;’ but NS:
_welke_. Cf. Joachim 2, 31, n. 2.

[22](part0012.html#ch1fn-41) Here I adopt Joachim’s emendation of the
numbering and punctuation. Joachim 2, 34, n 2.

[23](part0012.html#ch1fn-42) OP: “ _singularis existentia alicujus rei_.” As
at II/10/34, this is ambiguous. Here the NS take _singularis_ to modify
_existentia_ , but wrongly, I think.

[i](part0012.html#ch1fn-43) Here I shall discuss experience somewhat more
fully, and examine the Method of proceeding of the Empiricists and of the new
Philosophers [NS: … the Empiricists, who want to do everything through
experience …].

[24](part0012.html#ch1fn-44) OP: “ _illius_ ,” NS: “ _enige_.” Perhaps we
should read: _ullius_ , ‘any’.

[25](part0012.html#ch1fn-45) The comparison which follows may have been
suggested by any of various passages in Bacon [e.g., I, 126 (= IV, 14); I, 152
(= IV, 40); I, 157 (= IV, 47)]. But as Joachim notes (2, 53), Spinoza makes a
rather different use of the comparison. Similar remarks apply to a passage in
Descartes’ _Regulae_ (AT X, 397). Neither Bacon nor Descartes uses the analogy
to counter a threatened regress.

[k](part0012.html#ch1fn-46) By inborn power I understand what is not caused in
us by external causes. I shall explain this afterwards in my Philosophy.

[l](part0012.html#ch1fn-47) Here they are called works. In my Philosophy, I
shall explain what they are.

[m](part0012.html#ch1fn-50) Note that here we shall take care to show not only
what we have just said, but also that we have so far proceeded rightly, and at
the same time other things that it is quite necessary to know.

[26](part0012.html#ch1fn-48) Spinoza does seem to mean that these inborn tools
are needed only provisionally, until better ones can be made with them, though
as Joachim remarks (2, 54, n. 1) this is obscure. Other translators (e.g.,
Appuhn, Koyré) take Spinoza to mean that these inborn tools are all the
intellect requires to make more advanced ones.

[27](part0012.html#ch1fn-49) NS: “The true idea.” But I take it that this must
be a generalizing use of the definite article, since no basis has been laid
for reference to any particular true idea (or for any assumption that,
ultimately, there is only one true idea).

[28](part0012.html#ch1fn-51) Joachim (2, 54, n. 2, 80, n. 1) contends that by
a “true idea of Peter” Spinoza here means the true idea which someone else may
have of Peter. The example Spinoza gives at the end of this paragraph seems to
confirm this.

[n](part0012.html#ch1fn-52) Note that here we are not asking how the first
objective essence is inborn in us. For that pertains to the investigation of
nature, where we explain these things more fully, and at the same time show
that apart from the idea there is neither affirmation, nor negation, nor any
will.

[o](part0012.html#ch1fn-54) In my Philosophy, I shall explain what seeking is
in the soul.

[29](part0012.html#ch1fn-53) OP: “ _modus, quo sentimus essentiam formalem_.”
It is unclear whether _modus_ should be taken as a technical term here.

[30](part0012.html#ch1fn-55) Perhaps, as Joachim suggests (2, 162, n. 4), we
should read _et_ for _aut_ here: “Reasoning and intellection.”

[31](part0012.html#ch1fn-56) OP: “ _datae verae ideae_ ”; NS: “ ’ _t gestelde
ware denkbeelt_.” Koyré argues that the term _datae_ in this kind of
expression is best suppressed, since it does not imply what it is likely to
suggest, viz. that the true idea is given to us. All that is implied is that
there is a true idea. Gueroult (1, 1:30, n. 42) argues against this that the
qualification implies that the true idea is an actual eternal essence in the
infinite or finite intellect, and hence produced by God, not by the intellect.
Man finds the Idea “en lui sans lui.” Although uncertain of the correctness of
Gueroult’s interpretation, I find it impossible to follow Koyré’s policy,
which seems to lead to serious difficulty in contexts like § 43.

[p](part0012.html#ch1fn-57) To interact with other things is to produce, or be
produced by, other things.

[32](part0012.html#ch1fn-58) The NS version of this sentence runs: “If there
were something in nature that did not interact with other things, then its
objective essence, which would have to agree completely with the formal
essence, would also not interact with other ideas, i.e., we would not be able
to understand or infer anything about it.” I have translated the Latin (as
emended by Gebhardt to correct a grammatical mistake); Gebhardt thinks it
obvious that the conditionalization of the reference to the objective essence
is a change made by Spinoza after the Dutch translation was done. But I share
Joachim’s feeling (2, 100, n. 2) that the Dutch makes better sense. Gebhardt
also adds a phrase in l. 31 from the Dutch, so that the conclusion of the
sentence might be translated: “we could neither understand nor infer.…” But it
is very unlikely that this indicates an earlier and fuller version of the
text. Probably it represents nothing more than the use of two Dutch verbs to
render one Latin one.

[33](part0012.html#ch1fn-59) OP: “ _ut mens nostra omninò referat Naturae
exemplar_.” It is difficult to be confident about the translation of this
clause. Joachim (2, 100) offers: “that our mind may reflect ideally in all
respects its real Original—i.e., may reflect the formal essence of Nature in
its totality and in all its parts,” drawing on § 91 for the gloss. As Joachim
points out later (215, n. 1) this passage is prima facie incompatible with his
interpretation of Spinoza’s conception of truth.

[q](part0012.html#ch1fn-60) As we also do not here doubt the truth we possess.

[34](part0012.html#ch1fn-61) I believe § 104 provides a helpful gloss on this
passage.

[35](part0012.html#ch1fn-62) There is no negation in either the OP or the NS,
but most editors have felt the need to supply one. If one is supplied, then it
seems we must also assume a gap in the text after “I reply to him.” Koyré
understands the text in this fashion, and conjectures that Spinoza eventually
came to regard the objection as well-founded, so that he concentrated on the
_Ethics_ and put the _Treatise_ to one side (cf. his note to this passage, and
the _Avant-propos_).

Gebhardt at one stage thought likewise, but by the time he produced his
edition of the _Works_ had come to the conclusion that the text must be
defended, not emended (II/326-327). He takes Spinoza to be replying not to an
objection to his procedure here, but to an objection to his procedure in his
projected _Philosophy_. Eisenberg (1, 45-49, n. 82) joins Gebhardt in
defending the text.

I prefer Koyré’s reading. I cannot deal fully here with the arguments offered
by Gebhardt and Eisenberg, but I will make the following observations: (1) the
text of the OP is supported by the NS, but if the conjectured omissions were
in Spinoza’s ms., this confirmation does not amount to much; quite possibly
the ms. contained a passage which Spinoza struck out and never replaced; (2) I
do not see why the emendation would make § 46 a mere duplication of
II/17/8-34; (3) if Spinoza were switching suddenly from a defense of his
procedure in the _TdIE_ to a defense of his procedure in his _Philosophy_ , I
would expect a more explicit indication of it; (4) Eisenberg construes
_ostenderim_ in II/18/2 as a future perfect (indicative): “If anyone should
seek [perhaps] to know why I shall have shown the truths of Nature in that
order at once, before everything.…” But both morphology and syntax require us
to construe it as present perfect subjunctive. And the concluding line of the
paragraph (in which Eisenberg construes _praemiserim_ as present perfect
subjunctive) makes it clear that Spinoza intends to defend what he has already
done.

[r](part0012.html#ch1fn-65) See further what we shall note concerning
hypotheses that we clearly understand; but the fiction consists in our saying
that such as these exist in the heavenly bodies.

[36](part0012.html#ch1fn-63) OP: “ _somnum_ ,” but NS: “ _dromen_.” So
probably we should read: _somnium_.

[37](part0012.html#ch1fn-64) NS: “ _eerste/prima_.” So perhaps Spinoza
originally wrote: “first cause.”

[38](part0012.html#ch1fn-66) Gebhardt adds the phrase “in existing” from the
NS, but I agree with Joachim (2, 116, n. 2) that this is at least unnecessary,
if not wrong. Similarly Gebhardt’s addition at II/19/1 seems wrong given that
Spinoza goes on (both in the OP and in the NS) to enumerate a fourth task of
the method. His text would be translated: “Third [NS: and finally]”.…

[s](part0012.html#ch1fn-69) Because the thing makes itself evident, provided
it is understood, we require only an example, without other proof. The same is
true of its contradictory—it need only be examined for its falsity to be
clear. This will be plain immediately, when we speak of fictions concerning
essence.

[t](part0012.html#ch1fn-70) Note. Although many say that they doubt whether
God exists, nevertheless they have nothing but the name, or they feign
something which they call God; this does not agree with the nature of God, as
I shall show later in the proper place.

[u](part0012.html#ch1fn-71) By an eternal truth I mean one, which, if it is
affirmative, will never be able to be negative. Thus it is a first and eternal
truth _that God is_ ; but _that Adam thinks_ is not an eternal truth. _That
there is no Chimera_ is an eternal truth; but not _that Adam does not think_.

[39](part0012.html#ch1fn-67) Joachim (ibid.) suggests reading _essentia_ ,
though the OP’s _existentia_ is supported by the NS. If it were not for the
immediately following phrase (_ipsâ suâ naturâ_), I would think this almost
certainly correct. I have translated the Latin as it stands, but (with
Eisenberg) I feel certain that what Spinoza _means_ is that the essence of the
thing by itself does not entail either that the thing cannot, or that it must,
exist.

[40](part0012.html#ch1fn-68) The text of the OP would be translated: “From
this it follows that, if there is a God, or something omniscient, we (_nos_)
can feign nothing at all.” Since this makes very little sense, earlier editors
and translators often supplied a phrase to fill it out: “we can feign nothing
at all about it.” Gebhardt’s text, which I have translated, reads _eum_ for
_nos_ , following the NS. Slightly preferable, perhaps, would be van Vloten
and Land’s _hoc_ (= this being) for _nos_. Textual emendation is a dangerous
game, but if anything in this area is certain, we can be sure that the text of
the OP is corrupt. For a full discussion see Gebhardt (II/328-330) or
Eisenberg 2, 56-60. Eisenberg gives a clear explanation of the thought: since
hypotheses concern only the possible (i.e., things whose existence or
nonexistence depends on causes unknown to us), a being to whom nothing was
unknown would not be able to regard anything as merely possible, hence would
not be able to form hypotheses about anything.

[41](part0012.html#ch1fn-72) The clause “when (_ubi_) we do not attend to the
order of Nature” is puzzling enough to have prompted attempts at emendation.
Gebhardt is probably right to reject Elbogen’s suggestion that it has simply
been misplaced, but might have considered more seriously Stern’s suggestion
that we should read _etsi_ for _ubi_ : “ _even if_ we do not attend …” It
would not take a great deal of carelessness in the writing or the reading for
a handwritten _etsi_ to be taken for an _ubi_ and _etsi_ would not require a
subjunctive (_pace_ Gebhardt). Koyré (2, 106) has a plausible gloss: for
Spinoza there are as many modes and degrees of existence as there are modes
and degrees of essence; the existence of a man is different from that of an
animal or an inanimate object; even when we do not attend to the order of
nature (which is a necessary, but not sufficient condition of all feigning),
we cannot attribute to a man an animal’s mode of existence unless we think in
general terms.

[x](part0012.html#ch1fn-75) Afterwards, when we speak of fiction that concerns
essences, it will be clear that the fiction never makes, or presents to the
mind, anything new, but that only things which are in the brain or the
imagination are recalled to memory, and that the mind attends confusedly to
all of them at once. Speech and a tree, for example, are recalled to memory,
and since the mind attends confusedly, without distinction, it allows that the
tree speaks. The same is understood concerning existence, especially, as we
have said, when it is conceived so generally, as being. Then it is easily
applied to all things which occur in the mind together. This is very much
worth noting.

[y](part0012.html#ch1fn-76) The same must also be understood concerning the
hypotheses that are made to explain certain motions, which agree with the
phenomena of the heavens; except that when people apply them to the celestial
motions, they infer the nature of the heavens from them. But that nature can
be different, especially since many other causes can be conceived to explain
such motions.

[42](part0012.html#ch1fn-73) Koyré suggests glossing “done something” by
“uttered some words.”

[43](part0012.html#ch1fn-74) Joachim (2, 120 n.) suggests that Spinoza has in
mind Descartes’ _Principles_ IV, 95-101, though it is not clear that Descartes
is there involved in either of the suppositions Spinoza here discusses.

[44](part0012.html#ch1fn-77) I have translated the text of the OP (“ _verae ac
merae assertiones_ ”) as it stands, but in spite of the support of the NS and
Joachim’s defense (2, 121, n. 2), I question whether _verae_ (‘true’) is
correct. Appuhn has: “assertions pure and simple,” which seems more in keeping
with parallel passages (II/21/20-21, 21/27-28, 22/20-21).

[z](part0012.html#ch1fn-78) It often happens that a man recalls this term
_soul_ to his memory, and at the same time forms some corporeal image. But
since these two things are represented together, he easily allows that he
imagines and feigns a corporeal soul: because he does not distinguish the name
from the thing itself. Here I ask my readers not to hasten to refute this,
which, as I hope, they will not do, provided that they attend as accurately as
possible to the examples, and at the same time, to the things that follow.

[45](part0012.html#ch1fn-79) Elbogen points out that most of Spinoza’s
examples come from Ovid’s _Metamorphoses_. But note that there seem to be
references also to the Judaeo-Christian doctrine of creation and the Christian
doctrine of the incarnation. Cf. Parkinson, 101-102, and E IP8S2, II/49/35.

[46](part0012.html#ch1fn-80) Koyré sees an allusion both to theologians who
hold a voluntarist theory of belief and to Hobbes’ _De Corpore_ I, iii, 8.

[47](part0012.html#ch1fn-81) Wolfson (1, 2:110-111) thought that this passage
was undoubtedly directed against Descartes, citing _The Passions of the Soul_
III, 152. He might, with equal justice, have cited the Fourth Meditation’s
claim that it is principally our free will that justifies our thinking of
ourselves as made in God’s image (AT VII, 57). De Deugd (90-91) countered that
Descartes nevertheless does not ascribe to man a power to create ideas _ex
nihilo_ (which is what is in question here in § 60). Still, I do not think
that would be a terribly implausible reading of certain passages in the Third
Meditation (AT VII, 43-44). Descartes may be the target.

[a](part0012.html#ch1fn-82) Although I seem to infer this from experience, and
someone may say that this is nothing, because a demonstration is lacking, he
may have one, if he wishes; since there can be nothing in nature that is
contrary to its laws, but since all things happen according to certain laws of
nature, so that they produce their certain effects, by certain laws, in an
unbreakable connection, it follows from this that when the soul conceives a
thing truly, it proceeds to form the same effects objectively. See below,
where I speak of the false idea. [In the OP this note is attached to the last
sentence in § 60. Gebhardt places it here, following the NS. De Deugd has
defended the placement of the OP (88, n. 1). But Eisenberg (2, 69) argues
persuasively that the note is intended, not to disprove the view discussed in
§ 60, but to support the view presented in § 61.]

[b](part0012.html#ch1fn-83) Note that the fiction, considered in itself, does
not differ much from the dream, except that the causes which appear to the
waking by the aid of the senses, and from which they infer that those
presentations are not presented at that time by things placed outside them, do
not appear in dreams. But error, as will be evident immediately, is dreaming
while awake. And if it is very obvious, it is called madness.

[48](part0012.html#ch1fn-84) This sentence occurs only in the OP, which may
indicate either an oversight on the part of the translator (as Leopold
thought) or a later addition (as Gebhardt thought). This paragraph and the
following are very strongly reminiscent of Descartes’ teaching in the
_Regulae_ , Rules 10 and 12, AT X, 399, 418, and 420. But even here there is
nothing Spinoza could have derived only from Descartes. As Koyré points out, a
similar doctrine is taught by St. Thomas, _Summa theologiae_ , Ia. 17, 3.

[49](part0012.html#ch1fn-85) OP: “ _primam_ ” NS: “ _het eerste denkbeelt_ ”
(= _ideam_). But parallelism with 1. 12 requires: _fictionem_.

[50](part0012.html#ch1fn-86) OP: “ _sed quòd necessitas_.” Joachim (2, 153, n.
2) suggests emending by deleting _sed_. That still leaves a somewhat awkward
construction. What Spinoza _means_ , I think, is that the second clause is a
consequence of the first, not a separate condition.

[51](part0012.html#ch1fn-87) As Joachim notes (2, 91-98), there are two
passages in Descartes that Spinoza may have in mind here, one in the Fifth
Meditation and one in the Second Replies (AT VII, 64, 103-104). Spinoza’s
examples are awkward for those interpreters who emphasize other passages in
which Spinoza apparently adopts a correspondence theory of truth (e.g.,
myself, in Curley 3, 52-56, 122-126, 134-137, 142). But the examples are
awkward in any case, since apparently incompatible with the general
proposition they are supposed to illustrate, which is not so awkward. For
further discussion see Curley 9.

[52](part0012.html#ch1fn-88) Koyré is probably right to see an allusion to
Hobbes here. Cf. _De Corpore_ I, i, 8.

[53](part0012.html#ch1fn-89) OP: “ _cogitationis_ ”, NS: “ _kennis/cognitio_.”
Gebhardt thinks the OP represents Spinoza’s correction of a mistake he made in
the ms. from which the NS translation was done.

[54](part0012.html#ch1fn-90) OP: “ _uti primâ fronte videtur_.” Most
translators (including the NS) have taken this to be presented as no more than
a plausible hypothesis. But Joachim suggests (2, 91) that it is presented as a
self-evident principle: “as is apparent at first glance.” Cf. § 106.

[55](part0012.html#ch1fn-91) Joachim (2, 159, n. 1) suggests following the NS,
which reads: “… that was such a most subtle body.…”

[56](part0012.html#ch1fn-92) Gueroult (1, 1:169 n.) identifies the “first
elements of the whole of Nature,” which constitute the source and origin of
Nature, with the attributes that constitute God or substance. I agree (Curley
3, 42) and infer that God is not to be identified with the whole of Nature,
but only with _Natura naturans_.

[z](part0012.html#ch1fn-94) These are not attributes of God that show his
essence, as I shall show in [my] Philosophy. [Since this topic is one taken up
in the _Short Treatise_ (KV I, ii-vii), but not in the _Ethics_ , this note is
evidence that the work referred to in the TdIE as “my Philosophy” was more
like the _Short Treatise_ than the _Ethics_.]

[a](part0012.html#ch1fn-95) This has already been demonstrated above. For if
such a being did not exist, it could never be produced; and therefore the mind
would be able to understand more things than Nature could bring about—which we
have shown above to be false.

[57](part0012.html#ch1fn-93) Koyré refers us here to E IIP38 and Hobbes, _De
Corpore_ I, vi, 4-13.

[58](part0012.html#ch1fn-96) In the OP this sentence is printed as a footnote
annexed to the Latin phrase here represented by “But in thinking.…” Gebhardt
(following a suggestion of Leopold’s) adopts the reading of the NS, which
brings it into the text. Joachim (2, 182 n.) thinks this a mistake.

[59](part0012.html#ch1fn-97) OP: “ _quomodò quaestiones sint determinandae_.”
I adopt Joachim’s paraphrase (2, 183).

[d](part0012.html#ch1fn-99) But if the duration is indeterminate, the memory
of the thing is imperfect, as each of us also seems to have learned from
nature. For often, to believe someone better in what he says, we ask when and
where it happened. Although the ideas themselves also have their own duration
in the mind, nevertheless, since we have become accustomed to determine
duration with the aid of some measure of motion, which is also done with the
aid of the imagination, we still observe no memory that belongs to the pure
mind.[61](part0013.html#ch1fn102a)

[60](part0012.html#ch1fn-98) OP: “ _Fabulam amatoriam_ ,” NS: “ _tooneelspel
van liefde_.” Literally, love story or romantic play. But the marginal note in
the NS suggests that Spinoza may originally have written _Comoedia_. The
change (if there was one) was presumably made only for stylistic reasons and
was not made consistently (cf. 1. 29).

[61](part0013.html#ch1fn-102a) OP: “ _sit purae mentis_ ” NS: “ _gantschelijk
tot de ziel behoort_ ” (= belongs entirely to the mind).

[62](part0012.html#ch1fn-100) The NS at this point gives (instead of “etc.”) a
version of the lines occurring above 12-14. But they add that the imagination
is not only _random_ , but also _unconscious_ , and that the soul is
_entirely_ acted on.

[e](part0012.html#ch1fn-101) The principal Rule of this part (as follows from
the first part) is to review all the ideas we discover in us from the pure
intellect, so that they are distinguished from those we imagine. This will
have to be elicited from the properties of each, i.e., of the imagination and
the intellection.

[f](part0012.html#ch1fn-102) Note that it is evident from this that we cannot
[NS: legitimately or properly] understand anything of Nature without at the
same time rendering our knowledge of the first cause, _or_ God, more ample.

[63](part0012.html#ch1fn-103) Cf. Hobbes, _De Corpore_ I, i, 5, and his
_Examinatio et emendatio mathematicae hodiernae_ , second dialogue. See also
Cassirer 2:98ff.

[64](part0012.html#ch1fn-104) According to Gueroult (1, 1:172-173), Spinoza
later modified this requirement and came to regard his definition of God (E
ID6) as a genetic, causal definition. It would still be true that God requires
nothing else except his own being (i.e., the elements of his being, the
attributes) for his explanation. But it would not be correct to say that a
definition in terms of those elements excludes every cause. Whereas the notion
of being _causa sui_ is here treated as if equivalent to being without a
cause, later it will be treated more positively. The key passage is in Letter
60 (IV/270-271).

[65](part0012.html#ch1fn-105) OP: “ _concludantur_ ” NS: “ _verklaart worden_
” (literally: ‘be explained’).

[66](part0012.html#ch1fn-106) Accepting Leopold’s emendation of the text. Cf.
Joachim 2, 214 n.

[67](part0012.html#ch1fn-107) Cf. §§ 42, 91, and 95.

[68](part0012.html#ch1fn-108) Various scholars (Leopold, Appuhn, Joachim) have
seen in this sentence a digression, probably added by Spinoza as a marginal
note. Gebhardt, following both the OP and the NS, retains it in the text,
rightly, I think.

[69](part0012.html#ch1fn-109) I take the reference to be to § 61, as Gebhardt
apparently does at II/337. But at II/338 he apparently takes it to be to § 70,
as part of his case for his emendation of II/38/1-2.

[70](part0012.html#ch1fn-110) OP: “Nam ex nullo fundamento cogitationes
nostrae terminari queunt.” Elwes’ translation of that text is as reasonable as
any: “For our thoughts may be brought to a close by the absence of a
foundation.” Gebhardt (following the NS) emends to: “Nam ex nullo alio
fundamento cogitationes nostrae determinari queunt,” which is what I have
translated. But Appuhn’s conjecture is also plausible: “Nam ex nullo
fundamento cogitationes nostrae determinari nequeunt” (= “for without a
foundation our thoughts cannot be determined”). For a fuller discussion see
Eisenberg 1, 103-105, or Gebhardt II/337-339. Cf. Aristotle, NE, 1098 b1-12.

[g](part0012.html#ch1fn-111) Cf. above [II/13-14ff.].

[71](part0012.html#ch1fn-112) The text is evidently corrupt here. Gebhardt
emends along lines suggested by the NS. I believe his version of the text
makes sense if understood as I have translated it. For an alternative version
and full discussion, see Eisenberg 1, 107-109.
