V.I
# INTRODUCTION.


"If it cann(»t be said of Comte that lie has created ascience, it

mayl)e said trulythathe has, for the firsttime,madethe creation
possible. This is agreatachievement,and, withtheextraordinary
merit of his historical analysis, and of his philosophy ofthe phy-
sicalsciences,is enough toimmortalizehisname." John Stuart
Mill.

"Comte is now geiieially admitted to have been themost emi-
nent and impf)rtant of tiiat iiiteresting groujt of thinkers whom
the overthrow of old institutions in France turned towards social
speculations." John Morley.

THE
foregoing- quotations f]-om the two English
authorities who have most severely criticized the
"Positive Polity" of Auguste Comte, bear witness to
the profound imj^ulse given to modern thought by the
publication of the " Positive Philosophy," more than half
a century ago. Miss Martineau's condensation appeared
eleven years later, duringthe lifetime of Comte and before
the completion of his later works. It was warmly
welcomed by the philosopher himself, and adopted by him
as the popular form of his own voluminous treatise.

Since that time an immense amount of discussion has
arisen about the philosophy itself, about the subsequent
development of Comte's own career and sj^eculations, and
on the incidents of his strenuous life. In placing before
the public Miss Martineau's version of the "Philosophie
Positive" in a new form, it seems a fitting occasion to in-
troduce it by some notice of Comte's own life and labours,
as well as by some account of that which he called his
"fundamental work," and of the very remarkable version
by which Harriet Martineau gave it a new literary form.

Auguste ComteAvas born at Montpellier, in the south of
France. 19th Jan., 1798, the eldest son of Louis Comte,
treasurer of taxes for the department of Hcrault, and of
Rosalie Boyer, whose family produced some eminent
l)hysicians. Both father and motherwere sincereCatholics
and ardent royalists. Their son was christened Isidore
Auguste Marie Francois Xavier. The house in which he
was born is still to be seen opposite the church of Sainte
Eulalie. At the age of nine, a small and delicate child,he
was placed as a boarder in the Lycee of his native city.

He soon showed extraordinary intelligence and industry,
a character of singularcoui*age and resolution, and a spirit
of defiance towards religious and civil authority. He re-
fused to conform to any worship, and avowed an open
hatred of Napoleon and his schemes of conquest. Anec-
dotes are still told of his prodigious memory ; he could
repeat a hundred verses after a single recital, and could
recite backwards the words of a page that he had once
read. He carried off all prizes, and at the age of fourteen
and a half lie had passed through the entire course of
the Lycee. He then studied mathematics under Daniel
Encontre, a teacher of great ability, whose place he was
able to take in his fifteenth year. At the age of sixteen he
passed in the Ecole Pojyfech/ilque, the first on the list of
candidates for the south and centime of France.

In October, 1814, the young Comte, then in his seven-
teenth year, entered the great college at Paris, and there
applied himself with his usual energy to mathematics and
physics under the illustrious Poinsot. Hewas called"the
philosopher," and took the lead amongst his fellow pupils
by his energy as well as his abilities. He was known as
an ardent republican,a fierce opponentof tyranny,whether
theological, political, or academic. In 1816, one of the
tutors having given offence to the younger pupils, Comte
took the lead in demanding his resignation, and drew up a
curt memorial to this effect. The college was sent down,
and Comte, who was only in his second year of residence,
as the author of the insurrection, was sent home to his
despairing parents and placed under the surveillance of
the police, with his hopes of a future career entirely
destroyed.

Forsometime hestudiedbiologyin themedical schoolof
Montpellier, but in September, 1816, being then eighteen,
he returned to Paris with the brave intention of suj)port-
ing himself l\v lessons. He now dropped the mediaeval
name of Isidore bywhich he had been known from infancy,
and took his Roman baptismal name of Auguste. In the
following year he was introduced to Saiut-Simou, with
whom he remained in relations forfour or five years. The
vague,optimistic,audhumanitarian dreamsofthissingular
reformer did undoubtedly exercise a certain fascination
over the youthful mind oi Comte, and gave his genius aud
character an iuHexible bent towards a scheme of social
reorganization. But the shallowness of Saint-Simon's
acquirements could not impart anything of a solid kind to
such a mind as Comte's and the vanity and charlatanry
;
of the famous socialist alienated his young follower. They
soon came into direct opposition on Saint-Simon's con-
tention that intellectual aud moral re-organization could
only proceed from the authority of government. Saint-
Simon claimed as liis own thework of his youfigcolleague,
and when he fell back on a mystical theologism, the
rupture became final.

AugusteComtewrote a fewpieces forvarious periodicals
in Paris, to which he attached but little importance. His
first great philosophical woi'k was a pamphlet in 191
pages, published in May. 1822, with an introduction by
# THE POSITIVE PHILOSOPHY OF

# AUGUSTE COMTE.


## INTEODUCTION.


## CHAPTER

I.


ACCOUNTOFTHEAIM OF THISWOKK. VIEWOF THE NATURE
AND IMPORTANCE OF THE POSITIVE PHILOSOPHY.

A GENERAL statement of any system of philosophy
maybe eitherasketch of a doctrine to be established,
or a summaryof a doctrine alreadyestablished. If greater
value belongs to the last, the first is still important, as
characterizing from its origin the subject to be treated.

In a case like the present, where the proposed study is
vast and hitherto indeterminate, it is esjjecially important
that the field of research should be marked out with all
possible accuracy. For this purpose, I will glance at the
considerations which have originated this work, and which
will be fully elaborated in the course of it.

In order to understand the true value and character of
the PositivePhilosophy, we must take a brief generalview
of the progressive course of the human mind, regarded as
a whole for no conception can be understood otherwise
;
than through its history.

From the study of the development of
human intelligence, in all directions, and progress"™*"
through all times, the discovery arises of a ° *
great fundamental law, to which it is necessarily subject,
and which has a solid foundation of pi'oof, both in the
facts of our orga—nization and in our historical experience.

The law is this: that each of our leading conceptions,
—
eachbraucliofourknowledge, passes successivelythrough
three different theoretical conditions : the Theological, or
ofi rcti pt oi so iu ts iv; e.the IM neta op th hy es ric wa ol r, do sr ,ab ts ht erac ht u; ma an nd t mh ie ndSc ,ie bnt yifi ic t,
s
nature, employs in its progress three methods of philoso-
phizing, the character of which is essentially different,and
even radically oj^posed : viz., the theological method, the
metaphysical, and the positive. Hencearise three philoso-
phies, or general systems of conceptions on the aggregate
of phenomena, each of which excludes the others. The
first is the necessary point of departure of the human
understanding and the third is its fixed and definitive
;
state. The second is merely a state of transition.

In the theological state, the human mind,
^ ' ^ • seeking the essential nature of beings, the
f—irst and final causes (theorigin—andi^urpose) of all effects,
inshort,Absoluteknowledge, supposesallphenomenato
beproducedbytheimmediateactionof suj)ernaturalbeings.

econ, „ j^Q(I j^n f^(t ,h g^e ^|Qm je j^ta Qp fhy ts hi ec fa il rsts ,ta tt he e, w mh ii nc dh si us ppo on sl ey sa
e . ,
instead of supernatural beings, abstract forces, veritable
entities (that is, personified abstractions) inherent in all
beings, and capable of producing all phenomena. What
is called the explanation of phenomena is, in this stage, a
mere reference of each to its proper entity.

™, . , ^^ In the final, the positive state, the mind
" ' has given overthevain search after Absolute
notions, the origin and destination of the universe,and the
causes of —phenomena, and applies itself to the study of
their laws, that is, their invariable relations of succession
and resemblance. Reasoning and observation, duly com-
bined, are the means of this knowledge. What is now
understood when we speak of an explanation of facts is
simply the establishment of a connection between single
phenomena and some general facts, the number of which
continually diminishes with the progress of science.

The Theological system arrived at the
^''''"*' highest perfection of which it is capable
ofeach.*''
whenitsubstituted theprovidentialaction of
a single Being for the varied operations of the numerous
divinities which had been before imagined. In the same
way, in the last stage of the Metaphysical system, meu
substitute one great entity (Nature) as the cause of all
phenomena, instead of the multitude of entities at first
supposed. In the same way, again, theultimate perfection
of the Positive system would be (if such perfection could
behopedfor)torepresent —allphenomenaasj^articularaspects
of a single general fact; suchas Gravitation, forinstance.

The importance of the working of this general law will
be established hereafter. At j^resent, it must suffice to
point out some of the grounds of it.

There is no sciencewhich, having attained
the positive stage, does not bear marks of *^
the Kw^^*^
having passed through the others. Some
timesinceitwas(whateveritmightbe) composed,as wecan
now perceive, of metaphysical abstractions and, further
;
back in the course of time, ittookitsform from theological
conceptions. We shall have only too much . , ,
occasion to see, as we proceed, that our
most advanced sciences still bear very evident marks of
the two earlier periods through which they have passed.

The progress of the individualmind is not onlyan illus-
tration, but an indirect evidence of that of the general
mind. The j^oiut of departure of the individual and of
the race being the same, the phases of the mind of a man
correspond to the epochs of the mind of the race. Now,
each ofus is aware, if he looks back upon his own history,
that he was a theologian in his childhood, a metaphysician
in hisyouth, andanaturalphilosopherinhismanhood. All
men who are up totheirage can verify this for themselves.

Besides the observation of facts, we have theoretical
reasons in support of this law.

Themost importantof thesereasonsarises rpi ..g+jcni
from the necessity that always exists for
some theory towhich to refer our facts, combined with the
clear impossibilitythat,at the outset of human knowledge,
men could have formed theories out of the observation of
facts. All good intellects have rej^eated, since Bacon's
time, that there can be no real knowledgs but that which
is based on observed facts. This is incontestible, in our
present advanced stage ; but, if we look back to the
primitive stage of human knowledge, we shall see that it
must have been otherwise then. If it is true that every
theory must be based upon observed facts, it is equally
true that facts cannot be observed without the guidance of
some theory. Without such guidance, our facts would be
desultoryand fruitless we could notretain them for the
; :
most part we could not even perceive them.

Thus, between the necessity of observing facts in order
to form a theory, and having a theory in order to observe
facts, the human mind would have been entangled in a
vicious circle, but for the natural opening afforded by
Theological conceptions. This is the fundamental reason
for the theological character of the primitive philosophy.

This necessityis confirmed bythe perfect suitability of the
theological philosophy to the earliest researches of the
human min —d. It is remarkable that the most inaccessible
questions, those of the nature of beings, and the origin
—
and purpose of phenomena, should be the first to occur
in a primitive state, while those which are really within
our reach are regarded as almost unworthy of serious
—
study. The reason is evident enough : that experience
alone can teach us the measure of our powers and if men
;
had not begun by an exaggerated estimate of what they
can do, theywouldneverhavedoneallthattheyarecapable
of. Our organization requires this. At such a period
there coxild have beennoreceptionof apositivephilosophy,
whose function is to discover the laws of phenomena, and
whose leading characteristic it is to regard as interdicted
to human reason those sublime mysteries which theology
explains, even to their minutest details, with the most
attractive facility. It is just so under a practical view of
the nature of the researches with which men first occupied
themselves. Such inquiries offered the powerful charm of
—
unlimitedempireovertheexternalworld, aworlddestined
wholly for our use, and involved in every way with our
existence. Thetheologicalphilosophy^presentingthisview,
administered exactly the stimulus necessary to incite the
human mind to the irksome labour without which it could
make no progress. We can now scarcely conceive of such
a state of things, our reason having become sufficiently
maturetoenteruponlaborious scientificresearches,without
needing any such stimulus as wrought upon the imagina-
tionsofastrologersandalchemists. Wehavemotiveenough
in the hope of discovering the laws of phenomena, with a
view to the confii-mation or rejection of a theory. But it
could not be so in the earliest days ; and it is to the
chimeras of astrology and alchemy that we owe the long
series ofobservationsandexperimentsonwhich ourpositive
science is based. Kepler felt this on behalf of astronomy,
and Berthollet on behalf of chemistry. Thus was a spon-
taneous philosophy, the theological, the only possible be-
ginning, method, and provisional system, out of which the
Positive philosophy could grow. It is easy, after this, to
perceive how Metaphysical methods and doctrines must
have afforded the means of transition from the one to the
other.

The human understanding, slow in its advance, could
not step at once from the theological into the positive
philosophy. The two are so radically opposed, that an
intermediate system of conceptions has been necessary to
renderthetransition possible. Itis onlyindoing this,that
Metaphysical conceptions have any utility whatever. In
contemplating phenomena,men substitutefor supernatural
direction a corresponding entity. This entity may have
been supposed to be derived from the supernatural action
but it is more easily lost sight of, leaving attention free
for the facts themselves, till,atlength, metaphysical agents
have ceased to be anything more than the abstract names
of phenomena. Itis not easyto sayby what otherprocess
than this our minds could have passed from supernatural
considerations to natural ; from the theological system to
the positive.

The Law of human development being thus established,
let us consider what is the proper nature of the Positive
Philosophy.

As we have seen, the first characteristic of Characterof
the Positive Philosophy is that it regards all the Positive
phenomena as subjected —toinvariablenatural Philosophy.

Laws. Our business is, seeing how vain is any rese —arch
into what are called Causes, whether first or final, to
pursue an accurate discovery of these Laws, with a view
to reducing them to the smallest possible number. By
speculating upon causes, we could solve no difficulty about
