---
title: "R.A.Fisher: The Thoughtful Eugenist"
author: "Professor A.W.F.Edwards FRS"
---

R.A.Fisher: The Thoughtful Eugenist  
I  
POSITIVE EUGENICS 
 
Professor A.W.F.Edwards FRS  
Fellow of Gonville & Caius College   

For the members of Fisher’s college  
14 November 2021 
 
### The Caius undergraduate is introduced to Eugenics

In October 1909 Ronald Aylmer Fisher, aged nineteen, won a scholarship in
mathematics to Gonville and Caius College in Cambridge University. In June the
University had celebrated Charles Darwin’s centenary and the half-centenary of his
Origin of Species. Fisher was already no stranger to the book, or to its sequel The
Descent of Man, for at Harrow School he had chosen the complete works of Darwin
in thirteen volumes as a school prize. Fascinated by the theory of natural selection and
its application to man he stepped into an atmosphere not only Darwinian but the new
Mendelian, for Cambridge was the home of William Bateson, the champion of Gregor
Mendel’s long-neglected paper which had resurfaced in 1900. The new century was
facing a scientific revolution and in Britain Cambridge was its base.

In 1906 Bateson had introduced the name genetics for the new subject of the
physiological basis of inheritance. In London he presided over The International
Conference on Hybridisation and Plant Breeding, which changed its name in the
course of the Conference to the Third International Conference on Genetics. In time
for the Darwin Celebration, Cambridge University Press published Bateson’s major
book Mendel’s Principles of Heredity, though two of his young assistants had got
theirs out first: R.C.Punnett with his brief Mendelism (1905) and R.H.Lock with his
remarkable Recent Progress in the Study of Variation, Heredity, and Evolution
(1906). Punnett and Lock were both young Fellows of Gonville and Caius College,
and they were both members of the London-based Eugenics Education Society. So
was Sir Charles Sherrington, later to be celebrated as Caius’s first Nobel Laureate.

Lock was the son of the Bursar J.B.Lock, many generations of whose
descendants have been educated at Caius. Father and son are memorialised in the
handsome Lock Jug which they presented to mark their simultaneous Fellowships.

R.H.Lock presented the second edition of his book to the Library in July 1909; Fisher
matriculated in October, and there is much evidence that he read it. Chapter X
‘Eugenics’ was new for this edition. It and the last part of the ‘Concluding Chapter’
XI give a remarkable account of contemporary views of eugenics promulgated by
Francis Galton, Karl Pearson, Sidney Webb, Bernard Shaw – and the unknown Mr
McDougal whom we shall meet again below. Their language is no longer regarded as
acceptable, but ‘The past is another country; they do things differently there’, and we
have a duty to allow for that.

In Chapter X Lock explains that eugenists seek to confront the ‘dangerous
differences in the incidence of the birth-rate’ among the groups identified by Pearson,
but quotes Thomas Huxley: ‘Who is competent to do the necessary selecting?’ and
himself adds another objection ‘The ruthlessness necessary for the carrying out of the
method of deliberate selection is in itself so unsocial a quality that, if it were ever to
arise, society would probably be far worse off than before’. So what is to be done?
Lock describes some suggestions, but ‘It must not be supposed that the writer is a
special advocate of all or any of the suggestions which have been mentioned above’.
There was plenty for Fisher to think about.

It seems likely that Punnett will have told Fisher about the Society and
perhaps even floated the idea that a Cambridge branch might be started. Fisher and
some student friends lobbied senior members of the University with the idea and in
1911 the Cambridge University Eugenics Society was founded, with substantial
support among the dons. One of them was the Regius Professor of Physic Sir Clifford
Allbutt, like Punnett and Lock a Fellow of Caius. Professor A.C.Seward, the
Professor of Botany, was President, Fisher was the undergraduate chairman and the
young John Maynard Keynes the Senior Treasurer.

### Fisher’s early papers

Fisher’s academic work flourished. He took a First Class in Part I of the Mathematical
Tripos in 1911 and another in Part II in 1912. During this time his interest in
statistical theory was sparked by one of his Caius teachers, the astronomer F.J.M
Stratton, leading to his first publication ‘On an absolute criterion for fitting frequency
curves’ in the latter year. He was later to call the criterion to which he referred
‘likelihood’, and the method he advocated ‘the method of maximum likelihood’. This
was his entry into theoretical statistics, to be magnificently expanded into ‘On the
mathematical foundations of theoretical statistics’ ten years later. His second
publication, during his Wollaston studentship year 1912-13 at the Cavendish
Laboratory, was a long essay ‘Application of vector analysis to geometry’.

At the end of this academic year he repeated a paper ‘Some hopes of a
eugenist’ to the Eugenics Education Society (on 2 October 1913, presumably in
London) that he had given to the Cambridge branch in November 1912, adding an
important reference. It was published in Eugenics Review in 1914 (5, 309-315),
Fisher’s first publication in eugenics. It must be this paper of 1914 which Fisher was
to call ‘ephemeral’ in The Genetical Theory of Natural Selection of 1930. Since it was
originally delivered in 1912 at the age of 22, he might indeed wish us to regard it as
ephemeral juvenilia, but we should note its importance and make allowance for its
youthful exuberance.

It needs to be read in its entirety in order to appreciate the impact of the
Cambridge environment favourable to eugenics on the mind of a student well-read in
Darwin, Galton and Karl Pearson as well as the books by Bateson, Punnett and Lock.
A brief quotation will set the scene: ‘From the moment we grasp, firmly and
completely, Darwin’s theory of evolution, we begin to realise that we have obtained
not merely a description of the past, or an explanation of the present, but a veritable
key of the future’. Fisher’s rolling English oratory is soon interrupted by a paragraph
which starts by giving the important reference additional to his Cambridge talk:

>What appears to be the underlying principle in the decadence of civilized races has been
>revealed in an article [‘Human fertility’] by Mr. J.A.Cobb, which appeared in the EUGENICS
>REVIEW last January [1913, 4, 379-382]; an article which, if my faith in it is justified, must be
>regarded as containing the greatest addition to our eugenic knowledge since the work of Galton.

The full 1914 version of the paper ‘Some hopes of a eugenist’ is the basis of
Fisher’s argument for a kind of ‘positive eugenics’. In it he had already pointed out,
probably first in the 1912 original, ‘In the present time in this country the evidence
appears to be conclusive that we are breeding more from the worse than from the
better stocks’. This well-known – and at the time much-discussed – association in
Britain between lesser achieved fertility and greater wealth was seen to have
important long-term consequences. So far the discussion had been limited to the
immediate effect on the composition of the population and the increasing
preponderance of the unskilled that it entailed. Cobb, however, pointed out that the
problem was not just the class-differential rates of reproduction themselves but their
population-dynamic consequences:

>If, however, as I shall try to show, there is a natural tendency under modern conditions for
>the more intelligent to become less fertile, the problem is a more serious one.
>
>If variations in fertility are inherited and the wealthier classes have for generations been put
>through a process of selection by which members of small families have been given an
>advantage over members of large families, we should expect that the wealthier classes would, as
>a whole, be less fertile than the poorer classes.

Fisher seized on the idea, and with the engaging enthusiasm (and language) of
his 22 years, explained the principle and its harmful consequences:

>Mr Cobb points out that in any society which is so organised that members of small families
>enjoy a social advantage over members of large ones, the qualities of all kinds, physical, mental,
>and moral which go to make up what may be called “resultant sterility” tend, other things being
>equal, to rise steadily in the social scale; so that in such a society, the highest social strata,
>containing the finest representatives of ability, beauty, and taste which the nation can provide,
>will have, apart from individual inducements, the smallest proportion of descendants; and this
>dysgenic effect of social selection will extend throughout every class in which any degree of
>resultant sterility provides a social advantage.

We may here note that the argument is not between classes but ‘throughout every
class’. It is not a static picture of class differentiation in fertility but of a continuum as
in the social scale. The effect described is a dynamic one of social mobility involving
the whole population. Geneticists call such a continuum a cline, though exactly what
might be the measure of the ‘scale’ of the social cline is open to debate. However, no-
one doubts its existence.

Fisher continues:

>It is this principle, vital in its importance and almost universal in its application, which
>explains to us why civilisations in the past, with one notable exception, and especially urban
>civilizations, in which the value of wealth is greatly accentuated, have ultimately collapsed
>owing to the decay of the ruling classes to which they owed their greatness and brilliance. And
>it is this principle which must underlie the reconstruction of our own civilisation if it is not to
>share the fate of those which have preceded it. (In a footnote, Fisher says the ‘one notable
>exception’ is provided by the Nordic civilization of the 10th century.)

The paper is incidentally also remarkable for its ending, in which Fisher introduces
the notion later called ‘inclusive fitness’ and developed by J.B.S.Haldane,
W.D.Hamilton and others to explain the evolution of altruism. He advocates
‘versatility’ ‘So that not only in youth, but throughout life, we may retain full
sympathy for our fellow men’.

His next paper after ‘Some hopes of a eugenist’ is ‘Frequency distribution of
the values of the correlation coefficient in samples of an indefinitely large population’
(1915), in which he proved by a novel geometric argument the equation of the
distribution function of the coefficient, which hitherto had only been approximated.
Knowledge of this function is fundamental to assessing the significance of a
correlation, while Fisher’s geometric method of representing a sample in a
multidimensional Euclidean space became standard in distribution theory. This paper
announced his arrival in the pantheon of mathematical statisticians and gives the lie to
the claim that his scientific agenda was driven by eugenic concerns. Correlation
coefficients are of universal applicability throughout statistics, as is distribution
theory.

Two other papers have quite properly caught the eye of historians of science,
but they were not published until the typescripts were unearthed in 1976. Both were
read to undergraduate meetings of the Society. The first, ‘Mendelism and biometry’,
to the Cambridge society on 10 November 1911 is an astonishing harbinger of
Fisher’s great 1918 paper ‘The correlation between relatives on the supposition of
Mendelian inheritance’, which is the foundation of biometrical genetics, animal and
plant breeding methods, the analysis of variance, and much else. The second paper
‘Evolution and Society’ on 13 March 1912 (in W.B.G.Batten’s rooms on S staircase,
Tree Court) is a brief but remarkable philosophical discourse on the implications of
natural selection for the evolution and structure of human society, with relevant
comparisons to insect societies and other biological communities which act
cooperatively.

### Positive eugenics

In her biography of her father The Life of a Scientist Joan Box brilliantly describes his
life and extra-mural work while teaching for a year at Rugby School and then at
Bradfield College (pp.49-61). The extra work not only included an attempt at
subsistence farming that would impress any modern green student politician, but an
increasing involvement in the Eugenics Education Society encouraged by its President
Leonard Darwin, Charles’s fourth surviving son.

Darwin (Leonard) not only provided a personal link with Charles but
nourished Fisher’s intellectual life by involving him in writing short notices of papers
in the genetical literature for the Eugenics Review, greatly widening Fisher’s own
knowledge. He also arranged for him to receive a part-time salary from the Society
for this work and other assistance that he gave. Soon he was engaging Fisher in
correspondence about the interpretation of genetical correlations which inspired
Fisher’s famous paper ‘The correlation between relatives on the supposition of
Mendelian inheritance’.

When this paper was reviewed unfavourably by the Royal Society’s referees it
was withdrawn. Finished in mid-1916, two year later it was still unpublished. Darwin
stepped in and found that the Royal Society of Edinburgh would publish it for a
contribution of about £50 to the printing costs, and told Fisher that the Eugenics
Education Society wished to sponsor it. Thus was the ‘1918’ paper born. Fisher wrote
a less technical summary of it for the Eugenics Review which ended:

>In conclusion it is right that I should express my deep sense of gratitude to the Eugenics
>Education Society, who have most generously assisted me throughout; and in particular to
>Major Leonard Darwin whose continual kindness and encouragement has enabled me to carry
>through the work.

Yes, the Eugenics Society ensured the publication of this seminal paper, but it is not
true, as has been written, that ‘We should see it ... as a stunning contribution to
eugenics’. It contains no eugenics at all.

Meanwhile the Great War of 1914-18 had taken place, and the appalling loss
of life on the Western Front had intensified the pre-war discussion at home of the
demographic consequences of class-variation in fertility. At a time when there was
already concern about the possibility of the population declining, the loss of so many
young men became part of the discussion, which had already generated the phrase
‘Positive eugenics’ to refer to the need ‘To increase the birth-rate in the professional
classes and among the highly-skilled artisans’, as Fisher put it in his paper ‘Positive
eugenics’ in 1917.

Fisher’s paper was what one might expect from a young man of twenty-seven
obsessed with a mission to halt a long-term decline in the British population in both
quantity and quality. He calls upon the professional classes and the trade-unions to
help with methods ‘by which material advantage may be given to the families of
members’ by scholarships, facilities for professional training and the free exchange of
professional services between members. He ends:

>The present distribution of the birth-rate is draining the nation of its best ability, and if I am
>right in supposing that the root cause of this dysgenic selection is the difficulty of giving to the
>children of the professional classes an adequate start in life, a programme of cooperation with
>the professional classes should constitute the first great step in Positive Eugenics.

### A return to J.A.Cobb’s theory

At the end of the 1919 school year Fisher ended his unhappy career as a school-
master, presumably a war-time occupation since his extreme short-sightedness had
made him unfit for military service. He had three foundational papers in mathematical
statistics under his belt. The first, introducing the method of maximum likelihood
hardly yet recognized, the second solving the distribution of the correlation
coefficient, and the third a magnum opus on the correlation between relatives which
introduced the analysis of variance.

He applied for a Fellowship at Caius, but was unsuccessful. Nevertheless, he
had been noticed. A Cambridge botanist, Horace Brown, introduced him to Dr
E.J.Russell, the Director of Rothamsted Experimental Station who was visiting
Cambridge looking for staff. ‘In August there followed an offer from Rothamsted:’ -
writes Joan Box - ‘would Fisher come for 6 months or a year to find out whether the
accumulated records could yield more information by a thorough statistical analysis
than had been possible in the absence of a trained statistician?’ From his appointment
in 1919 until 1933 Fisher the Caius mathematician was to invent all the statistical
methods that were needed himself. Russell soon made the post permanent: ‘He
reported to me weekly at tea at my house. It took me a very short time to realise that
he was more than a man of great ability, he was in fact a genius who must be retained’
(Fisher Box, p.97). Caius caught up the following year by electing him into a non-
resident Fellowship for six years.

Fisher did not mention Cobb’s theory in ‘Positive eugenics’, but we know that
he had been continuing to think about it. A year or two before 1968 Joan Box was
clearing out the family house Milton Lodge in Harpenden and found a typescript at
the back of a cupboard with the first three chapters of a book by Fisher. It is dated
1919 and is a draft that formed the basis of parts of The Genetical Theory of Natural
Selection of 1930. In particular part of Chapter XI ‘The social selection of fertility’
deals at length with Cobb’s theory and its Galtonian origins. At some later stage,
presumably when Fisher was reviewing the material for inclusion in The Genetical
Theory, he wrote in the margin of the typescript a comment that ‘neither its logical
cogency nor its importance to sociological theory, seem to have been ever widely
grasped, and apart from some ephemeral papers of my own … it might be said to have
been totally neglected’. (This appeared in The Genetical Theory with the addition at
the ellipsis of ‘and a brief discussion in Major Darwin’s recent book The Need for
Eugenic Reform’.)

I can find no reference to Cobb’s theory in any work of Fisher’s published
after 1914 until 1924 when he reviewed E.F.Rathbone’s The Disinherited Family in
the Eugenics Review. In an extensive discussion of her proposals for family
allowances he advances his version designed to counter the dysgenic effects to which
Cobb had drawn attention.

Then in 1926 came ‘Eugenics: can it solve the problem of the decay of
civilisations?’, originally an address in French given in Paris. It is Fisher’s first full
account of his proposal for family allowances which he was to promote tenaciously
for the next seventeen years. 1926 was also the year of publication of Darwin’s book,
in which the author refers to Cobb’s paper and to the contemporaneous paper by
Fisher ‘with whom I have frequently discussed these topics’ (footnote, p 339). Fisher
ended his long review ‘Modern eugenics’, also 1926, of Darwin’s book by recording
his ‘particular personal gratification’ that the author had noted ‘these topics’.

In a long essay in 1929 entitled ‘The over-production of food’ Fisher reviews
the problem of population from an economic point of view in the light of western
Europe’s population no longer replacing itself. He stresses the consequences of a
system of flat-rate family allowances but it is ‘beyond the scope of the present article’
to question its ‘intricate’ ‘effects upon the hereditary constitution of future
generations’.

Once started at Rothamsted Fisher devoted his time to the development of the
statistical mathematics for which he became famous. In 1925 he published Statistical
Methods for Research Workers, the most influential statistics book of all time, while
the companion volume The Design of Experiments based directly on his work at
Rothamsted was published in 1935, two years after he had moved to University
College London as Galton Professor of Eugenics. For the most part he set aside any
thoughts of continuing with the book he had started just before his Rothamsted
appointment, but in 1928 he took up the work again, encouraged by Darwin. It was to
become The Genetical Theory of Natural Selection and to incorporate, in its last five
chapters, the mature development in Fisher’s mind of the idea planted there in 1913
by Cobb’s paper.

### The Genetical Theory of Natural Selection (1930)

Fisher’s 1926 paper mentioned above was a first published look at the problems he
was to consider in Chapters VIII to XII of The Genetical Theory of Natural Selection.
These chapters have tended to be neglected, pilloried or cited as racist or ‘classist’, in
spite of Fisher’s protests that they are an integral part of ‘the genetical theory of
natural selection’ as it applies to Man and his social history.

Each chapter starts with a short list of contents and ends with a Summary.
Chapter VIII ‘Man and society’ sets the scene including comparisons with social
insects. The Summary for each chapter may usefully be read first to prepare for the
main text. Chapter IX ‘The inheritance of human fertility’ considers ‘the great
variability of human reproduction’, the ‘direct evidence for the inheritance of fertility’
and ‘the evolution of the conscience respecting voluntary reproduction’. Chapter X
‘Reproduction in relation to social class’ examines the ‘economic and biological
aspects of class distinctions’ and discusses the fact that in Europe and the United
States there is an ‘inversion of the birthrate’ with respect to the prosperity of families,
the wealthier having the fewer children. ‘Those who can afford most of comforts and
luxuries can assuredly afford to have the most children, and upon purely economic
grounds … the large households of the rich might be reasonably expected to produce
and support more children than the small households of the poor’. ‘The total burden
of rearing the next generation of citizens would be more easily borne, if distributed
more in accordance with the ability to support it’.

Chapter XI ‘The social selection of fertility’ describes the crux of Fisher’s
eugenic concerns. It traces the ‘History of the theory’ to remarks by Francis Galton in
his Hereditary Genius of 1869 but quickly passes to J.A.Cobb’s 1913 paper in the
Eugenics Review already mentioned. As noted above, Fisher observes that ‘apart from
a few ephemeral papers of my own, and a brief discussion in Major Darwin’s recent
book The Need for Eugenic Reform [1926] it might be said to be totally neglected’.

Before quoting the major part of Cobb’s paper Fisher summarizes the theory
as follows:

> Restricting himself to the unconscious causes of relative infertility, Mr. Cobb points out that, just as
>the fortune of an heiress enables her to make a socially advantageous marriage [Galton’s point that
>heiresses necessarily come from small families], so among the children of families of any class,
>members of the smaller families will on the average commence life at a social advantage compared
>to members of larger families. Alongside the many excellent qualities which enable a family to
>improve its social position, relative infertility also plays its part. In this way the less fertile stocks,
>having the social advantage, will gradually permeate the upper classes of society, and there cause
>the peculiar situation in which the more fortunate and successful of mankind have the smallest
>birthrate.

Two sections follow: ‘Infertility in all classes, irrespective of its cause, gains
social promotion’ and ‘Selection the predominant cause of the inverted birth-rate’.
Fisher then continues at length with the implications of the theory for understanding
‘The fact of the decline of past civilizations’, but that is not our present subject. In the
long Summary to the Chapter he remarks ‘The various theories which have sought to
discover in wealth the cause of infertility, have missed the point that infertility is an
important cause of wealth’.

The short final Chapter XII ‘Conditions of permanent civilization’ is a call to
arms for the introduction of a system of family allowances to help break the
association between infertility and wealth. ‘The total burden of rearing the next
generation of citizens would be more easily borne, if distributed more in accordance
with the ability to support it’ (Chapter X). Fisher considers the implications of Cobb’s
theory in a mature contribution to the discussion then taking place of the introduction
of family allowances in Britain. Arguing against the adoption of the French system of
equal child allowances paid by the employer he envisages a similar system but with
the allowance being proportional to the employee’s wage, and outlines the eugenic
and economic advantages of such a plan. In neither case would the cost be borne by
general taxation but through redistribution of the employer’s wage-bill. He argues that
both benefits would accrue to the long-term advantage of society through a
contribution to the equalisation of the birth-rate throughout the different strata of the
population.

### Reactions to The Genetical Theory of Natural Selection Chapters VIII to XII.

Three of Fisher’s contemporary colleagues best-qualified to comment on his book and
in particular on the chapters on ‘Man’ were J.B.S.Haldane, Julian Huxley and
Lancelot Hogben. All were on the political left, Haldane being a member of the
Communist Party. Hogben was the most antagonistic to Fisher’s position in both
genetics and statistics, while Haldane could be relied on for vigorous and often public
comment on the human condition from a genetical point of view. Haldane and Fisher,
from their different political view-points, did however maintain a sort of barbed
friendship with mutual scientific respect. Huxley was not quite up to the intellectual
powers of the other two H’s but was the most friendly with Fisher. He, like Fisher,
was an active member of the Eugenics Society; Haldane had been a member of the
Oxford branch, while Hogben was strongly opposed.

First out of the starting-block was Haldane who in March 1931 wrote to Fisher
‘I think it would be an excellent thing to present your results about eugenics in a more
popular form’, which indeed Fisher was to do the following year (see below). Haldane
contributed a review ‘Mathematical Darwinism’ of the whole book to the Eugenics
Review (23, 115-17, 1931) in which he remarked (with a nice socialist dig at the end):

> [Fisher’s] suggested remedy for the dysgenic character of civilized societies is a very thorough-
> going system of family allowances on such a scale that infertility would no longer be a cause of
> social promotion. The reviewer considers that he has made out an extremely strong case. Indeed, if
> his biological facts are correct it is probable that a socialistic state in which no wealth was inherited
> would be more eugenic than our present society, and it is a little difficult to see why Dr. Fisher’s
> economic views are not even more radical.

Haldane, characteristically, then gives arguments against the efficacy of Fisher’s
proposal, but concludes: ‘Nevertheless, if Dr. Fisher is on the whole correct,
civilization can only be saved by a very radical change of opinion and practice’.

Then in 1932 in his book The Causes of Evolution based on lectures at the
University of Wales Aberystwyth in January 1931 Haldane wrote ‘And the usual
course taken by an evolving line has been one of degeneration. It seems to me
altogether probable that man will take this course unless he takes conscious control of
his evolution within the next few thousand years’. As late as 1955 Haldane said, in his
Woodhall Lecture at the Royal Institution, ‘I fully agree with Fisher that family
allowances are a eugenic measure, but I see no possibility of a fully eugenic policy
with the limits of our present economic system’ (The prospects of eugenics, Penguin
New Biology 22, 7-23, 1957). In fact, independently of Cobb’s argument, Haldane
never departed from the view, usually unspoken, ‘[the Nation] would have improved
more if, say a million children who were born to unskilled labourers had been born to
skilled workers, teachers and the like’ (from his eulogy for Karl Pearson, Penguin
New Biology 25, 7-26, 1958).

Huxley congratulated Fisher on The Genetical Theory by letter on 4 May
1930: ‘It does seem to me the most important book on Evolution which has come out
this century’. He later referred to the final chapters in his Galton Lecture of 1936:

>Then R. A. Fisher has brilliantly and devastatingly shown the relentless way in which such a system
>as ours promotes both infertility and certain types of talent, and in so doing ties together the genetic
>factors responsible. In the course of the generations - genes making for small families become
>increasingly bound up with those making for social and economic success; and conversely those
>making for social and economic failure become bound up with those making for high reproduction
>rates. Eugenically speaking our system is characterized by the social promotion of infertility and the
>excess fertility of social failures.

In Genetic Principles in Medicine and Social Science (1931) Hogben wrote:
(like Haldane, with a socialist dig at the end):

>R.A.Fisher has pointed out that low fertility assists materially in social advancement in societies in
>which mercantile or industrial interests predominate and thrift is the supreme social merit. This
>might tend to concentrate individuals who are incapable of having large families in the governing
>classes. As a long view of the situation, Fisher’s argument is worthy of attention. For the collective
>endowment of parenthood he makes a case which compels the serious consideration of those who
>are disposed to regard private enterprise as an institution sanctified by natural law.

For Caians, all we lack is an opinion from Joseph Needham, who of course knew
Fisher well in College for nearly twenty years. I myself during many discussions with
him had opportunities to ask about eugenics and Fisher’s contributions, but the
subjects simply never came up. Stories about Fisher, most of them amusing,
circulated freely in my time (I arrived six years after his death) but no Fellow had a
really deep knowledge of his scientific work.

I am not aware of any contemporary writer who understood Fisher’s argument
and criticized it. Much later Stephen Jay Gould (1996) did, in an essay I consider
below.

### Fisher’s papers from 1932 and 1935

In 1932 Fisher returned to the subject of the social selection of human fertility and
family allowances, first in an address to the Eugenics Society on 12 April ‘Family
allowances in the contemporary economic situation’. In this lecture he places his
proposals from The Genetical Theory in the wider political and economic context,
reminds the Society that they were incorporated in its Outline of a Practical Eugenic
Policy of ‘some years ago’, and defends them against criticism both articulated and
foreseen. He mentions the proposals of Sir William Beveridge, later incorporated in
the Beveridge Report of 1943, for a flat-rate allowance of (say) 5s. per child per week
supported by a national insurance scheme, and explains the economic reasons for
preferring proportional allowances paid by the employer. (He adds that it is only fair
to say … that Sir William has established among the professors and lecturers at the
London School of Economics the first English system of family allowances for
university teachers.)

Next, Fisher is invited to deliver the Herbert Spencer Lecture for 1932 in
Oxford, which he does on 8 June: ‘The Social Selection of Human Fertility’. This is
appropriately enough a more academic discourse, with a long introduction about the
phenomenon of natural causation arising from the probable behaviour of large
assemblages of entities such as molecules and genes, but with the same plea as before
eloquently argued.

In 1933 Fisher left his post of Chief Statistician at Rothamsted Experimental
Station to take up the Galton Professorship of Eugenics at University College London.
In a lecture ‘Eugenics academic and practical’ to the Annual General Meeting of the
Eugenics Society in 1935 (a title to which he was invited to speak) he laid out his
academic plans for a Department in what we now call human genetics. It was the
moment at which the subject of human genetics was detached from ‘practical
eugenics’, which he described as ‘practical action in the legislative sphere’. Under
Fisher and his successors the ‘Galton Laboratory’ established itself as one of the
world’s premier departments of human genetics.

In this lecture Fisher did not mention family allowances, but in the same year
the Eugenics Society issued a notice of its Aims and objects. ‘Eugenics aims at
improving the inborn qualities of future generations’. Under ‘Positive Eugenics’ a
paragraph states:

>FAMILY ALLOWANCES: The Society favours the provision of family allowances by the
>establishment of graded equalization pools and other systems calculated to have a eugenic effect. It
>regards as wholly dysgenic the provision of allowances through flat rate payments by the State.

It is clear that Fisher had carried his proposal in the Society.

### Haldane’s Heredity and Politics 1938 and The Geneticists’ Manifesto 1939

In 1938 Haldane published his Muirhead Lectures ‘Heredity and Politics given at the
University of Birmingham the previous year, and in Chapter 4 ‘Differential Fertility
and Positive Eugenics’ he describes Fisher’s view in The Genetical Theory and
understands his evolutionary argument. But he does not describe Fisher’s solution. He
writes: ‘My own view is that some form of family allowances would be a measure of
social justice, but would be extraordinarily difficult to carry out. It would be most
difficult to arrange a system of family allowances for the professional groups such as
lawyers and doctors, who are a valuable class of men from the eugenic point of view’.
Fisher had argued that the child allowances in such self-employed professional classes
should be via their professional associations, which would add a sum to their
members’ annual subscription that would allow a standard allowance per child to be
paid. Difficult, certainly, but Fisher was promoting a progressive idea at no cost to the
state that first of all needed to be seriously discussed. Haldane continued ‘Although I
am in considerable sympathy with Fisher’s views, I cannot regard them as resting on
very complete evidence’, implying criticism of Fisher’s careful arguments in The
Genetical Theory.

The following year at the Seventh International Congress of Genetics at
Edinburgh ‘The Geneticists’ Manifesto’ Social Biology and Population Improvement
was drawn up and circulated by seven participants, F.A.E.Crew, J.S.Huxley,
J.B.S.Haldane, H.J.Muller, S.C.Harland, J.Needham and L.T.Hogben. It attracted
fourteen further signatures, including those of G.Dahlberg, Th.Dobzhansky,
R.A.Emerson, A.G.Steinberg and C.H.Waddington. As we have noted above, Huxley,
Haldane and Hogben had all understood and applauded Fisher’s argument. It was not
explicitly mentioned, but the following extract indicates support for the practice of
eugenic selection:

>The intrinsic (genetic) characteristics of any generation can be better than those of the preceding
>generation only as a result of some kind of selection, i.e., by those persons of the preceding
>generation who had a better genetic equipment having produced more offspring, on the whole, than
>the rest, either through conscious choice, or as an automatic result of the way in which they lived.
>Under modern civilised conditions such selection is far less likely to be automatic than under
>primitive conditions, hence some kind of conscious guidance of selection is called for. To make this
>possible, however, the population must first appreciate the force of the above principles, and the
>social value which a wisely guided selection would have.
>
>[Sixthly,] conscious selection requires, in addition, an agreed direction or directions for selection to
>take, and these directions cannot be social ones, that is, for the good of mankind at large, unless
>social motives predominate in society. This in turn implies its socialised organisation. The most
>important genetic objectives, from a social point of view, are the improvement of those genetic
>characteristics which make (a) for health, (b) for the complex called intelligence and (c) for those
>temperamental qualities which favour fellow-feeling and social behaviour rather than those (to-day
>most esteemed by many) which make for personal “success”, as success is usually understood at
>present.

Not surprisingly given the socialist methods proposed, Fisher, who was
present at the Congress, did not sign. Indeed, he had given his contrary opinion
privately in a letter to his friend C.S.Stock in 1932: ‘… anything so big as eugenic
aims must be controlled by the personal choice of individuals acquainted with their
own individual needs and circumstances’. His proposal for family allowances did not
seek ‘the improvement of genetic characteristics’. It was more modest and more
urgent, intended to halt the dynamic action of the processes currently acting in the
British population in the opposite direction. Many years later Guiseppe Tomasi di
Lampedusa captured the same logic in his famous Sicilian novel Il Gattopardo: ‘Se
volgiamo che tutto rimanga come è, bisogna che tutto cambi. Mi sono spiegato?’ – ‘If
we want everything to stay the same, everything will have to change. Do I make
myself clear?’

An experiment involving ‘conscious selection’ and ‘socialised organisation’
was about to start. The Second World War began a few days after the Congress broke
up.

### 1943 Beveridge and Fisher

In 1943 Sir William Beveridge gave the Galton Lecture on 16 February. As we have
seen, Fisher was aware of Beveridge’s proposals for flat-rate family allowances
supported by the government, and Beveridge, himself a member of the Eugenics
Society, was familiar with Fisher’s arguments, for Fisher had sent him his 1932
address to the Society. Beveridge’s lecture ‘Eugenic aspects of children’s allowances’
is an attempt to assess the merits of the two approaches.

‘Do people tend to have relatively fewer children because they are rich, or is it
the other way round, that infertility is the cause of economic success?’ asks
Beveridge. He has already missed Fisher’s point (and Cobb’s). Both effects acting
concurrently are involved in social advancement in consequence of which the
associated genotypes will rise together in the social strata, taking with them the
attributes which favour both increased economic success and reduced fertility. Both
are part of the same phenomenon and result in the same effect, namely the
stratification of society so that economic success and reduced fertility are correlated.
The answer to Beveridge’s question is that both alternatives are true, and, that being
the case, they provide the answer to Fisher’s question, which is ‘Why are the
successful strata innately less fertile?’

But then Beveridge seems to weaken: ‘Not only is infertility the cause of
social promotion, but social promotion in turn causes infertility’. However, ‘it is not
easy to believe that there has been enough time for selection, working by itself, to
produce those enormous differences between the relative fertility of different classes.
After all, natural selection is a relatively slow process’. (Fisher once confided to my
student contemporary J.S.Gale that he had written The Genetical Theory with the
main aim of demonstrating the remarkable power of natural selection.)

We may forgive Beveridge for some lack of clarity in his long address
because, he tells us, he had no script and had just come from the House of Commons
listening to the opening debate on the Beveridge Report. Towards the end he remarks
that if Professor Fisher is wrong, and ‘the lower fertility of the wealthy class is due, to
some extent, not to selection but to the fact that they are wealthy or are educated, that
still more strengthens the argument for … allowances above the subsistence level in
these higher grades so as to remove as completely as possible the premium on
infertility’. It is an interesting remark from a social reformer, but then he caps it in his
peroration by saying:

>One of the things which we in this country like to do is to look back with pride upon our ancestors.
>As a nation we look back with pride on our ancestors of 200 or 300 years ago, and some can look
>back individually to ancestors of distinction. If we look back, I do not see why as a community we
>should not look forward 200 or 300 years and see that we ensure the best possible posterity. That
>depends on breeding not from the worse stocks, but from the better. That is worth doing and ought
>not to be regarded as anything fantastic or unreasonable. We ought to take thought not of to-day,
>nor perhaps of to-morrow, but of 100 or 200 years ahead. We have need to look forward as well as
>to look back.

Fisher sums up the whole problem in ‘The birthrate and family allowances’
also in 1943 in what reads as a reply to Beveridge’s Galton Lecture. It is his most
eloquent, and as it turned out the final, advocacy of his proposal for family allowances
to allay the consequences of the ‘Cobb principle’. His only mention of the principle
itself is that ‘It was, in fact, primarily with a view to the eugenic problem that I first
came to study the possibilities and probable effects of family allowances’.

Though there is no indication that the paper was given as a lecture, it gives no
references and does not mention Beveridge. The well-known American geneticist
J.F.Crow (‘Jim’), who knew Fisher well, once told me that he thought Fisher had
simply tired of arguing, in which case we might regard the 1943 paper as a kind of
apologia, not an apology but a final defence of a rational scheme which Beveridge
should have appreciated. He was not without hope:

>It is most earnestly to be hoped that renewed study of the subject in the light of the experience of
>other nations and the requirements of post-war reconstruction will enable the problem to be met, not
>by a patchwork of ineffectual compromises, but by a co-ordinated system based on principles fit to
>bring about the reforms required.

### A Parthian shot 1958

It has often been suggested by way of criticism that Fisher was a prominent proponent
of eugenics throughout his career, but 1943 was in fact the date of his last public
statement, by which time he had also detached himself completely from the Eugenics
Society. Yet when in 1958 Dover Books issued a ‘second revised edition’ of The
Genetical Theory of Natural Selection Fisher inserted a final paragraph to Chapter
VIII ‘Man and Society’:

>In the following chapters we shall examine, first, the objective evidence as to the magnitude
>and heritability of variation in human fertility; next, we shall consider the widespread evidence
>of its association with social class; and, finally, we shall put forward a theory of the selective
>process by which this association appears to have been established. On this theory it may be
>seen that its destructive consequences are not incapable of rational control.

It is a wistful reminder to us not to neglect an argument that had impressed him in his
youth forty-four years previously and which had drawn no scientific criticism other
than by denial of the existence of the effects of natural selection on fertility and
behaviour.

### Stephen Jay Gould’s criticism, 1996

The scientist and essayist S.J.Gould had a tilt at Fisher in ‘The smoking gun of
eugenics’ in his collection of essays Dinosaur in a Haystack (1996) thirty-four years
after Fisher’s death. To his credit he understood the Cobb principle, and he was fair in
stating ‘… I do not single out Fisher for any opprobrium on this score [eugenics]. The
great majority of geneticists advocated some form of eugenics, at least until Hitler’.
Fisher had ceased to be active in the Eugenics Society before Hitler’s war, and, as we
have seen, from 1943 and the Beveridge Report he showed no further interest in
population questions of any kind.

Gould’s attack took the well-worn path followed by many of simply denying
the existence of heritable components in behavioural characteristics, at least in man.
What came to be known as ‘sociobiology’ was not for them. Familial behavioural
characteristics, recognised as such for millennia long before the modern
understanding of inheritance, could not have a genetical component. The contrary
opinions of Darwin and his mendelian followers counted for nothing. Animal
analogies, indeed animal experiments, counted for nothing either. In The Descent of
Man (1871) Darwin was quite clear as far as ‘the intellectual and moral faculties of
man’ were concerned (it is striking how The Genetical Theory employs Darwinian
language such as this, even using ‘civilised’ and ‘barbarian’ as opposites): ‘These
faculties are variable; and we have every reason to believe that the variations tend to
be inherited’.

Five years later Darwin was to reply to a correspondent who had reported a
case of odd inherited behaviour in his family – and another in his dog’s family –
writing ‘The longer I live the more I come to believe in inheritance [of behaviour]’.

Today the academic left continues to hide behind the rejection of inherited
behavioural patterns (especially bearing on anything associated with intelligence and
ability) and Gould was no exception.

After four pages of exaggerated consideration of ‘the numerous false
assumptions that detail Fisher’s complex argument’ Gould delivers his verdict. ‘Why
should we assume that people who rise socially do so, in large part, by genetic
endowment?’ This is ‘quite unproven; but the second conjecture (a genetic basis for
fewer children in the upper classes) seems wildly improbable, even bordering on the
absurd’. Fisher, of course, did not say ‘in large part’ nor did he conjecture only ‘a
genetic basis’ for fertility. Gould concluded:

>We may take a kindly view of Fisher’s eugenics and say that his genetic conjectures did no
>harm, for, try as he might in press and before parliament, Fisher’s recommendations made no
>practical headway. But false genetic hypotheses of human behaviors and statuses are politically
>potent.

We can but agree with the last sentence also in the case where genetic influence is
denied, as in Gould’s Lysenkoism.

### Conclusion

Fisher’s youthful encounter (at the age of twenty-three) with J.A.Cobb’s theory of the
increasing association between social advancement and infertility as a consequence of
natural selection acting on the British population led him to propose a system of child
allowances to help share the costs of child-bearing and education more equally in
each level of society, to be met by the employer or professional association. He
argued that this would help to counter the reduced fertility in the upper reaches of
society (which at the time was below replacement level) and thus help to mitigate the
undesirable effect outlined by Cobb.

Fisher elaborated his proposal as the years went by, expounding it in papers in
The Eugenics Review and ultimately in detail in the second part of his great 1930
book The Genetical Theory of Natural Selection. It there attracted the qualified
approval of his colleagues the geneticists J.B.S.Haldane, Lancelot Hogben and Julian
Huxley, and by 1935 had become one of the ‘Aims and Objects of the Eugenics
Society’. In 1943 Fisher spoke against the system of flat-rate family allowances
proposed by Sir William Beveridge in his Report, while Beveridge argued against
Fisher’s scheme. Flat-rate child allowances won when Beveridge’s proposals passed
through Parliament.

Fisher ultimately tired of arguing but his 1958 addition to The Genetical
Theory quoted above shows that he held to his conclusion. It is instructive to note the
quotations with which he headed each chapter of The Genetical Theory, of which we
may repeat the one from Chapter VIII ‘Man and Society’ from Francis Bacon’s
(1561-1626) Of the Wisdom of the Ancients, here given in extenso but with Fisher’s
extract in italics (his wording is slightly different).

>SPHINX, says the story, was a monster combining many shapes in one. She had the face and voice
>of a virgin, the wings of a bird, the claws of a griffin. She dwelt on the ridge of a mountain near
>Thebes and infested the roads, lying in ambush for travellers, whom she would suddenly attack and
>lay hold of; and when she had mastered them, she propounded to them certain dark and perplexed
>riddles, which she was thought to have obtained from the Muses. And if the wretched captives could
>not at once solve and interpret the same, as they stood hesitating and confused she cruelly tore
>them to pieces.

