---
title: On the material supports of subjectivity
author: Fabrício Cardoso de Mello
---

Article in Social Science Information · July 2022
DOI: 10.1177/05390184221109772
CITATIONS READS
2 88
1 author:
Fabrício Cardoso de Mello
Rio de Janeiro State University
13 PUBLICATIONS 11 CITATIONS
SEE PROFILE
[This is the accepted version of a text published in 2022 in Social Science Information:
https://doi.org/10.1177/05390184221109772. Please refer to the published version for
quoting.]

## On the material supports of subjectivity: Mead, the self and the new mastery of nature

Fabrício Cardoso de Mello
Postdoctoral researcher (PNPD-CAPES), Graduate Program in Political Sociology – Vila
Velha University (Brazil)

## Abstract:
The pragmatism of George Herbert Mead has been fundamental to the sociological
understanding of the self. However, the complexity of his work is largely unrecognized in
the discipline. This mainly affects the way Mead intertwined discursivity with the
materiality of experience in his conception of human subjectivity. Through a
metatheoretical analysis, the present paper proposes a straightforward approximation
between Mead’s theories of the self and the act in order to contemplate the incidence of
processes encompassed by the latter upon the former. Based on this movement, and after a
dialogue with Francis Chateauraynaud’s pragmatic sociology, the paper suggests a new
Meadian-inspired sociological alternative to the concept of self, attentive to its material
dimension and centered on the concepts of outer and inner grasps. The current discussion
about the ontological politics in the context of a new mastery of nature allows for an
empirical exercise of the argument.

Keywords: George Herbert Mead; materiality; self; pragmatic sociology; risk

Introduction
The prominence enjoyed by the idea of interaction in the theoretical framework of
sociology is much indebted to George Herbert Mead’s pragmatist philosophy. His proposal
of a socially developed individual self (Mead, 1903, 1910, 1912, 1913, 1922, 1925, 1967
[1934], 2011 [n.d.]) has been taken by different approaches within the sociological
discipline as an axis for the solution of the polarization between structure and agency. The
communicative properties of interaction, which stand out in his discussions on social
psychology, have been pivotal in this aspect. However, sociology has underexplored the fact
that neither interaction nor the self are restricted to such properties in Mead’s work.

Although not focused directly or systematically on the topic of the self, his theory of the act
and his general discussion on the human perception of physical objects (Mead, 1912, 1926,
1932, 2011 [n.d.], especially 1972 [1938]), suggest that the material dimension of
experience is elementary for the self’s constitution and performance. The overall goal of the
present article is of metatheoretical nature, namely, to develop a Meadian-inspired
sociological alternative to the concept of self which is not limited to its internal and external
symbolic transactions, but which is also attentive to the material groundings of such
interactions.

The first section of the text sets the problem of the sociological undervaluation of
Mead’s concern with the material properties of the self. I analyze the form in which three
specific authors, Herbert Blumer, Jürgen Habermas and Axel Honneth were central for the
reduction of Mead’s complexity to his proposition of symbolically mediated
intersubjectivity as the pillar of the dynamics of socialization. A fourth scholar, Hans Joas,
partially departs from the problem, but still joins the others in a limiting view on the internal
composition of the self which, due to the wide reach of their readings of Mead, became
hegemonic in the social sciences. A counter-hegemonic understanding of the inner structure
of the self is addressed in the following section, which presents an internal reconstruction of
Mead that straightforwardly brings together his theories of the self and the act. It addresses
the issue of materiality in the Meadian act based on Markell’s reading of the concepts of “I”
and “me” (Markell, 2007) and puts into dialogue three different faces of Mead, which are
not systematized in his own work due to its fragmented characteristic: the Jamesian,
Deweyan and Whiteheadian ones. The purpose behind this move is to seek in Mead’s own
conceptual edifice the foundation for a conception of the self where the materiality of
experience plays active role in the construction of subjectivity.

The third and last section sets off seeking to empirically ground the previous
conceptual work. The social sciences have recently faced epistemological challenges set by
technological advancements in ventures such as biotechnology and geoengineering, which
promote what Pellizzoni (2015) has named the new mastery of nature. Based on new forms
of structural intervention in matter, these new technologies increasingly guide considerations
about the relations between nature, capitalism and risk towards an ontological dimension of
analysis. They also set the stage for renewed reflections on the intersection between the
material contact with the world and the production of subjectivity within contemporary
modernity. Accordingly, I draw upon the aforementioned metatheoretical endeavor in order
to tackle the vicissitudes of this new historical formation. My starting point for this task lies
in considering that Mead’s pragmatism is as important to detail the engine moving the
political ontology of this new relationship with nature as it is to build an inquiry critique
based on practical consequences as the most adequate criterion for judgement. In a decisive
point of this last section I signal the need for a sociological interlocutor able to back up
Mead’s material concerns, suggesting Francis Chateauraynaud’s pragmatic sociology, and
specifically his discussion around the concept of grasps (prises), as fit for this purpose. I
then settle my argument with a Meadian rendering of Chateauraynaud, advancing the idea of
the individual self as composed by inner and outer grasps. By taking such a step, on the one
hand, the operationalization of elements such as conflict, asymmetry and domination in
Mead is enabled, whereas, on the other hand, Chateauraynaud’s sociology benefits from a
valuable input for the construction of a pragmatics of interiority.

1. The neglect of Mead’s ecological view of the self in social theory and the
hegemonic interpretation of the “I” and the “me”
Not a sociologist himself, Mead’s incorporation into the discipline often relied on
the mediation of authors directly affiliated to sociology or with a wide margin of influence
over its academic field. Throughout the 20th century, symbolic interactionism and critical
theory provided decisive entry points for the “sociologization” of Mead, imprinting their
marks on the form which sociologists absorbed his concepts (Silva, 2007; Huebner, 2014).

In this section I draw a critical appraisal of four interpretations of Mead made by different
authors: Herbert Blumer (symbolic interactionism), Jürgen Habermas and Axel Honneth
(critical theory) and Hans Joas (linked to both critical theory and Chicago’s sociological
tradition). Notwithstanding notable differences among them, the first three authors converge
on what can be deemed as a problematic understanding of Mead’s conception of self, which
has as one of its outcomes the omission of the importance of materiality in his pragmatism.

Joas, on the other hand, hints at the direction for the solution of this problem, but does not
follow the path to the end, since he stands by the same limiting understanding of the
Meadian concepts of “I” and “me” as that of the other three authors.

It is worth discussing briefly some of the most substantial elements of Mead’s
thought about the social construction of the self and its communicative properties in order to
understand the role the aforementioned authors reserve for him in their own respective
works. By assuming an anti-Cartesian position, Mead does not consider the self as an
anthropological starting point but conceives it as the outcome of ecologically contextualized
communicative processes that evolve both phylogenetically and ontogenetically. Two
influences are central to him in this assertion: the integrating view that, by late 19th century,
Dewey (1896) launched over the concepts of stimulus and response in perception and the
relevance proposed by Wundt of the interchange of gestures as a foundational factor of
language (Mead, 1903, 1910, 1922)1. Mead locates the origins of the self in the conversation
of gestures among two or more individuals belonging to a given species in the animal world.

Such conversation sets stimuli and response circuits that coordinate the succession of acts in
the behavior of those individuals. The distinctive feature of the conversation of gestures in
human species lies on its qualitative remark supported by the development of a reflective
intelligence, or reflective conscience, capable of giving meaning to the expression of
attitudes through significant symbols (Mead, 1910: 178, 1922: 161, 1967 [1934]: 45ff, 90-
100). A gesture brings along a significant symbol “[...] when it has the same effect on the
individual making it that it has on the individual to whom it is addressed, or who explicitly
responds to it [...]” (Mead, 1967 [1934]: 46), whereas the origins of meaning lie on concrete
interactions throughout the course of communicative experiences among individuals, when
they mutually alter their responses by taking a specific goal as reference and reach a
substantial degree of symbolic unity (Mead, 1967 [1934]: pp.77-80).

One of the most relevant consequences Mead extracts from his idea of reflective
intelligence is that a gesture imprinted by an individual towards a companion of action, in
other words, a stimulus to the other’s response, already carries along the projective
anticipation of such a response, so that the uttering individual is also stimulated by its own
gesture. The extension of this dynamics opens room for the continuous process of reciprocal
1 In regard to Mead’s intellectual relations with Dewey, it is correct to say they both influenced each other
throughout their careers.

modification of gestures that structures the collective coordination of behaviors. By acting
this way, the individual continuously relies upon the attitudes that others address towards it
in order to become an object for oneself. In its turn, this subjective movement implies that
the individual also acts as the very subject of oneself by rebuilding its position within the
social act in a manner attuned to information provided by the world around to it (Mead,
1913: 379-380, 1922: 160, 1925: 267, 1967 [1934]: 135ff). We can observe, at this point, the
socialized nature of the self. It is constituted as a psychosocial structure with interactive
characteristics that expresses itself as an inner conversation, or forum, where both its
subjective and objective aspects take part in. It encompasses reminiscences acquired by the
individual actor through the environments it has experienced and the people it has lived and
communicated with, directly or indirectly, throughout its life. These elements work out as
raw material for the construction of this actor’s own individuality.

Mead’s social-psychological outline sketched above was taken by Blumer as the
main pillar of his symbolic interactionist approach. Blumer (1969) relies on Mead’s
discussion of the relation between mind, reflective intelligence and the significant symbol in
order to suggest that society might be seen as comprised by the interlinkage of symbolic and
non-symbolic interactions among individuals, and that sociology’s main task is to develop its
analytical work specifically focused on the former. This is so because, in his view, Mead’s
major legacy to sociology would be to portray society as constructed characteristically out of
the conscious organization of meanings found in the intersubjective relations of a plurality of
selves. For Blumer (1969: 23ff), therefore, “the obdurate character of the empirical world”
that repeatedly challenges the rigid models of the sociologist is marked by the contingency
and fluidity of the interchange of meanings that forms the core of people’s social
experiences.

Symbolic interactionism turned out to be a richly diversified sociological current,
unrestricted to Blumer’s own ideas and with different degrees of proximity to Mead’s
philosophy depending on each author (Joas, 1993: ch.1). However, it is notorious that over
the years Blumer acted not as an ordinary epigone, but as heir apparent and legitimate
interpreter of Mead, adapting his philosophical work to the language and empirical
methodology of sociology. His particular approach was key for the reception of Meadian
concepts in the American social sciences (Huebner, 2014: 158ff).

Although critical theory’s first generation was quite skeptical about the validity of
American pragmatism (Joas, 1993: ch.4), Mead’s social psychology was of great importance
to the theoretical synthesis developed by Habermas, one of the leading figures of Frankfurt
School’s second generation. Habermas found in Mead’s theoretical framework elements he
believed were capable of restituting the emancipatory potential of the concept of reason
within the universe of the German critique, since the pragmatist’s decentralized conception
of conscience allowed him to wander about a consensual social dynamics based on
cognitively and normatively justified actions. The Meadian concept of the generalized other
was essential for Habermas to locate the construction of legitimacy within the
communicative practices of the phenomenological concept of the lifeworld. In Mead’s work
(1922: 161ff, 1925: 268ff, 1932: 87, 1967 [1934]: 154), the generalized other refers to the
internalization of the structural organization of the attitudes of community by the individual.

Akin to Blumer, but with structural inclinations, Habermas (1987 [1985]: 37-44) sees in this
set of roles and expectations the key point of the production of norms, notwithstanding his
conclusion that Mead, in his own work, shied away from a satisfactory solution to the
problem of institutions.

Mead’s ideas are also an important reference for the architecture of Axel Honneth’s
theory of recognition, which sought a new reformulation of Frankfurt's critical tradition by
introducing social conflict as the driving force of historical transformation. Honneth saw in
the struggle for recognition the collectivized instance of the inner tensions of Mead’s self,
the ones deriving from conversations or discussions between its two phases. In a very
general way (to be further worked out shortly) we may define the“I” as the element which
corresponds to the self’s subjective facet and the “me” as the one which is correlated to its
objective facet (Mead, 1912, 1913, 1925, 1967 [1934], 2011 [n.d.]). According to Honneth’s
reasoning (Honneth, 2002: 502), by taking the reciprocity of recognition “[…] as the
individual evolution of a ‘me’ that consists in the consciousness of legitimate social
expectations, then the ‘I’ could perhaps be conceptualized as the source of continuous
rebellion against established forms of recognition [...]”. By resorting to Mead, Honneth
(1995 [1992]: 84-85) saw an opportunity to fill the motivational gap in Hegel’s theory of
recognition. The “I” would be a force behind demands for the extension of society’s
structures of recognition in favor of causes hitherto not incorporated by them, since it would
be a source of irradiation of individuals’ creativity that stands up to the conventionality of
the “me”.

What has been discussed so far allows the realization that the form through which
Blumer, Habermas and Honneth imported Mead’s thought does not make justice to it, since
they access his discussion on the self from only one of the angles available in his work,
namely: a social psychology concerned with the symbolic properties of the formation of
consciousness and communication. Hans Joas, another student of Habermas trained in the
Frankfurtian lineage, but who also established strong bonds to the Chicago tradition, shined
light on some consequences of this limited view of Mead’s thought. According to Joas
(1993: 137), Habermas’ restriction (also observed in Blumer and Honneth) of the Meadian
conception of social interaction at gestural language level is a “misunderstanding” that
would, furthermore, explain the assessment that a satisfactory discussion about the
institutionalized social order is absent in Mead. Not only would that be untrue (given Mead’s
concerns about democracy and science - Joas, 1993: 137, also see 1985 [1980]: ch.9; Silva,
2008), but the same interpretation puts aside other extremely important objects of Mead’s
philosophy.

As suggested by Joas (1985 [1980]: 145ff), there was never a border in Mead’s
writings between a world of action exclusively inhabited by humans and a world of non-
human beings and inanimate objects fully excluded from linguistic exchanges. For the
pragmatist philosopher, subjectivity and the production of meaning take place in complex
milieus where human behavior is engaged with entities of plural constitutions. This feature
evidences Mead’s connection to the strong naturalist profile spread over the pragmatist
environment of Chicago during the passage from the 19th to the 20th century (Dewey et al,
1945; Cefaï, 2001). Reflecting on the ethical implications of this environmental
characteristic of Mead, Brewster and Puddephatt (2016: 155) claim that his would be an
“ecological view of the self”, which becomes “[...] more expansive both by being
progressively more inclusive of diverse others [i.e. human and non-human] into our existing
groups and communities and by progressively identifying with larger groups and
communities [...]”.

By stripping Brewster and Puddephatt’s proposition of its moral aspect (however
relevant this is) we observe that an ecological view of the self also holds ontological and
cognitive grounds in Mead’s thought. We may return to Joas (1985 [1980]: 159-161) for a
relevant entry point to this argument when he recalls that, in Mead’s theory of the act (1932:
119-139, 1972 [1938], 2011 [n.d.]) the construction of the physical object by a perceptive
subject is socially mediated and linked to the apprehension of the unity of the subject’s own
body as the likely object of its action. However, Joas (1996: 181-184) does not move
forward in order to in-depth explore the questions this observation brings over the
constitution and maintenance of the self, and rather remains bound to the discussion about
the link between creativity and the formation of body image. By thinking both with and
against Joas I argue that, if a truly ecological treatment to the self should not be limited to
linguistic interchanges that substantiate human intersubjectivity, it must also not be
narrowed down to the mere valuing of corporeal elements linked to the interactive
experiences of individuals. It is essential investing in an integrative view between both
aspects, so we may contemplate the inseparability of the material and symbolic dimensions
in the continuous counterpoint between subjectivity and objectivity in the inner domains of
each individual.

In addition to the point highlighted by Joas about Habermas, which is extensible to
Blumer and Honneth, there are two deficiencies related to the form of appropriation of Mead
which can be claimed common to all these four authors. The first one regards the conceptual
selection they carried out in Mead’s work in order to integrate sections of it to their own
respective synthesis. The absence of the notions of problem and inquiry (both central to
pragmatism) in each of those four conceptual cores separates the theoretical analysis of the
self from the practical context of its formation, as well as from the (re)constructive work of
reflective intelligence in the course of continuous displacements between the worlds of
matter and meaning. I shall explore the relevance of this pair of concepts for the
reconstruction of Mead herein envisaged later (section two) in this article.

For now I will focus on the second common deficiency of the appropriation of
Mead by the authors discussed in the current topic, which rests on the interpretative
alternative that they followed regarding the inner structure of the self. It is implicit in Joas’
formulation that the maximum participation of materialility within the self occurs when the
material world itself is taken as object for the self’s action during the process of
consolidation of the bodily unity. Such a lack of consideration with the active role of
materiality in human action and subjectivity results from the interpretation of relations
between the Meadian concepts of “I” and “me” that was sanctioned by Joas and shared with
Blumer, Habermas and Honneth. Both the American and the German authors welcomed into
their respective theoretical works a problematic definition which largely reduces the “I” to
individual and the “me” to collective personifications within the self.

This specific approach to the roles of the “I” and the “me” in Mead’s self has been
called into question by Markell (2007) in the wake of a critique to what he understands as a
disabling feature of Honneth’s theory of recognition. The main line of his argument (Markell,
2007: 102-107) lies on the proposition that the definition of recognition as necessary crossing
point for the transformation of personhood from something potential to actual means the
submission of its self-realization to an external authority. According to Markell (2007: 112-
114, 125-128), this problem derives from the reifying reading of the “I” and the “me” that
Honneth made of Mead . Such an approach defines these two concepts as clearly different and
counterposed agencies. On the one hand, the “I” would encompass an irreducible
individuality, with nature similar to the unconsciousness of psychoanalysis and whose
contingency and creativity would represent the potential of renovation. On the other hand, the
“me” would be formed by a collective force, a habitual agent that is transposed from the
community to the individual in order to censor its “I”. Honneth would not be alone in this
interpretation of the Meadian self, for both Habermas and Joas would share with him the idea
that the “I” is “[...] something like a source or seat within the individual of creativity, novelty,
spontaneity, or resistance to social norms.” (Markell, 2007: 112-113, emphasis in original)2.

As pointed out before, Blumer’s understanding on the matter is not distant to that of the
Frankfurtians. While acknowledging an ambiguity in the form Mead used the two terms, the
sociologist sees the “I” as that thing that brings into the self “[...] expression and release to
organic impulse and tendency [...]” and the “me” as something that “[...] reflects the attitude
of the community [...]” (Blumer, 2004: 65-66).

For the purposes of the present discussion, the main problem with relating the “I”
and the “me” in this way is that it compromises the linkage between Mead’s social
psychology and his reflections on perception and the human engagement with matter present
in his theory of the act. The delimitation of the self to a symbolically mediated dialogue
between a radically individual agency and an interiorized force representing society (in its
minimal definition of a collective of individuals) rules out the incidence of the material
dimension of human experience on the production of subjectivity. If, as stated by Mead (2011
[n.d.]: 27), “the relations of the environment and the individuals is one of mutual influence.”,
2 Markell (2007: 112) recalls that for Habermas (1992: 180) “[...] the “I” appears on the one hand as the pressure
of presocial, natural drives, and on the other hand as the impulse of creative fantasy [...]” while for Joas (1985
[1980]: 118) it represents “[...] the endowment of the human being with impulses.”. Despite not identifying such
impulses with “[...] some natural compulsion [...]”, Joas (1985 [1980]: 118) sees them as unceasing individual
drives, finding “[...] expression in fantasies [...]”.

it is necessary to recognize that the interpersonal relations of the self traverse and are
traversed by constellations of physical entities. The expansion of the ecological view of
Mead's concept of self can contribute to a more complex and environmentally promising
version of his idea of subjectivity.

2. The materiality of the “I” at the confluence of self and act
2.1. – Actuality, materiality and the “I”
Blumer’s observation about the ambiguity of Mead’s utilization of the “I” and the
“me” in his own discussion on the self should not be overlooked. In fact, the problematic
understanding of the two concepts portrayed in the last section does not lay roots either in
symbolic interactionism or critical theory’s incorporation of Mead, but in Mead’s own
writings, on the polyphony he adopted to treat both concepts along his career. There are
basically two forms which Mead dealt with the dynamics of the “I” and the “me”. Later in his
work, the idea of counterposed individual and social agencies within the self predominates.

This version has prevailed in his canonization in sociology and sustains the hegemonic
interpretation of the Meadian self, as we have seen in the previous section. But another
interpretation of the conceptual pair, more aligned with the pragmatism of James and Dewey,
finds substance in Mead’s early discussions on the self (Mead: 1903, 1912, 1913)3. It is the
intent of the present section to show that this alternative, counter-hegemonic interpretation of
the “I” and “me” dynamics is more suitable for dealing with the material properties of
subjectivity and, therefore, to serve as starting point for a sociological reconstruction of Mead
concerned with an ecological conception of the self.

Some years ago, Markell (2007) took a stance adopted later by other authors (Silva,
2007: 106-107; Cook, 2013) and set forth a diligent rescue of Mead’s earlier conception of the
“I” and the “me”. More specifically, Markell has reclaimed Meads’ articulation (1903: 101-
102) between the original Jamesian formulation of the self, which is constituted by the pure
3 Mead clearly adheres to this approach in texts such as The Definition of the Psychical, The Mechanism of
Social Consciousness and The Social Self, all published during the two first decades of the 20th century. In
Mind, Self & Society, which is composed mainly of notes taken from Mead’s lectures in Chicago during 1928,
the two interpretations of the “I” and the “me” contents coexist. Markell (2007) and Cook (2013) explore the
contrast between them in detail.

ego (“I”) and the empirical self (“me”), and the proposition by Dewey (1896: 364) that
stimulus and response do not have separate and empirically definable contents, since they are
rather referentially composed and only distinguishable through the function they fulfill in the
coordination of the sensory-motor circuit.

In this specific formulation, Mead concludes that the self is a continuous encounter,
in the flow of the individual’s experiences, between subjectivity and objectivity as phases,
i.e. aspects4, of its understanding about the world and about itself. The self’s interaction with
the rest of the individuals’ internal and external experience field is particularly dynamic in
situations when uncertainties break that flow and disrupt the constitution of the object of
action, a process which Dewey has called “disintegration” (Mead, 1903: 101). Within this
individual innerscape, the subjective aspect of the self is given by the “I”, the “[...]
reconstructive activity [...]” (Mead, 1903: 109, emphasis added) responsible for the
emergence of new objects in action, which takes place in the “[...] very process of replying
to one’s own talk [... through] the gestures, the symbols, that arise in consciousness” (Mead,
1912: 406, emphasis added). Based on such a conception, the “I” is configured as the
transitive element of the “stream of consciousness” that links different objective experiences
and gives them a singularizing touch, a particular inward coloring that confers to the
individual a sense of existential continuity (James, 1955 [1890]: 159). Therefore, the “I” is
responsible for the subjective synthesis between an individual’s reflections and feelings by
generating a sense of unity and sameness that supports its personal identity (James, 1955
[1890]: 214-216). The “me”, in its turn, emerges as the objective aspect of the self, which
delimits, within this field of experience, the elements that can be (re)constructed as objects
to the individuals’ action through its assumption of the attitudes of others with reference to
oneself. Briefly, the “I” is the activity, the “actual response”, which is provided by the self to
a problem caused by the disruption of an object (Mead, 1967 [1934]: 277); the “me” is the
objectivity of experience introduced to the self when it assumes the attitudes of others
(Mead, 1967 [1934]: 175, also see Markell, 2007: 125-127).

It is important to distinguish Markell’s distancing from the hegemonic
interpretation of the internal structure of Mead’s self from the approach offered by Lewis
(1979). Like Markell, Lewis also opposes the assumption that the “I” is an organically
composed portion of the self with entity-like properties and, conversely, treats it as the self’s
4 Based on the Meadian vocabulary, the word “phase” does not necessarily regard a stage belonging to some
sequential teleological order. Its use is not different from that of the word “aspect” (Silva, 2008: 90-91).

form of response in communication. However, seeking what he calls a “social behaviorist”
approach of the self, Lewis points out that the “I” is the predominantly overt response, the
“[…] observable activity which is attended to by both the self and the other.” (Lewis, 1979:
269). He then offers an objectivist version of the “I” by basically excluding its presence in
thought and by wiping out the subjective core of intimacy envisioned by Mead’s early
writings from its response.

With traces of Dewey, one of the main effects of this counter-hegemonic
understanding about the inner structure of the self lies on the fact that only the roles played
by “I” and “me” can be respectively identified through exclusively individual and social
properties; their content, however, is interchangeable (Markell, 2007: 128; Cook, 2013: 121-
124). As suggested by Markell (2007: 128), Mead’s assertion that the reconstructive activity
of a present “I” ends up, retrospectively, integrating the objectivity of a future “me” (Mead,
1913: 374, 1967 [1934]: 174) also works in reverse. From this reasoning we conclude that
the adoption of the attitude of the other by the individual as its response derives from a form
of exercise, rather than necessarily from a drawback, of its individuality. The very act of
responding, whether with or against society, is a manifestation of the “I”. Consequently, the
same image or representation crossing one of the components of the “I”-“me” pair may
come to attend the other. The only variation in those elements will be observed in the type of
their functional participation in this reconstructive inner move, whether stimulus or response.

This approach is essential for us to understand the material dimension of the self. In
order to advance in this direction, it must be specified that, due to the social treatment Mead
gives to ontogenetic development, he sees the initial contact with the material world as the
consolidation of the intersubjective cognitive mechanism in the individual. The physical
object is the abstraction of the social object (Mead, 1972 [1938]: 190). Therefore, the physical
thing always enters the experience of a person through the resistance awakened by the friction
between that thing and the person’s physical organism. This resistance allows the
identification of something substantial in the object, which is not necessarily a personality,
but an interior, an “inside” that gives physical responses (thickness, roughness, rigidity…) to
the frictional stimulus that, in its turn, is transported to the self and assumed by it through the
objectivity of the “me” (Mead, 1972 [1938]: 109-110, 143-144, 152, 186-187, 191-196, 212-
213, 429-431). Devoid of communicative capacity, the resistance provided by the physical
object to the human body is the equivalent to its voice in the Meadian interactive structure, so
that we talk with things through their ledges, crests, and folds. Resistance also implies
cooperation (Mead, 1972 [1938]: pp.108-110). Therefore, by drawing upon a vocabulary
influenced by contemporary pragmatic sociology, I can state that, in affinity with Mead, the
self is not only buttressed by conventional supports of action (Dodier, 1993), but also by
material supports that are brought to its inner realm in the course of its interactions in a world
full of physical objects.

Once inside the individual’s inner constitution, sensations caused by material
supports interact with the universe of language and stir up representations and images
stocked in a repertoire of memories built from past experiences: “The image, functionally
defined, is then a content that, in terms of past experience, has served as a solution of the
problem set in the form of the sensation” (Mead, 1904: 605, also see 1912). By standing
before the ecological composition of the problem it faces and the updated version of its self
(which is likely the carrier of a new, previously absent, memory), the individual’s response
(which exercises the singularity of its “I”) can give rise to new images, i.e., new symbolic
interpretations of those materially experienced sensations. My point in here does not lie on
the precedence of materiality’s magnitude in comparison to the symbolic dimension of
Mead’s pragmatism. I rather shine light on the way Mead is sensible to the reciprocity
between the material and the symbolic. Significant symbols and physical resistances meet
each other through the communicative work of thought, so that symbols find ballast in
material supports and physical resistances acquire meaning from conventional references.

The discussion indicates that creative action benefits, on the one hand, from the
situational variability set by the flux of experiences and, on the other, from the
reconstructive work of the “I”-response, which expresses the individual’s volitions and goals
in the space between an old reality that became obsolete, and a new reality yet to be defined
(Mead, 1972 [1938]: 34-35, 115). By associating the “I” and the “me” with the creativity
found in the resolution of problems set by interactions between people and things, we get to
the vertex between the theories of self and the act.

A few systematic words about the act are relevant at this point. Its substantial
elaboration is found on The Philosophy of the Act, which is a posthumous compilation
composed of writings where Mead was under the advanced influence of Alfred North
Whitehead’s objective relativism. The act is an activity of practical ontology wherein human
beings socially set the sense of reality by means of the convergence between their signifying
abilities and the material properties of the natural world throughout a spatiotemporal axis.

Mead analytically distinguishes the act into four phases: 1) impulse, when sensations
experienced by the individual start the first levels of the construction of a response that lasts
the whole trajectory of the act; 2) perception, when, at distance, the object occupying the
center of the act starts to be outlined after being associated with that initial sensation; 3)
manipulation, when distance gives way to contact and a conscious analysis is exerted over
the object; 4) consummation, when the construction of response is concluded and brings
along a qualification cast upon the object (Mead, 1972 [1938]: ch.1).

The different stages of the act encompass the previously mentioned concepts of
problem and inquiry. By drawing upon Dewey’s idea about the disintegration of the object,
Mead (1972 [1938]: p.6) defines the problem as the “[...] lack of adjustment between the
individual and his world”. It occurs in the context of the act due to the development of the
incompatibility between the response provided by the individual and the demands it deals
with after receiving a given stimulus. This situational mismatch breaks the flow of the act.

The reconstructive work that starts at this point follows the inquiry form, which
experimentally analyzes data about the problematic situation in order to reduce incongruous
or ambiguous information, to formulate new hypotheses for the solution of the problem, and
to test such hypotheses by checking whether the paused act has been restored, or not (Mead,
1972 [1938]: 82-83; also see Cook, 1993: 177).

A displacement occurs within two gradients throughout this inquiry. The first
gradient is related to spatiotemporal proximity, as the examination of an object, whose initial
stimuli are always felt at distance, depends on direct contact with the inquirer for effective
experimentation. The second one concerns cognitive formality, as individuals move from a
spontaneous relationship with the world around them, which Meads calls immediate
experience, to the rationalized attitude of a reflected analysis, when conscience is already
oriented towards the manipulation phase in order to experimentally test the components of
the problem at hand (Mead, 1932: 133-139, 1972 [1938]: 13-16).

These two movements influence the inner configuration of the inquirer’s self as it
goes through different situations. The objective stimulation (“me”) and the response (“I”) are
gradually defined throughout the double displacement caused by the inquiry in the course of
the act, from its initial stage (when immediate experience prevails) to the full establishment
of reflected analysis (which takes place in manipulation). When reflected analysis is
accessed, self-consciousness and awareness about objects adjacent to the self, which are
based on a rationalized form of problem appreciation, are quite well-focused. At
phylogenetic level, obtainment of rational problem solving does not result from the rupture
with a state prior to conscience, but unfolds from it, in a dependent fashion, following the
emergence of the significant symbol (Mead, 1922: 160, 1925: 271, 1967 [1934]: 68-82;
Silva, 2008: 121-122). When it comes to the individual level, the theory of the act suggests
that, as soon as the basis of one’s self is formed, the expression of the analytical reflection
about an object in the field of experiences is situational and progressive, so that there is no
interruption in thought, but continuity between rationality and the most intuitive forms of
engaging in the world. Thus, we observe that the reconstruction of external data sets the “I”
and the “me” in motion, and that this process will reflect on the interior domain of the self.

The self as inquirer also reconstructs its own inner constitution through its relations with the
objects around it.

2.2. Perspectives and prehensions
In the transactions with the world sketched above the individual only has access to
the common ground of reality through its own perspective. The idea of perspective has
noteworthy presence in the work developed by Mead in the last decade of his life. Its
mobilization represents Mead’s attempt to combine his pragmatist naturalism to the
relational metaphysics of Whitehead (Mead, 1925: 259-260, 1932: 161-163). In a quite
concise fashion, a perspective can be defined as the product of perception spatiotemporally
originated from a percipient event that finds itself in relation to a consentient set, i.e., an
environment comprising relevant objects concerning the existence of that perceiving entity
(Mead, 1925: 256, 1932: 161-175, 1972 [1938]: 100ff). Different perspectives developed
throughout the act are concentrated either in a prospective unity, as the promise of a future
trajectory, or in a retrospective manner, in the consummation phase, when the act acquires
evaluative character (Mead, 1934: 162, 1972 [1938]: 134). After all, reality is the product of
a relational organization of perspectives, and individual human subjectivity is part of
nature’s objectivity because it is a concrete datum produced within the interchange of
organism and environment (Mead, 1972 [1938]: 163).

Mead’s borrowing of the concept of perspective is essential for the present
articulation of his theories of self and act. As we know, the philosopher points out that the
self benefits from inquiries conducted by the individual on its own inner affairs and
problems, which are intersubjectively developed throughout relations with the external
environment (Mead, 1913: 378-379, 1967 [1934]: 38, 97-100, 119-124, 177, 188, 216, 254,
274-281, 308, 376, 1972 [1938]: ch.1, 5). Conversations internal to the self sustain thought
as a reconstructive activity enabling the individual to set up the self-perspective that defines
its singularity (Mead, 1967 [1934]: 254, 308). Thus, Mead (1925: 259-260) understands that
“[...] each individual has a world that differs in some degree from that of any other member
of the same community, [and] that he slices the events of the community life that are
common to all from a different angle from that of any other individual.”. The angles
provided by the perspectives of each percipient event produce a stratified reality that
comprises nature itself (Mead, 1932: 171).

By taking part in continuous processes of relational entanglement of viewpoints that
comprise nature, the self has to deal with the material dimension of perspectives from a whole
set of entities it interacts with in space and time. The articulation between the concepts of
perspective and prehension in Whitehead’s philosophy helps us better understanding
materiality’s relevance for the internal construction of individuality in Mead’s work.

According to Whitehead (2011 [1925]): 86, 1978: 18ff), prehension is a mode of perception
that takes shape through apprehension, whether cognitive or not, of a given actual entity over
another. We do not find in it a simple extension of a being over another, or even an aggregate
formed by the sum of two, or more, entities. In the formation of a prehensive unity,
Whitehead (2011 [1925]): 81) sees the transperspective complexity of reality with the
interpenetration of aspects among all beings composing a totality. Yet, due to its “vector
character” (Whitehead, 1978: 19-20), prehension is the form through which an entity can
extend itself to others, involve and be involved by them and express its singularity to the
external environment. In short, there is no individuality without interdependence between the
different perspectives observed in the same universe.

In Mead’s work, aside brief mentions in The Philosophy of the Act (1972 [1938]:
147, 202), there is a relevant reference to the concept of prehension in his essay The Objective
Reality of Perspectives, published originally in 1926 and later compiled in The Philosophy of
the Present. In such reference, Mead makes it clear that, from his view, the way how
individuals deal with the common environment cannot be separated from the perspectives
they built over themselves within their inner scopes:
The consentient set is determined by its relation to a percipient
event or organism. The percipient event establishes a lasting
character of here and there, of now and then, and is itself an
enduring pattern. The pattern repeats itself in the passage of events.

These recurrent patterns are grasped together or prehended into a
unity, which must have as great a temporal spread as the organism
requires to be what it is, whether this period is found in the
revolutions of the electrons in an iron atom or in the specious
present of a human being. Such a percipient event or organism
establishes a consentient set of patterns of events that endure in the
relations of here and there, of now and then, through such periods
or essential epochs, constituting thus slabs of nature, and
differentiating space from time. This perspective of the organism is
then there in nature. (Mead, 1932: 162, emphasis added)
Because it is a perceptual apprehension that is not reduced to cognitive intercourses
between entities, prehension immediately refers us to processes of contact present in the flow
of Mead’s act, from the impulse phase to the consummation phase. However, the excerpt
above indicates that, according to Mead, by apprehending objects through such a process, a
subject is simultaneously setting in motion the prehensive unit of its own self. This unity is
built through the interaction of the individual with its consentient set, as different response
patterns (elaborated in the interaction between “I” and “me” and later translated into a new
mnemonically reconfigured “me”) are temporally accumulated and “grasped together or
prehended” as the continuity of its being. This takes us back to James’ influence upon Mead’s
initial phase, in particular to the proposition of personal identity as the subjective synthesis of
experiences. By dialoguing with this reference it is possible to see in the context of interior
problematic situations the “I” and the “me” engaging in a process of inner prehension, in
which each of the two elements strives to seize the other from their own perspective, the
result of this transaction being the personal configuration of the self. This means that the self
derives from the crossing of perspectives between subjectivity and objectivity in the context
of mind, where the “I” and the “me” seek to grasp one another 5.

By looking at this topic through such lenses, excerpts where Mead states that “The
active individual [the “I”] finds in this object individual [the “me”] and its world the
conditions under which its action may take place” (2011 [n.d.]: 31, emphasis added) can be
interpreted as indicating the possibility that material supports from the field of experiences
contribute to the consolidation of the posture of the “I”-response in the temporal flow, not
5 The conception of “I” and “me” as perspectives is also present in Bolton (1981). However, while I follow
Whitehead’s definition of the concept, Bolton (1981: 249) suggests a simplified version of perspective as “[...]
a symbolically organized mode of orienting oneself toward a situation [...]”.

only to the configuration of a “me” an organic and naturally individual “I” presents itself to.

If, as suggested by Markell, the subjective self encompasses in its transitivity the generalized
social attitudes brought along by the objective self, it does the same thing with the material
impressions left by contact with physical objects. Matter is not simply an input that passively
receives directions from the individuality of the self; it effectively acts upon this individuality,
by influencing it through the game played between resistance and cooperation, which is
especially observed in manipulation. The transitive state of the stream of consciousness
composing the “I” can be supported either by the representational, imagistic and normative
conventions of social relations or by the physical contours of the world in order to give its
touch of singularity to the self. We seek and take hold of the perspective of an object,
prehending its “inside”, just as we seek and take hold of the other in social conduct during the
making of our own behavior. The ledges of things are as important for the definition of the
response of the “I” in the subjective conformation of our actions as the social expectations of
our human peers: “By acting as the object will act [...]” says Mead, “[...] we realize the
hardness of the object and do not run our heads against it.” (1972 [1938]: 107). We conclude
that matter takes part not only in the formation of an individual’s corporal self-image, as Joas
points out, but also in the entire introspective process of problem solving that feeds its self-
understanding. As Mead himself has stated (1926: 382), that object we lay our hands over is
turned into a material to build the world of our heart’s desire and dreams.

The interpretation built throughout this section made Markell’s rescue of the
pioneer version of “I” and “me” meet Mead’s Whiteheadian reflections, and from there
extracted the newly proposed approach of the material supports of the self. In important
points, it contrasts with the view defended by Rosenthal and Bourgeois (1991). These
authors have accessed Mead’s work by making the effort to make him closer to Merleau-
Ponty (Rosenthal and Bourgeois, 1991: 103ff). In their theoretical convergence, they do not
adhere to the counter-hegemonic definition of the “I” and “me” concepts, and it leads them
to two important mistakes. Firstly, according to Rosenthal and Bourgeois, “I” and “me” do
not fully take part in the reconstructive process of the problematic experience, because the
disintegration of the object would also cause the transitory disintegration of the relationship
between these two components of the self. During the first moments of reconstruction, the
individual would only count on the fundamental subjectivity of the “concrete subject” and
on its “lived body” (Rosenthal and Bourgeois, 1991: 106), notions taken by the pair of
authors from Merleau-Ponty as sources of bodily intelligence. Secondly, because Rosenthal
and Bourgeois do not assume the “I” as intrinsically associated with the response activity,
they do not see the complex, continuous and incremental relationship between its role in the
structure of the self and the material supports of action. According to them, “I” and “me”
only return to the scene after the establishment of conscious reflection, and in there they are
added to the dynamics of the concrete subject, which lasts and mediates the interactions of
the self with the environment. The continuity of the concrete subject within the self is what
would guarantee its exchange with the physical world in a process taking place through a
non-thematic internal dialogue wherein the “I” would be experienced, felt as the background
of mind, but not made explicit as an object of knowledge (Rosenthal and Bourgeois,
1991:113, 115).

This last proposition about a non-rationalized instance in thought actively
contributes to the procedural treatment of the Meadian self, which has been designed
throughout this paper. Nevertheless, it is worth inquiring: is the deviation through Merleau-
Ponty necessary in order to achieve it? My answer is no, and its elaboration helps correcting
the two aforementioned problems regarding Rosenthal and Bourgeois’ approach. If we recall
the image of the self moving along a gradient of cognitive formality, we observe that the “I”
and the “me” are involved in the reconstructive process from its very beginning, when
immediate experience prevails. It is at that very moment that both elements express
themselves in a non-thematic (following Rosenthal and Bougeois’ denomination), non-
symbolic (Blumer, 1969: 8) way or, yet, from another viewpoint, in the manner of what
Giddens (1984: 44-45) has called practical conscience, which is found in “[...] circumstances
in which people pay attention to events going on around them in such a way as to relate their
activity to those events” without, however, “thinking” about what they are doing. In
reflective analysis, however, our relationship with the objects grows towards transparency
and although still not turned into a theme in direct experience, the “I” finds itself in such
circumstances able to support more refined ways of response. We can extract from this
reasoning that what Rosenthal and Burgeois attempted to describe by resorting to the
external notion of concrete subject can be reached within Mead’s own conceptual universe
through the articulation between his theories of the self and the act. Therefore, we
understand that, similarly to the symbolic dimension, the material dimension of experience is
also part of the prehension of human subjectivity in its different degrees of rationality and
intentional clarity, and that it is found both in the objectivity of the “me” and in the
reconstructive activity of the “I”.

3. The self, pragmatic sociology and the new mastery of nature
Different currents of contemporary social theory have recently converged to the
appreciation of the ontological dimension of interactive partnerships between humans and
other beings. References to an ontological politics (Mol, 1999) or to new materialisms (Coole
and Frost, 2010), although quite different from each other, share as common orientation the
understanding that definitions of reality are productions traversed by conflicts, disputes and
effective transformations. The current section argues that Mead’s pragmatism, mainly his
theory of the self as herein reconstituted, offers relevant contribution to the discussion about
the ontological twist in the forms of power in contemporary modernity. Furthermore, as
announced in the introduction, the theoretical exercise developed throughout this article is
aimed at an empirically grounded sociological concern which finds fertile soil for research
and reflection in discussions about ontological power. Therefore, in addition to discussing the
issue through a Meadian outlook, I will also seize the opportunity to explore in the following
pages a new sociological alternative to be integrated into Mead’s conceptual perspective.

My starting point to deal with these ontological issues is the study by Pellizzoni
(2015) about recent reconfigurations in the neoliberal mode of mastery over nature, where he
expands previous reflections by Cooper (2008) about the entanglement of knowledge,
biotechnology and financial capital6. Pellizzoni describes a paradigmatic shift in the political
and economic discourses of capitalism beginning in the 1970s. At that time, the sense of a
natural limit to growth was progressively replaced by the proposition of the inexhaustibility of
opportunities provided by nature. This new discourse appropriates diagnostics about the
complexity of the biophysical world resulting from different sectors of the scientific
community and from ecological movements to highlight certain features of environmental
processes, such as indetermination and instability. It then generalizes these features in positive
manner and depicts the unpredictability of environmental systems as a whole set of
possibilities, rather than interdictions, for the fulfillment of human designs. The principle of
precaution is then neutralized by the ontological reach of purposeful action, since the attitude
to be taken towards risk is not its reduction, but the refinement of interventions in the
6 See Pellizzoni (2015: ch.1) for a comprehensive critical appraisal of post-constructivist/anti-humanist
approaches to ontological politics, which are not the focus of the current article.

biophysical world. The investment in the figure of indetermination in this new form of
mastery over nature reinforces the imaginary of plasticity of reality (Papadopoulos, 2011),
which is taken to its last consequences by technological fronts such as geoengineering and
biotechnology.

Pellizzoni dialogues, at important aspects, with Boltanski and Chiapello’s (1999)
idea about a new moral foundation rising from the establishment of neoliberalism. These two
authors suggest that capitalism has overcome the crisis of its industrial period by
reconfiguring itself through the cooptation of an artistic critique. Present in several political
and cultural movements at the late 1960s, this critical modality used to substantiate demands
for mobility, adaptability and, most of all, for flexibility. Once the principle of flexibility was
integrated as resource in the entrepreneurial world, the critique that used to call for it was
disarmed to a large extent. Pellizzoni (2015: 66) himself points out his affinity with this
argument; however, I herein further explore this link by assuming his idea of a new mastery
of nature as part of the new spirit of capitalism proposed by Boltanski and Chiapello. Thus,
the definition of matter as undetermined source of possibilities, broadly flexible and
responsive to human projects, seems to result from a surreptitious response from capitalism to
critiques coming from both complexity theorists and ecological movements that, since the
1960s, have drawn attention to the irreducibility of nature to the economic, political and
epistemological ventures of that regime. Hence, it can be stated that the capitalist
reconfiguration promoted by neoliberalism relied not only on moral supports, as Boltanski
and Chiapello have suggested. We find in it the articulation between conventional and
material supports in the reformulation of a normativity about the relation between human
activity and nature.

The ideological reorganization that has promoted this flexibilization of nature in the
wake of the formation of a new spirit of capitalism brought to light a new object to human
experience. As shown by Mead, this is not sustainable without concrete supports. The
neutralization of ecological critique did not occur despite the complexity of nature claimed by
scientists and activists, but it precisely resulted from its recognition, since it contributed to the
perception about the limitations of the typically industrial form of exploration in face of
environmental resistances imposed to human manipulation. The adherence to complexity in
the neoliberal layout had the double effect of sophistication of economic interference in
nature, on the one hand, and the political emptying of critique (at least to some degree) on the
other. Therefore, the development of the new technologies mentioned by Pellizzoni, which
also include the ones related to carbon markets and human enhancement, did not happen
simply throughout projections of pre-elaborated business models over the biophysical world.

Their designers engaged in inquiries that sought analytical contact with the profusion of
attributes composing the materials in the center of their attention. By manipulating these
objects, they intended to reach their interiors, assume their perspectives and, thus, access the
complexity of their constitutions. This means that they understood the ideas by authors such
as Morin (2008: 5), about the relationship between knowledge and the environment, but they
actively sought to neutralize the critical inclination of such theories in favor of elaborating
more creative and efficient forms of extracting economic value from nature. In other words,
they relied upon the manifold material supports of nature in order to master it.

Accordingly, material resistance has acted incisively in the perspectives either of
critiques of the industrial mastery of nature and of its reformers. However, materiality does
not express itself alone in symbolic mediated social relationships. The concept of complexity
was the consummatory, representational form with which this resistance was consolidated as
object. But, as we have seen, power relations have marked this adjustment of perspectives
between the material world and human agencies. Clear asymmetry is established between
these perspectives, because, even if the critical interpretation of complexity keeps on
operating, its reformulated version as inexhaustible basis of economic exploitation has all the
systemic, institutional and moral support of the new spirit of capitalism.

Before I tackle the problem of asymmetries, I shall draw new, pragmatist bases for
Pellizzoni’s critique to the new mastery of nature. Based on Heidegger, Pellizzoni (2015:
156-157) defends a fundamental split between being and “thinking”, ontology and
epistemology, as the source of the singularity of human existence. Consequently, the new
technologies approached by his reflection would be worrying not so much due to the results
of their activities, but mainly because they would push the leveling between matter and
knowledge. From this viewpoint the corruption of the essence of the human as resident of
the world is strengthened, and it leads up to an “[...] instrumentalization of everything
[natural] as standing-reserve, governed by relations of efficient causality [...]” (Pellizzoni,
2015: 153).

Through pragmatist lenses, this line of reasoning is not satisfactory. In the first
place because, as seen in the discussion about the symbolic and the material in Mead, for
pragmatism both knowledge and matter belong to the domain of practice: thinking is itself a
way of acting upon the world (Frega, 2006: 39). Secondly, because it reverses the order of
construction of critique (MacGilvray, 2004: 104; Frega, 2006), since its justification is based
on the non-contemplation of a principle, in this case, the anthropological proposition of
discontinuity between humanity and nature. In order to repel this form of idealism, Dewey-
inspired pragmatism, to which Mead was affiliated, emphasizes the need for critique to be
experimentally constructed. Critical endeavor should be based on assessments of the
consequences of a problem, since the very meaning of the critique’s object is dependent
upon such consequences for its process of signification (Frega, 2006: 62-65).

The consequences of the new technologies must therefore be the aim of critiques
directed to the new mastery of nature. Critical constructions should not aim from the
beginning at one-size-fits-all considerations (such as Pellizzoni’s), but instead should
proceed modestly in a path guided by inquiry work (Chateauraynaud, 2018). The literature
on biotechnology and geoengeneering points out some outcomes of such technologies which
are relevant for a critical exercise that sticks to practical consequences as the starting point of
judgment. Authors from different, albeit critical, theoretical affiliations (Cooper, 2008;
Szerszynski et al, 2013; Demeulenaere, 2014; Pellizzoni, 2015), indicate that the progressive
transfer of ontological control from ordinary entities (human or not) to the benefit of power
systems that create and administer these technologies is one of the most prominent
developments set in motion by both strands of innovation. Inspired by Mead and his
Whiteheadian moment, by ontological control I mean the capacity an entity has to apprehend
its own constitution as a being in relation to its consentient set and, in the case of humans, to
actively inquiry and evaluate objects, including one’s self. Intrinsically linked to the
regeneration of the market that has emerged after the global crises of the 1970’s, the new
mastery of nature propels a gradual colonization of experience by the economy at “[...] the
genetic, microbial, and cellular level, so that life becomes, literally, annexed within capitalist
processes of accumulation.” (Cooper, 2008: 19).

However, if Mead did not fully disregard the subject of power, it is true that his
liberal normativity has limited his view to dialogical forms of conflict resolution (Silva,
2008: ch.15). Regarding this problem, it is essential extending to Mead the observation by
MacGilvray (2004: ch.5) about the Hegelian “extrapragmatic roots” of Dewey’s political
theory. Similarly to Dewey, Mead understands that the democratic dynamics of collective
life is organized by the teleological harmonization of individual orientations, and that it takes
place through communicative processes that integrate the multiple selves into their
communities. There is insufficient room in his work to the discussion about inequality,
violence and domination, which comes about the reduction of autonomous space for the
production of perspectives in favor of hegemonic apprehensions.

This characteristic of Mead’s thinking emphasizes the difference between his social
philosophy and an empirically oriented sociological approach and casts light upon the value
of endeavors made by the authors present in the first section of the paper in order to remold
the pragmatist’s conceptual force with sociological design7. As we have seen, however,
those theoretical constructions suffer from problems which inhibit a satisfactory account of
the self according to the ecological view guiding the present study. A final step in the
reconstruction of Mead put forward by this article then lies in the task of finding a new base
to synthetically house his perspective in the sociological discipline. After ruling out the most
prominent options I suggest that a particular approach within contemporary pragmatic
sociology, the one advanced by Francis Chataeauraynaud, presents itself as a promising
candidate. In addition to his participation in pragmatic sociology’s active claim of classical
pragmatism’s legacy in the beginning of the 2000’s (Chateauraynaud, 2004),
Chateauraynaud’s theoretical work stands out for highlighting the intertwining between
discursivity and materiality in the conduction of inquiries of both ordinary and expert profile.

In order to fill the Meadian gap on violence and domination, I shall introduce the
concept of ascendancy (emprise) as understood by Chateauraynaud (2015, Chateauraynaud
and Debaz, 2017), in the context of his approach to Foucauldian bio-power from the
standpoint of pragmatic sociology. What Chateauraynaud defines as ascendancy is an
intense form of asymmetry, non-hierarchical, diffused through networks, based on
legitimacy and realized by the way of the biasing of actors’ perceptions (Chateauraynaud
and Debaz, 2017: 235). An actor gains ascendancy over others by indirectly influencing their
behavior, by conquering their “territories of experiences” (Chateauraynaud, 2015: 9), and,
finally, by managing the conformation of problems that are elaborated there, as well as the
flow of inquiries conducted to solve them. This discussion is substantiated by the concept of
grasps (prises) observed throughout Chateauraynaud’s work. By drawing upon it, the author
explores the ontoformative power of convergences between representations and material
7 Mead’s image as an armchair philosopher is not accurate, for he was not entirely distant from empirical
practice (Huebner, 2014: ch.2-3). However, he never devoted himself to the elaboration of a specific
methodology for empirical social research.

perception (Bessy and Chateauraynaud, 1995; Chateauraynaud and Debaz, 2017: 606-607).

Grasps are products of human agency in its attempt to elaborate definitions over objects and
processes in a universe that is as material as hermeneutical.

It is relevant to point out the proximity between the concepts of grasp and
prehension, as well as the scarce presence of Whitehead in the work by Chateauraynaud,
which also holds true regarding Mead (Mello, 2019: 173)8. In the present article I address the
confluence among Mead, Whitehead and Chateauraynaud in order to propose that the
processes encompassed by the concept of prehension must be incorporated by the concept of
grasp. This is, accordingly, the centerpiece of the synthetical movement bringing together
Mead and Chateauraynaud. At this point of the article, I must introduce an analytical
distinction between inner and outer grasps9. The basic difference between them is
determined by the object of each one: in the former, internal affairs experienced by an actor
are the main object, while in the latter the object lies outside the actor’s innerscape. In
empirical reality a clear distinction between inner and outer grasps is not possible. We may
think of them as interchangeable and communicable analytical perspectives, one directed to
the study of problems and inquiries within the courts of the self, the other focused on social
and environmental problems which different selves take part in.

When it comes to human reflexivity, outer grasps are processes of ontological
characterization of objects the actors interact with in their environments. Their existence
implies the operation of inner grasps, because the same interaction promotes, at a greater or
lesser degree, the reorganization of the self through the “me” and the “I”, which are
responsible for conducting into interiority the material and conventional supports at stake in
the resolution of the experienced problem and for the manifestation of the active element
responsible for the personal mark in the subject’s response, respectively.

Inner grasps are in motion when the individual presents itself as its own object,
when its own self occupies the center of the problems and inquiries it experiences at a given
moment. On such occasions, the greatest test put to the self lies on coping with the problem
rising within the “enduring pattern” shaping the individual, to grasp issues affecting its
8 Indeed, this similarity is suggested by the long excerpt from Mead quoted above. We may elaborate from it an
image of prehension as the gripping movement of a hand that tactfully affords a sense of continuity between
what is sensed in one of its regions and what lies in its opposite area.

9 See Mello (2017) for the initial definition of inner and outer grasps regarding collective subjectivities.

Besides concentrating on individual subjectivity, the present article dives much deeper in Mead’s work in
order to substantiate the pair of concepts.

inmost sphere by the “lasting character of here and there, of now and then” built along its
biographical trajectory. Referring back to the Jamesian Mead (1903; James, 1955 [1890]:
213ff), we may state that, by holding an inner grasp, a person is apprehending its scope of
memories, expectations, ideas, emotions, perceptions, and actions, whether they are
informed by material or conventional supports, in a specific perspectival conformity that
maintains its sense of intimacy and inner correspondence along an ever-changing relational
existence with itself and the environment. Not only grasps over external objects, i.e. outer
grasps, are compromised in contexts of ascendancy. Inner grasps are loosened, one’s
ontological control over its own self is weakened, and an asymmetry is installed to favor
other parties. Chateauraynaud’s sociology benefits from this procedure by accessing stronger
terrain in order to deal with transactions between subjectivities and externalities sustaining
generative existential processes. By taking this step we enable the concept of grasp to work
as the existential pillar of a pragmatic sociology of interiority10.

Two important topics must be addressed regarding this Meadian-inspired
formulation of the inner grasp. The first one is related to the compatibility between synthesis
and disruption in the work of the “I”. The “I” may act as a disruptive force as the individual
sees itself from a new angle during the self-inquiry engaged by it in the context of a
problematic experience. However, a synthetical movement still guides it, as it seeks to leave
behind the existential discomfort set in place once a problem has been established. Thus,
disruption has to do with the contrast between the contents mobilized in the course of self-
inquiry and the initial frame of the problem one is experiencing11.

The second topic complements the first and resumes the issue of the tension
between the “I” and the “me” as approached towards the end of the previous section. As
stated at that moment, both phases strive to grasp each other in the context of inner
problematic situations. Chateauraynaud’s pragmatic sociology brings substance to this
10 In sociology, Thomas and Znaniecki (1918-21) were pioneers in developing a biographical analysis of the
individual “life-organization” inspired by the legacy of pragmatism. Strauss (1959), in his turn, clearly borrowed
the pragmatist conceptions of problem and inquiry (although without explicit reference to them) for analyzing
self-identity through his discussion of “self-appraisals”. Corrêa (2021) has similarly followed this path recently,
also proposing a dialogue between classical pragmatism and contemporary pragmatic sociology.

11 Some complementary observations on this topic: 1) By “existential discomfort” I mean a form of
dissatisfaction untied to any specific state of emotion. In light of this, peace, stillness and joy may be sources of
existential discomfort just as unrest, suffering or misery; 2) given 1, by mentioning a movement away from such
discomfort I evidently do not rely on the structural-functional argument of a constant human necessity of
stability and social conformation, as conformation itself may be the cause of discomfort in the first place; 3) the
synthetical movement set forth by a problem is not rectilinear or predictable; 4) because of 3, the exercise of a
synthetic movement does not guarantee at all that a reconstruction will come to term, since a person may found
itself in a continuous process of self-search without ever achieving a stationary solution.

discussion. With his version of the concept of tests (épreuves), pervasive in pragmatic
sociology, Chateauraynaud (2004: 169) invites us to think that the disintegration caused by a
problem can not make disappear entirely the material and symbolic properties of beings
involved in it. This reasoning is fully in line with Mead’s theory of the act. We may then
assert that in order to conduct reconstruction and (re)gain an inner grasp, the “I” must deal
with both cooperation and resistance offered by elements in the objective phase of the self.

In order to grasp oneself, a person must go through tests whose content is linked to the
configuration of the problematic experience12. It is the result of these tests, in which the “I”
and the “me” communicate more or less contentiously, which will determine the amount of
permanence or transformation of the self. Like outer grasps on collective problems, inner
grasps are also constantly put to the test by what one experiences in social situations.

Based on such an articulation, we have observed that the bias caused by asymmetric
ascendancy produces its effects on the relations of the self with its own internal province and
with its environment; its effects stretch down to the self’s very sense of reality developed in
its interactions with the other selves and the world. The ontological politics found in the new
mastery of nature projects itself over the territories of experience of different strata of the
world population, not just as a new grammar of relations with the environment, but, equally,
as an existential prescription that naturalizes flexibility as a principle for the orientation of
the self. The dynamics between the “I” and the “me” pointed out in the second part of this
text is fully connected to this process.

The internal components of the self are also coveted by this form of existential
ascendancy, since its goal is to influence the behavior of social actors. In order to further
assess this assertion, I must take the case of climatic change policies mentioned by Pellizzoni
(2015: 4): according to him, the new approach towards nature becomes normative when,
among other factors, it boosts the overlapping of the principle of adaptation to that of
mitigation in these regulations. This process leads to the normalization of uncertainty and
spreads the imperative of flexibility to adapt to new situations as a form of individual
responsibility in face of risks. The emphasis on the concept of adaptation, as it was molded
and disseminated by multi-lateral actors, such as the United Nations Framework Convention
on Climate Change (UNFCCC), shifts the focus of measures regarding risks from a
paradigm of stability to that of adequacy to environmental instabilities (Jennings, 2011:
12 Périlleux (2001) speaks of “self-tests” (épreuves du soi) in an approach closely linked to that of Boltanski and
Chiapello (1999).

240). According to Grove (2014: 204), the adaptation discourse in contemporary climate-
change and disaster policies heads towards the production of forms of life “appropriate” to
contexts under risk, which are responsive to them and capable of forging their actions based
on signs of threat. Just as assessed by Jennings (2011), the study by Grove suggests that,
oftentimes, one of the consequences of implementing adaptation policies is the establishment
of asymmetric relations between government and local populations that atomizes social
responsibility for risks by transferring it from the state to the individual level. Once exposed
to educational and qualification programs and to awareness initiatives, individuals are
expected to engage in reviews of their own attitudes in order to make themselves pliable to
the contingency of milieus (Grove, 2014: 203ff). An adaptable self is then vaunted, flexible
enough to adequate to, and even to profit from, the unavoidable indeterminacy of nature and
to be responsible enough to know that its fortune in this risky setting depends mainly on its
individual behavior.

It is worth highlighting that such a critical consideration about the concept of
adaptation refers to its hegemonic, contemporary version, which is consolidated in the
official circles of the United Nations and national governments. The term presents a
polysemic spectrum, and pragmatism itself houses a conception of adaptation related to its
ecological interpretation of agency. The first generation of critical theory clung to a
troublesome reduction of such an interpretation as a form of political conformism, when, by
talking about adaptation, pragmatists actually “[...] never meant routine and loss of
subjectivity but practical innovation, creative solutions to real problems.” (Joas, 1985
[1980]: 83, emphasis in original)13. Based on such logic, and besides the pragmatist difficult
relation with conflict that I have herein tried to compensate, adaptation can represent either a
way of accommodating to the status quo or to fully transform it. The current hegemonic
conception of adaptation can nonetheless be interpreted as a feature to prevent
transformation, especially if it is oriented towards a radical revision of risk production in
capitalism. Many times, the non-publicized implication of a discourse that advocates for the
promotion of empowerment of vulnerable communities, so they can develop their own ways
of adaptation, is, in fact, the exclusion of anti-systemic alternatives of response.

The flexibilization of life as imperative linked to the new spirit of capitalism brings
along a configuration where dealing with risks implies the continuous availability of
13 See Dewey’s (2013 [1934]: 14-15) differentiation between accommodation, adjustment and adaptation and the
sociological account of adaptation in contexts of social change in Thomas and Znaniecki (1918-21).

cognitive and affective arrangements between people and environments. If the new mastery
of nature sets a guideline that can lead local actors to lose their grasps over the milieu, it may
also promote a forced malleability of life projects, desires and dreams at the inner domains
of their selves, which is justified by the need of adequacy to an always mobile horizon of
hazards. Based on the conceptual articulation I have addressed earlier, I can talk about the
chances of a varying loss not only of outer, but also inner grasps when individuals find
themselves under the ascendancy of the hegemonic agenda of contemporary risk policies.

By replicating what happens in other neoliberal institutional coordinates (Boltanski
and Chiapello, 1999), to the extent that legitimate powers are successful in diffusing the
principles of adaptation and flexibilization, it is possible that a tendency for the reduction of
autonomous determination of the perspectives of local actors may develop. This is due
mainly to the interference in their selves’ inquiry space. The “I” lies in the center of this
dynamics of ascendancy, since it is necessary to encapsulate its singularizing activity within
a behavioral program ruled by the ethos of flexibility and adaptability. However, due to the
striking contingency of the “I”, the logic of adaptation opts for an indirect form of control. It
reaches the objective phases (“me”) of its target audience, provides them with justifications
for an individualized responsibility towards risk and diminishes the room for autonomous
responses of the “I”. This “culture of safety” (Grove, 2014: 205) espoused by many risk
reduction official managers, is entangled with the perspective of the ontological instability of
the environment, result of material manipulations upon nature’s properties. As a result,, the
tests biasing these audiences’ inner grasps towards adaptable versions of their selves are
sustained by both conventional and material supports. In the end, we observe that the
depoliticizing outer grasps laid by the new mastery of nature upon its resistance to typical
industrial exploration are mirrored by the exaltation of a flexibilizing model of inner grasp
with the purpose of ascendancy.

Conclusion
The discussion about the contemporary ontological politics based on Mead’s
philosophy stands out due to the sensibility of his naturalist pragmatism to the entanglement
of the natural and the social. With the aid of his perspective we observe that new forms of
political coordination of nature derive from reciprocal modifications in perspectives between
human communities and the biogeophysical world. With that in view, the integration of
subjective processes of the self within a critical appreciation of society cannot dispense with
the disclosure of the engines of mesological ascendancy that entertain human relations. Thus,
the reassessment of risks as opportunities favors an asymmetric form of ontological
flexibilization that affects life from its molecular level to the symbolic exchanges at social
plan.

Throughout the article, Markell’s rescue of James and Dewey’s influence on
Mead’s initial definition of the concepts of “I” and “me” have worked as the basis for the
reinterpretation of the relationship between materiality and subjectivity in the final,
Whiteheadian phase of his work, and it enabled a new outlook over the role of materiality in
the composition of the self. This was the background for the articulation between Mead’s
pragmatism and Chateauraynaud’s sociology, which proposed the former’s concept of self as
the fundament for the pragmatics of interiority envisaged by the latter, rendering it a
Meadian twist. By bringing together these two authors, I sought to contribute with an
alternative to the hegemonic interpretation of the internal dynamics of the Meadian self in
sociology, more sensible to the material contours of subjectivity. What has been developed
in this article lays the foundations for this endeavor, which shall be further explored both
theoretically and empirically in future occasions. The idea of self-inquiries as one’s attempt
to grasp itself may be unfolded both internally, through the access of other regions in the
works of its two central authors, or externally, by bringing into its synthesis other references
converging to the general conception of self sketched throughout the text.

## References
BESSY C and CHATEAURAYNAUD F (1995) Experts et faussaires. Pour une sociologie
de la perception. Paris: Métailié.

BOLTANSKI L and CHIAPELLO E (1999) Le nouvel esprit du capitalisme. Paris:
Gallimard.

BOLTON CB (1981) Some consequences of the Meadian self. Symbolic Interaction, 4(2):
245-259.

BLUMER H (1969) Symbolic interactionism: Perspective and method. Englewood Cliffs:
Prentice-Hall.

BLUMER H (2004) George Herbert Mead and human conduct. Walnut Creek: Altamira.

BREWSTER BH and PUDDEPHATT AJ (2013) George Herbert Mead as a socio-
environmental thinker. In: JOAS H and HUEBNER DR (eds) The timeliness of George
Herbert Mead. Chicago: The University of Chicago Press.

CEFAÏ D (2001) Le naturalisme dans la sociologie américaine au tournant du siècle: La
genèse de la perspective de l’École de Chicago. Revue du MAUSS, 1(17): 261-274.

CHATEAURAYNAUD F (2004) L’épreuve du tangible: Expériences de l’enquête et
surgissements de la preuve. In: KARSENTI B and QUÉRÉ L (eds) La croyance et l’enquête:
Aux sources du pragmatisme. Paris: EHESS.

CHATEAURAYNAUD F (2015) L’emprise comme expérience: Enquêtes pragmatiques et
théories du pouvoir. SociologieS, Dossier “Pragmatismes et Sciences Sociales” (on-line).

Available at: http://sociologies.revues.org/4931, (accessed 23 February 2015).

CHATEAURAYNAUD F (2018) De la criticité des causes environnementales. In: CARLINO
V and STEIN M (eds) Les paroles militants dans les controverses environnementales. Nancy:
Editions Universitaires de Lorraine.

CHATEAURAYNAUD F and DEBAZ J (2017) Aux bords de l’irréversible: Sociologie
pragmatique des transformations. Paris: Petra.

COOK GA (1993) George Herbert Mead: The making of a social pragmatist. Urbana and
Chicago: University of Illinois Press.

COOK GA (2013) Mending Mead’s “I” and “me” distinction. In: LOW J and BOWDEN G
(eds) The Chicago School diaspora: Epistemology and substance. Montreal and Kingston:
McGill-Queen’s University Press.

COOLE D and FROST S (2010) Introducing the new materialisms. In: COOLE D and
FROST S (eds) New materialisms: Ontology, agency, and politics. Durham and London:
Duke University Press.

COOPER M (2008) Life as surplus: Biotechnology and capitalism in the neoliberal era.

Seattle and London: University of Washington Press.

CORRÊA DS (2021) Esboço de uma sociologia dos problemas íntimos. Sociologia &
Antropologia 11(2): 415-444.

DEMEULENAERE E (2014) A political ontology of seeds: The transformative frictions of a
farmer’s movement in Europe. Focaal – Journal of Global and Historical Anthropology 69:
45-61.

DEWEY J (1896) The reflex arc concept in psychology. The Psychological Review, III(4):
357-370.

DEWEY J (2013 [1934]) A common faith. New Haven and London: Yale University Press.

DEWEY J, HOOK S and NAGEL E (1945) Are naturalists materialists? The Journal of
Philosophy 42(19): 515-530.

DODIER N (1993) Les appuis conventionnels de l’action: Eléments de pragmatique
sociologique. Réseaux 11(62):63-85.

FREGA R (2006) John Dewey et la philosophie comme épistémologie de la pratique. Paris:
L’Harmattan.

GIDDENS A (1984) The constitution of society. Cambridge: Polity.

GROVE K (2014) Biopolitics and adaptation: Governing socio-ecological contingency
through climate change and disaster studies. Geography Compass 8(3): 198-210.

HABERMAS J (1987 [1985]) The theory of communicative action, vol. 2. Boston: Beacon.

HABERMAS J (1992) Postmetaphysical thinking: Philosophical essays. Cambridge, MA:
The MIT Press.

HONNETH A (1995 [1992]) The struggle for recognition. Cambridge: Polity.

HONNETH A (2002) Grounding recognition: A rejoinder to critical questions. Inquiry: An
Interdisciplinary Journal of Philosophy 45(4):499-520.

HUEBNER, DR (2014) Becoming Mead: The social process of academic knowledge.

Chicago: The University of Chicago Press.

JAMES W (1955 [1890]) Principles of psychology. Chicago: The University of Chicago
Press/Encyclopaedia Britannica.

JENNINGS T (2011) Transcending the adaptation/mitigation climate change science policy
debate: Unmasking assumptions about adaptation and resilience. Weather, Climate, and
Society 3(4): 238-248.

JOAS H (1985 [1980]) G.H. Mead: A contemporary re-examination of his thought.

Cambridge, MA: The MIT Press.

JOAS H (1993) Pragmatism and social theory. Chicago: The University of Chicago Press.

JOAS H (1996) The creativity of action. Chicago: The University of Chicago Press.

LEWIS JD (1979) A social behaviorist interpretation of the Meadian “I”. American Journal of
Sociology (85)2: 261-287.

MacGILVRAY E (2004) Reconstructing public reason. Cambridge, MA: Harvard University
Press.

MARKELL P (2007) The potential and the actual: Mead, Honneth, and the “I”. In: VAN
DEN BRINK, B and OWEN, D (eds) Recognition and power: Axel Honneth and the tradition
of critical social theory. Cambridge: Cambridge University Press.

MEAD GH (1903) The definition of the psychical. Decennial publications of the University
of Chicago, 1º series, Vol. III. Chicago: The University of Chicago Press.

MEAD GH (1904) Image or sensation. Journal of Philosophy, Psychology and Scientific
Methods 1(22): 604-607.

MEAD GH (1910) What social objects must psychology presuppose? Journal of Philosophy,
Psychology and Scientific Methods 7(7): 174-180.

MEAD GH (1912) The mechanism of social consciousness. Journal of Philosophy,
Psychology and Scientific Methods 9(15): 401-406.

MEAD GH (1913) The social self. Journal of Philosophy, Psychology and Scientific Methods
10(14): 374-380.

MEAD GH (1922) A behavioristic account of the significant symbol. The Journal of
Philosophy 19(6): 157-163.

MEAD GH (1925) The genesis of the self and social control. International Journal of Ethics
35(3): 251-277.

MEAD GH (1926) The nature of aesthetic experience. International Journal of Ethics 36(4):
382-393.

MEAD GH (1932) The philosophy of the present. LaSalle, IL: Open Court.

MEAD GH (1967 [1934]) Mind, self & society. Chicago: The University of Chicago Press.

MEAD GH (1972 [1938]) The philosophy of the act. Chicago: The University of Chicago
Press.

MEAD GH (2011 [n.d.]) On the self and teleological behavior. In: SILVA, FC (ed) G.H.

Mead: A reader. London and New York: Routledge.

MELLO, FC (2017) Assimetria e Contestação: Uma sociologia pragmatista das
subjetividades coletivas. PhD thesis, State University of Rio de Janeiro, Brazil.

MELLO, FC (2019) As transformações de Francis Chateauraynaud: Percepção e
reflexividade na segunda onda da sociologia pragmática francesa. Sociologia & Antropologia
9(1): 159-184.

MOL A (1999) Ontological Politics: A word and some questions. The Sociological Review
47(S1): 74-89.

MORIN E (2008) On complexity. Cresskill: Hampton Press.

PAPADOPOULOS D (2011) The imaginary of plasticity: neural embodiment, epigenetics,
and ecomorphs. The Sociological Review (59)3: 432-456.

PELLIZZONI L (2015) Ontological politics in a disposable world: The new mastery of
nature. Farnham: Ashgate.

PÉRILLEUX, T (2001) Les tensions de la flexibilité: L’épreuve du travail contemporain.

Paris: Desclée de Brouwer.

ROSENTHAL SB and BOURGEOIS PL (1991) Mead and Merleau-Ponty: Toward a
common vision. Albany: State University of New York Press.

SILVA FC (2007) G.H. Mead: A critical introduction. Cambridge: Polity.

SILVA FC (2008) Mead and modernity: Science, selfhood, and democratic politics. Lanham:
Lexington Books.

STRAUSS A (1959) Mirrors and masks: The search for identity. Glencoe, IL: Free Press.

SZERSZYNSKI B, KEARNES M, MACNAGHTEN P, OWEN R and STILGOE J (2013)
Why solar radiation management geoengeneering and democracy won’t mix. Environment
and Planning A 45: 2809-2816.

THOMAS WI and ZNANIECKI F (1918-21) The Polish peasant in Europe and America:
Monograph of an immigrant group, 4 vols. Boston: The Gorham Press.

WHITEHEAD AN (2011 [1925]) Science and the modern world. Cambridge: Cambridge
University Press.

WHITEHEAD AN (1978) Process and reality. New York: Free Press.

