---
title: "Constructive Forms of Uncertainty in Spinoza’s Theological Political Treatise"
author: Alfonso R. Vergaray
---

CONSTRUCTIVE FORMS OF UNCERTAINTY IN SPINOZA’S THEOLOGICAL POLITICAL TREATISE 1

ALFONSO R. VERGARAY

Texas A&M International University
alfonso.vergaray@tamiu.edu
ABSTRACT
In the preface to the Theological Political Treatise Spinoza presents uncertainty as an intractable
problem in political and social life. Scholars have indirectly examined uncertainty’s role in TTP,
focusing on fear, hope, and superstition. This article takes a comprehensive view of the multiple parts
of uncertainty, ultimately showing uncertainty to be both a problem and a source of social vitality. It
argues that Spinoza’s central means of addressing destructive forms of uncertainty is through the
advancement of what I call constructive forms of uncertainty. Instead of recognizing only the poten-
tial dangers and pitfalls accompanying uncertainty, this paper argues that uncertainty can construc-
tively support political stability and a free state. This interpretation presents a fresh reading of the
role of uncertainty in the TTP and points toward Spinoza’s abiding concern with uncertainty through-
out his oeuvre.

KEYWORDS
Spinoza; uncertainty; hope; fear; superstition; devotion; democracy.

Questions about uncertainty are at the heart of Spinoza’s philosophy. Can certain
knowledge be attained? How certain are the workings of the natural world? How do
experiences of uncertainty influence political and social life? Before applying his mind
to those questions, Spinoza experienced harrowing forms of uncertainty in his early
life. At the age of six, he lost his mother. His sister died when he was nineteen; his
stepmother and father died when he was twenty-one. At the age of twenty-three, Spi-
noza was excommunicated from the Jewish community of Amsterdam. Moreover, dur-
ing those periods and in later life Spinoza struggled with health issues, survived multiple
plagues, and lived in a society with persistent religious and political turmoil (Nadler
2018, Steenbakkers 2021).

1 Earlier drafts of this paper benefited from comments and support by Joe Pitt, Ben Sax, and Eric
Schliesser.

Save his excommunication, the kinds of life events highlighted above were shared
by those living in the 17th-century Dutch republic of Spinoza’s day. Indeed, life expec-
tancy was low, political and religious disputes the norm, and public-health crises an
inescapable life obstacle. Spinoza’s response to the tumultuous sea of uncertainties he
experienced, however, was distinct. Through a religious-like devotion to philosophy,
Spinoza embraced “an ideal of intellectual rest,” applying his mind to what I call the
problem of uncertainty (Carlisle 2021, 23). Life is experienced as uncertain (i.e., as an
open question) and as such demands a response. When philosophy becomes the tool
used to diagnose the problem of uncertainty, it becomes apparent that uncertainty is
also a metaphysical, epistemological, and political problem. The problem of uncer-
tainty, while not named as such by Spinoza—much like the “principle of sufficient rea-
son” and “necessitarianism”—can nonetheless be discerned throughout his philosophy.

While I cannot defend the entirety of that claim here, I limit what follows to Spinoza’s
thoughts on uncertainty as they relate to political and social life.

In particular, I reconstruct Spinoza’s argument for constructive forms of uncertainty
in the Tractatus Theologico-Politicus (TTP). By constructive uncertainty, I refer to so-
cially beneficent forms of uncertainty that help sustain social order and/or promote
human flourishing. In the preface to the TTP, Spinoza shows in dramatic fashion the
ways that uncertainty creates upheavals of thought that are central to the origin and
maintenance of superstition. In all, uncertainty is presented as an intractable political
and social problem. Although uncertainty is an intractable problem, Spinoza does not
suggest eliminating it, nor is restraining its effects sufficient; rather, I argue, Spinoza’s
main means of addressing the uncertainty underlying superstition is to promote con-
structive forms of uncertainty. Spinoza prefers hope as a constructive form of uncer-
tainty, as it aligns with the active affects. Fear, by contrast, while useful under certain
circumstances, is presented as a largely destructive form of uncertainty.2 The salutary
effects of a hope-filled society are insufficient, however, if not accompanied by devotion
to the state. A devotion to the state anchors hope, solidifying it, which distinguishes it
from the reckless and wavering hopes pursued by those gripped by fear.

This article comprises three sections. The first section lays the groundwork for un-
derstanding constructive forms of uncertainty by providing an overview of the problem
of uncertainty in the preface of the TTP. The second section turns to chapter V of the
TTP to introduce both a pre-democratic use of constructive uncertainty in the Hebrew
republic as well as devotion’s stabilizing function. The third section ties together what
2 In Steinberg’s framing, Spinoza “privileges hope over fear” (83). I use “preference” instead of “priv-
ilege” in order not to lose sight that, for Spinoza, prioritizing one emotion over another is “dependent on
the specific circumstances that make obedience possible” (Vardoulakis 2020, 238).

followed in its examination of democratic hope. While not exhaustive, I hope that what
follows encourages readers of Spinoza to understand his philosophy as an attempt to
come to terms with the problem of uncertainty.

More generally, this paper goes against the grain of conventional thinking regarding
uncertainty. On the whole, uncertainty is presented as a problem in both popular cul-
ture and academic literature. To deal with this problem, academics and risk managers
transform uncertainty into risk in order to calculate risk probabilities empirically.3 Their
aim is to control, reduce, and, in all, mitigate a danger. Spinoza understood that be-
cause experiences of the future as uncertain are an inevitable feature of human life,
uncertainty must be dealt with on its own terms. In addition to being a danger that
needs to be restrained or avoided, uncertainty can be a constructive social force. In its
optimal political form, the uncertainties supported and unleashed in a free state point
their inhabitants toward joyful living.

SUPERSTITION AND UNCERTAINTY IN THE PREFACE OF THE TTP
This section provides an overview of uncertainty’s link to the origin and maintenance
of superstition in the preface of the TTP. It highlights the relationship between the
uncertain emotions and superstition, concluding with a preliminary reflection on Spi-
noza’s preference for hope over fear. After completing this section we will be prepared
to consider constructive forms of uncertainty in the TTP.

Despite the many themes of uncertainty that run throughout the TTP, scholars have
paid limited attention to its overarching significance. They either ignore uncertainty’s
role in Spinoza’s political thought, or acknowledge it without giving it pride of place in
their analysis.4 James (2012) uses the term uncertainty three times to connect it with
hope, fear, and/or superstition, but does not develop the connection further. She notes,
for example, that in order to relieve “the fear to which uncertainty exposes” individuals
turn to superstition (18). Steinberg (2018) likewise uses the term uncertainty when dis-
cussing Spinoza’s analysis of hope and fear in the preface of the TTP, but says little
else about the role of uncertainty in his analysis of Spinoza (83). Yirimyahu Yovel
(1989), in addition to acknowledging the presence of uncertainty in the TTP, makes
3 Consider, for example, Hacking, The Emergence of Probability; Modd, When All Else Fails; and
Power, Organized Uncertainty.

4 See James (‘Spinoza on Superstition’); Kaminsky (Spinoza, 61-64); Nadler (‘Hope, Fear, and
the Politics of Immortality’). I use ‘emotion’ to refer to Spinoza’s use of affectus. Hope and fear are
labeled as emotions in order to preserve the possibility that they may function as passive or active affects
in different contexts.

the direct claim that uncertainty “breeds superstition” (131). I follow and develop his
claim in what follows.

The first line in the TTP introduces readers to what I call the problem of uncer-
tainty, or what is parallel when considering social life, the problem of superstition.

If men could manage all their affairs by a definite plan, or if fortune were always
favorable to them, no one would be in the grip of superstition. (TTP 65)
Spinoza's requirements for preventing humans from falling prey to superstition can-
not be met. Human's lack control to direct their lives according to a definite plan, and
good fortune cannot be relied on to consistently ward off the destabilizing blows of
misfortune. The experience of the future as uncertain, consequently, makes humans
susceptible to superstition. For Spinoza, then, uncertainty and superstition can be un-
derstood as an inter-connected and self-sustaining problem that can be alleviated, but
not resolved.

There are three steps to trace in Spinoza’s use of uncertainty when describing its
connection with superstition. First, experiencing the future as uncertain is tied to the
omnipresent problem of superstition, placing uncertainty at the core of our understand-
ing of the origins and maintenance of superstition. Second, uncertainty about the future
releases the uncertain and future-oriented emotions of hope and fear. Those emotions
are both forms of uncertainty and responses to uncertainty. Third, those emotions can
be used by political agents and/or embedded within institutional and legal frameworks
to either constructively support the state, or destructively lead to the breakdown of civil
order. Constructive here refers to (a) the basic political and social stability required to
have a minimally functioning state and (b) the promotion of human flourishing. Notice,
you can have (a) without (b), but necessarily will have (a) if you have (b). The uncertain
emotions of hope or fear can constructively work to reach and sustain both these ends.

Constructive need not be “good” in my rendering. For instance, a despot can use con-
structive uncertainties for her devious ends, aiming for minimal social stability without
a concern for the human flourishing of her subjects.

Before proceeding to examine Spinoza’s thoughts on constructive uncertainty, let’s
first better understand how fear and hope are both forms and responses to uncertainty.

The animating force behind the problem of uncertainty are the fluctuating emotions
that are unleashed due to a lack of certainty about the future.

Then they vacillate [fluctuant] wretchedly between hope [spem] and fear [me-
tumque]; desiring immoderately the uncertain [incerta] goods of fortune, and ready to
believe anything whatever. While the mind is in doubt [in dubio], it’s easily driven this
way or that—and all the more easily when, shaken by hope and fear, it comes to a stand-
still. At other times, it’s over-confident, boastful and presumptuous. (TTP 65-6)
The uncertain emotions dominate the emotive state of someone in the grip of un-
certainty about the future. Even over-confidence, boastfulness or presumptiveness,
which do not qualify as uncertain emotions, are momentary states on the pendulum of
a life gripped by uncertainty. The uncertain emotions here refer to hope and fear.

Spinoza gestures to his fuller account of hope and fear in the Ethics when he writes of
the vacillating [flutuant] nature of those emotions, which reminds us of the vacillation
of mind [fluctuatio animi] that he presents in that work. In the Ethics, Spinoza writes
of hope and fear as follows:
Hope is nothing but an inconstant [inconstans] Joy which has arisen from the image
of a future or past thing whose outcome we doubt [dubitamus]; Fear, on the other hand,
is an inconstant Sadness, which has also arisen from the image of a doubtful thing.

(IIIP18S2)
Hope and fear are uncertain emotions in two interrelated ways. First, they both are
experienced as inconstant emotive states that are driven by doubt [dubitamus] regard-
ing an outcome.5 The uncertain feelings that accompany doubt about a prospective
outcome are necessarily linked to these emotions. Consequently, when doubt is re-
moved, hope and fear transform into confidence and despair, respectively. Second, as
Spinoza explains later, vacillations of the mind [fluctuatio animo] stem from hope and
fear (IIIP49S). Vacillation of mind refers to a ‘constitution of the Mind which arises
from two contrary affects’ and is closely linked to dubitamus (III P17 S). As hope and
fear are interrelated—‘there is no Hope without Fear, and no Fear without Hope’—they
have the potential to create simultaneous or fluctuating experiences (IIIP50S). For ex-
ample, if a student is filled with hope that she performed well on an exam, she also
fears, on some level, that she may have performed poorly. The student’s uncertain
affects are activated, in other words, when there is uncertainty regarding the outcome
of her final grade. While hope or fear may dominate her experience at certain mo-
ments, they may also increase, decrease, or collide based on external causes. If she
learns, for example, that the class average for the exam is low, her initial inclination
towards hope might turn to fear. Once her final grade is revealed (i.e., when certain
knowledge replaces uncertainty), hope and fear dissipate, and joy, grief, or another set-
tled affect overtakes. It should now be understood that for Spinoza a state of emotive
uncertainty is present in hope and fear, whether as doubt regarding an outcome accom-
panying each or the vacillations of the mind that stem from both.

Returning to the beginning of the preface, let us apply Spinoza’s ideas regarding the
emotive uncertainty accompanying fear and hope to his account of the problem of
5 As Susan James puts it, “What ties the two [fear and hope] together is the fact that each is a response to
doubt or uncertainty.” (2021)
superstition. In what follows I restate Spinoza’s account of the destructive uncertainties
underlying superstition and present inadequate responses to those uncertainties to
highlight the need for constructive uncertainties.

Spinoza follows a regular characterization of superstition as a response to fear found
in classical writers, and reiterated all the way through the early-modern period (James,
‘Spinoza on Superstition’, 3). In particular, he writes in the TTP: ‘The reason, then,
why superstition arises, lasts, and increases, is fear’ (TTP 67). Given Spinoza’s state-
ments regarding the interconnected nature of hope and fear in the Ethics, his claim
about fear’s relationship to superstition in the TTP appears one-sided.6 That intercon-
nected view is suggested earlier in the preface where Spinoza describes the alternating
hopes and fears that are the outgrowth of superstition. Spinoza’s reason for emphasiz-
ing fear’s connection to superstition in the quote above is to highlight its destructive
possibilities; possibilities borne from emotive uncertainty.

Someone in the grip of emotive uncertainty is liable to change superstitions on a
whim,7 due to superstition being “necessarily very fluctuating and inconstant’ (TTP 68).

It is difficult, after all, to remain true and loyal to any one superstition when caught in
a state of emotional unrest. Consequently, Spinoza writes, ‘This inconstancy [incon-
stantia] has been the cause of many uprisings and bloody wars’ (TTP 68). The incon-
stant nature of superstition is one form of what I call destructive uncertainty, as it leads
to social and political unrest. Yet the ability to use superstition for constructive ends is
immediately addressed by Spinoza in the next sentence:
As is evident from what we have just said, and as Curtius aptly noted, “Nothing gov-
erns the multitude more effectively than superstition.” (Quintus Curtius, IV, x, 7) (TTP
68)
Political agents have attempted, in other words, to constructively use superstitions—
read uncertainties—to create order and forms of governance.8 Those attempts, as Spi-
6 The immediate context before and after the quote above—on the crazed and tormenting rela-
tionship between fear and superstition— sheds light on Spinoza’s emphasis on fear. In the Ethics Spinoza
presents a more balanced account of superstition: ‘we are so constituted by nature that we easily believe
the things we hope for, but believe only with difficulty those we fear, and that we regard them more or
less highly than is just. This is the source of the Superstitions by which men are everywhere troubled’
(IIP50S).

7 As Spinoza puts it, ‘The common people [vulgus] always remain equally wretched, so they are
never satisfied for long’ (TTP 68).

8 Curtius is using and reacting to uncertainty. See James (2012) “Mining its insights, Spinoza now
focuses on Quintus Curtius’s claim that even the boldest rulers are liable to become superstitious when
they confront great danger and uncertainty.” (19)
noza makes clear, often fail, as it is easy to sway the common people from one super-
stition to the next.9 Still, the attempt to use superstition for constructive ends (i.e., to
govern) is highlighted here. The fluctuating nature of superstitions due to the ever pre-
sent problem of uncertainty, however, makes attempts to govern with superstitions un-
reliable. How, then, can the problem of uncertainty that underlies the types of super-
stitions Spinoza presents in the preface be addressed?
The first proposal Spinoza reviews is the attempt of ‘the Turks’ to instill religious
prejudices to such an extent that it leaves ‘no room in the mind for sound reason, nor
even for doubting [dubitandum]’ (TTP 68). In other words, one manner of addressing
the uncertainty underlying superstition is to eliminate uncertainty by instilling dogma,
a fixed superstition that bypasses doubt (uncertainty) with certain beliefs. In practice,
that may temporarily produce results. Over time, however, competing superstitions are
bound to arise, disrupting the temporary order produced by dogmatic belief. Further-
more, the attempt to eliminate doubt through indoctrination enslaves the mind, inhib-
iting the freedom of judgment necessary for the attainment of knowledge and freedom.

Instead of enslaving the mind, perhaps a solution to the problem of uncertainty is
educating the mind to not be swayed by the uncertain emotions. In the Ethics, Spinoza
shows a path to a life of freedom, i.e., the way to escape a life of bondage to the passions.

Part of that education entails striving to ‘depend less on Hope, to free ourselves from
Fear, to conquer fortune as much as we can, and to direct our actions by the certain
counsel of reason.’ (IIP47S). Indeed, leading a rational life is an option to prevent
being subject to superstition. The difficulty of attaining that way of life, however, corre-
sponds with its rarity.10 In other words, while striving for the knowledge necessary to
free oneself from fear is a possibility for the few, it is not a realistic option for the many.11
Still, Spinoza argues it is possible to develop a society that points towards rational ways
of being.12 That does not mean, however, that you can overcome superstition. The
human inclination towards superstition is too interwoven with what it means to be hu-
man to ever be eradicated on a collective scale. Hence Spinoza can unequivocally state
in the preface of the TTP that ‘it’s as impossible to save the common people from
superstition as it is from fear’ (TTP 75). Creating a society of philosophers is therefore
9 See the sentence following the Curtius quote, ‘That’s why they are easily led, under the pretext
of religion, now to worship their Kings as Gods, now to curse and loathe them as the common plague of
the human race.’ (TTP 68)
10 Consider Spinoza’s famous final line in the Ethics, ‘all things excellent are as difficult as they
are rare.’ (VP42S)
11 ‘But only a very few (compared with the whole human race) acquire the habit of virtue from the
guidance of reason alone’ (TTP 281-82).

12 Susan James (2012) makes this case in her book Spinoza on Philosophy, Religion and Politics.

not a realistic option. At best, a society can incline individuals towards rational ways of
being using constructive uncertainties—including superstitious like uncertainties—to
point the way. In sum, neither instilling dogma, nor expecting most individuals to live
a life of reason, effectively addresses the problem of uncertainty on a collective scale.

Spinoza’s explicit response to the problem of uncertainty is on the surface puzzling.

Instead of filling ‘the free judgment of each man with prejudices,’ Spinoza suggests that
the complete freedom of judgment, already present in the Dutch Republic, is condu-
cive to the piety and peace of the Republic (TTP 69).13 This is puzzling as promoting
complete freedom of judgment would unleash a broad array of viewpoints. Those view-
points would likely clash given that judgment is inherently fallible, resulting in “no nor-
mative criteria for a correct practical judgement” (Vardoulakis 260). In such conditions
uncertainties would be unleashed, resulting in more collective superstitions. Given the
above, it is unclear how granting freedom of judgment addresses the problem of super-
stition Spinoza carefully lays out in the preface.

One response to this puzzle might note that Spinoza later suggests ways to restrain
the freedom of judgment, and therefore deals with the problem of uncertainty through
mechanisms of restraint.14 While it is the case that Spinoza dedicates the latter section
of the TTP to discuss the limitations to freedom of thought in a free state, restraining
that freedom does not squarely deal with the fundamental problem of uncertainty.

Thus, the problem of uncertainty unleashed in a free state remains. Seeing that uncer-
tainty cannot be eliminated, a better approach is to ask, what uncertainties should be
unleashed in a free state? And how do those uncertainties combat destructive forms of
superstitions /uncertainties?
Briefly answering this question will take the first step to understand Spinoza’s means
of addressing the problem of superstition. In what follows, I review his preference for
hope over fear as a constructive form of uncertainty. I later work out those ideas in
section III of this paper.

Hope is the emotion that flourishes in a democratic (free) state. Unlike its counter-
part fear, hope, properly framed in a democratic society, is better equipped to guide
people towards a life lived in common that increases the possibility of peace and stabil-
ity over time. Hope contributes to the ‘foundation and end’ of democracy, which is to:
avoid the absurdities of appetite, and to confine men within the limits of reason, as far
as possible, so that they may live harmoniously and peacefully. (TTP 288)
13 It is a stretch to claim there was “complete freedom of judgment” in the Dutch republic at the
time. See Curley 55-56.

14 Spinoza’s stated purpose from chapter XVI onwards is to examine how far ‘freedom of thought,
and of saying what you think, extends in the best Republic’ (TTP 282).

Hope does not alone achieve the fundamental purpose of democracy. It is a neces-
sary, but not a sufficient condition. Devotion to a free state is another piece in the puz-
zle. I later examine devotion and freedom as they relate to constructive uncertainty,
especially devotion’s role in stabilizing the inconstant nature of superstition. The point
here is that the hope unleashed in a democratic society produces a constructive form
of uncertainty, which combats dangerous superstitions alongside devotion to a free
state. Let us preview why using hope is a viable option to counter the problem of
superstition.

As we have seen, using the intellect alone to deal with destructive passions on a social
and political scale is not sufficient. Thus, any manner of addressing those passions will
necessarily entail countering the destructive passions with other affects. That is to say,
we should follow Spinoza when he writes:
An affect cannot be restrained or taken away except by an affect opposite to, and stronger
than, the affect to be restrained. (IVP7)
Fear, as noted above, takes center stage in Spinoza’s description of the destructive
effects of superstition in the TTP. It is so problematic that Spinoza writes: ‘men are
tormented by superstition only so long as they are afraid’ (TTP 67). If fear is taken out
of the equation, in other words, superstition can seriously be tempered. As eliminating
fear is not an option, its counterpart, hope, offers a way to redirect its effects.

Hope is not without its defects, however. In the preface to the TTP, Spinoza notes
that hope can be used to protect superstition (TTP 68). In the Ethics Spinoza writes
that ‘Hope and Fear cannot be good of themselves’ and observes that they ‘show a
defect of knowledge and lack of power in the Mind’ (IVP47S). Indeed, fear and hope
are obstacles to our autonomy, freedom, and happiness. (Nadler 2005, 216). Yet be-
cause humans rarely live from the dictates of reason, Spinoza further notes, ‘Hope and
Fear, bring more advantage than disadvantage’ (IVP54S). In other words, there is a
constructive role for hope and fear to play. Like Hobbes, Spinoza notes that fear can
be used to foster order and serve as a form of restraint. Unlike Hobbes, however, he
argues that relying on fear to govern cannot consistently be depended on to foster po-
litical stability. Even when fear does manage to sustain a society, the damaging forms of
superstition it unleashes stunts human development, seriously hampering individual
and collective flourishing. Spinoza’s preference for hope in a free society, moreover,
differs starkly from Hobbes who makes fear an all-encompassing feature of his author-
ity-driven political theory.15
15 See chapter 7 in Vardoulakis for an excellent account of natural right and authorization in Spi-
noza and Hobbes.

Before turning to introduce examples of constructive forms of uncertainty in the
Hebrew republic, let us turn to a quote from Spinoza’s Political Treatise (TP) to frame
the discussion that follows.

For a free multitude [multidudo] is guided [ducitur] by hope more than by fear, whereas
a multitude which has been subjugated is guided more by fear than by hope. The first
want to cultivate life; the second care only to avoid death. The first are eager to live for
themselves; the second are forced to belong to the victor. So we say that the second are
slaves, and the first free. (TP 530)16
This quote succinctly captures Spinoza’s position that the uncertain emotions lead
[ducitur] people, as well as his preference for hope as the guiding form of uncertainty
in a free state.

CONSTRUCTIVE UNCERTAINTY IN THE HEBREW REPUBLIC
Spinoza first addresses constructive forms of uncertainty in chapter five of the TTP,
a chapter that begins discussing ceremonial rites in the Hebrew state. His discussion of
the uncertain emotions is most prominently featured when he turns from the ‘authority
of Scripture’ to ‘universal foundations’ to continue demonstrating how and why cere-
monial rites have preserved and stabilized the Hebrew state (TTP 143). More broadly,
this section in chapter V is a precursor to his later chapters on politics. I follow Spi-
noza’s argument in this section as it relates to constructive uncertainty, taking a brief
detour to chapter XVII to discuss devotion’s role in stabilizing the inconstant nature of
superstitious beliefs.

After arguing that social order is necessary for human security and flourishing, Spi-
noza turns to demonstrate that laws are necessary due to the recalcitrant nature of hu-
mans. He begins noting that a society without laws is not possible since humans are
liable to disobey what true reason teaches. They instead are apt to follow their narrow
self-interest (TTP 144). Considering that humans are inclined to be narrowly self-inter-
ested, Spinoza notes that teaching ‘true moral lessons’ will not yield the desired result
of individuals voluntarily choosing to live together in peace (TTP 144). Instead, hu-
mans require authority, force, and laws to be moved towards peaceful living.17
16 I take Spinoza’s usage of multidudo here to refer to a large number of people. For notes on
alternate uses of multidudo see Curley’s glossary entry, 644.

17 Vardoulakis argues that for Spinoza utility comes prior to authority and a need for laws. See
chapter 4. In his words, “reciprocity of utility does not require an established legal or political authority”
(147).

Spinoza observes that the emotive forces inclining humans towards self-interest are
such that they ‘take no account of the future’ (TTP 144). A narrow presentism, in other
words, coincides with immoderate desires. Instead of thinking about the future, a per-
son gripped by self-indulgent desires is stuck in the present.18 One of the benefits of
promoting constructive uncertainties, whether guided by hope or fear, is that it creates
a future-oriented posture that combats the narrowing of horizons that occur without it.

Immediately after claiming that force and authority are necessary for society, Spi-
noza tempers a potential penchant for authoritarianism when he quotes Seneca’s ob-
servation that ‘no one has sustained a violent rule for long; moderate ones last’ (TTP
144). Spinoza connects this insight with fear in the next sentence. He writes:
For as long as men act only from fear, they act very unwillingly, and don’t recognize the
advantage, even the necessity, of doing what they’re doing. All they care about is saving
their necks, and avoiding punishment. (TTP 144)
Spinoza in effect criticizes any form of ruling that attempts to rely solely on fear.

While using fear of punishment to motivate subjects to obey can prove effective in the
short term, relying solely on fear driven uncertainties is bound to be counterproductive,
putting peace and social stability in peril. Spinoza then shows that finding a means to
move people to willingly act in a way that encourages peace and stability is more effec-
tive than attempting to achieve that end through threat of punishment and fear. This
principle is stated in his second observation that follows from ‘universal foundations.’
It reads:
in each state the laws must be so instituted that men are checked not so much by fear as
by hope of some good they desire very much. For in this way everyone will do his duty
eagerly. (TTP 144)
Laws can be so instituted, in other words, that they become a form of uncertainty
that inclines people to do their duty willingly. Rather than instating laws that heighten
fear, Spinoza notes, laws that encourage future-oriented hopes are best suited to serve
as a check. Hope checks socially deviant behavior, for example, not through a threat
of punishment, but rather through a promise for a better future.

He then illustrates this principle by returning to the example of the Hebrew republic,
whose leaders were in a position to ‘enact new laws or to establish new legislation’ (TTP
145). Considering the Hebrew people were ‘weakened by wretched bondage,’ Spinoza
writes that they were not prepared for self-governance, and consequently they were
18 See also the Ethics ‘To this we may add that when we follow our affects, we value most the
pleasures of the moment, and cannot appraise future things with an equal affect of mind’ (IV Appendix
XXX).

subject to rule by a single sovereign (TTP 145). Moses was the most successful of these
sovereigns for two reasons. First, he could distinguish himself from the people by con-
vincing them of his divine power. Second, he took care to establish laws that were so
framed that ‘the people should do their duty, not so much from fear, as voluntarily’
(TTP 145). The threat of an impending war and the inability to rule the Hebrews
through force alone led Moses to use these strategies. Spinoza applies the second strat-
egy when he observes that success in war depends on soldiers being led through en-
couragement rather than through fear-laden threats of punishment. This is why, Spi-
noza continues, ‘Moses introduced religion into the Republic, so that the people would
do their duty not so much from fear as from devotion [devotione]’ (TTP 144-45).

While fear is downplayed here as an effective means to enlist obedience, devotion takes
its place as a motivating factor. How can devotion encourage obedience? How does
devotion temper the dangerous uncertainties underlying superstition? Let us examine
the power of devotion to enlist obedience and combat the inconstant nature of super-
stition in chapter XVII, as doing so will help us better understand Spinoza’s claim in
chapter V and set the stage for the next section.

Chapter XVII is focused on the causes behind the rise and fall of the Hebrew re-
public. Devotion, described as a combination of love and wonder (TTP 316),19 takes
center stage when Spinoza turns from an analysis of ways to restrain leaders to examine
ways to restrain the people (TTP 313). Devotion, in one form or other, is prominently
featured in this section, alongside ‘the principle of advantage’ and ‘extreme training in
obedience,’ as a means to restrain people in such a way to create a peaceful and stable
state (TTP 315, 316). In this context, devotion served as a form of restraint as it was
used to create a pious loyalty to the Hebrew state. Spinoza describes how a ‘devotion
[devotio] to their country’ was one of the factors that allowed the Hebrews ‘to bear
everything with special constancy and virtue’ (TTP 314). This devotion ran deep. As
Spinoza put it: ‘the love of the Hebrews for their country [patriam] was not a simple
love, but piety [pietas]’ (TTP 314). This piety gave the Hebrews a clear sense of their
enemies, which in turn strengthened their willingness to defend their country, thereby
encouraging order and obedience in the state.

More to the present argument, devotion helps stabilize the inconstant nature of su-
perstition outlined in the preface. It helps temper the swaying from one superstition
to the next due to the emotive unrest that accompanies moments of uncertainty. De-
votion cultivates inward stability, which helps weather outward uncertainties. More to
Spinoza’s larger argument in the TTP, devotion to the state places a priority on the
19 See also Ethics IIIP52S
collective good, thus facilitating peace and stability. Spinoza ends his discussion of de-
votion in this section in the strongest terms. He notes:
I don’t think anything more effective can be devised for steering people’s hearts in a
certain direction. Nothing wins hearts more than the joy which arises from devotion.

(TTP 316)
Devotion encourages a kind of joyful obedience by cultivating subjects who are will-
ingly loyal, obedient, and loving. Fear driven obedience, on the other hand, decreases
the power of individuals, diminishing joy and amplifying sadness.

In conjunction with devotion, Moses also placed the Hebrews ‘under obligation with
benefits, and in the name of God promised them many things in the future’ (TTP 146).

In other words, Moses created a future-oriented hope for the people in order to serve
as a counterweight to fear driven forms of rule. Instead of fearing punishments, the
Hebrews were inclined to follow orders based on uncertain promises. Those promises,
enlivened through devotion, amount to a kind of civic hope (Steinberg, 90). This is
another example of a constructive form of uncertainty in the TTP.

The usefulness of constructive forms of uncertainty for the Hebrews, however, was
limited. As the Hebrew people were ‘weakened by wretched bondage,’ they were more
effectively compelled by force (TTP 145). That fact is reflected in the object of the
ceremonial observances, which were designed so that the Hebrews ‘were not their own
master in anything, but they were completely subjected to someone else’s control’
(TTP 146). Consequently, fear and force, rather than hope, were the primary means
of guiding the Hebrews. To see constructive forms of uncertainty in their full vigor, we
need to turn to democratic hope.

DEMOCRATIC HOPE AS A FORM OF CONSTRUCTIVE UNCERTAINTY
Hope flourishes in abundance in a democratic state, contributing to its peace, stabil-
ity and rational character. It generates, in other words, a form of uncertainty that is
salutary. Hope alone does not contribute to the fundamental purpose of democracy.

Devotion is also necessary. Devotion to a free state, by prioritizing a free state above
other goods, sets boundaries to the uncertainties unleashed in a democratic state. In
this section I will defend this first claim, and then turn to devotion as it relates to hope
as a constructive form of uncertainty.

Chapter XVI begins a new section in the TTP. Spinoza announces that it is time to
ask how far freedom of thought and speech can extend in ‘the best Republic’ (TTP
282). The rest of the TTP is dedicated towards that end. It also, in large part, seeks to
work out the proper relationship between religion and the state. I first lay the founda-
tion for that argument by examining the relationship between natural right and democ-
racy. Doing so will show the limitations of relying on fear as a means to guide a free
people.

In the first part of chapter XVI Spinoza sets out to discuss the relationship between
natural right and the creation of social contracts. Natural right, for Spinoza, is coexten-
sive with each person’s power. If someone is powerful enough to do something, natural
right sets no boundaries and thus permits it. Consequently, a life lived by appetite
alone, or a life lived by the dictates of reason, are on the same plane when it comes to
natural right. In a state of nature, in other words, nothing can rightfully constrain indi-
viduals from acting according to their own necessity. This natural right is so founda-
tional it can never completely be transferred away. Nonetheless, Spinoza notes: ‘no
one can doubt how much more advantageous it is to man to live according to the laws
and certain dictates of reason’ (TTP 284). That is to say, in an environment where
‘everyone is permitted to do whatever he likes, and reason is granted no more right
than hatred and anger,’ fear reigns supreme (TTP 284). Correspondingly, Spinoza
notes: ‘There’s no one who does not desire to live securely, and as far as possible,
without fear’ (TTP 284). Contracts are therefore formed that place limits on natural
rights in exchange for peace, security, and a better life. There is always, however, a
tension in such contracts. As any contract necessarily rubs up against natural right, there
is the possibility of people rebelling from said contracts. Hence, Spinoza notes: ‘a con-
tract can have no force except by reason of its utility’ (TTP 286). If a contract ceases to
function in a way that corresponds with the nature of humans, in other words, it is ‘null
and void’ (TTP 286).

If a ruler relied on a coercive form of rule that created perpetual fear in his subjects,
for example, the contract would invariably fail because it goes against natural right. Spi-
noza makes this point as follows: ‘The supreme power would act in vain if he com-
manded a subject…not to desire to be freed from fear…which necessarily follow[s] from
the laws of nature’ (TTP 296). The desire to be freed from fear, in other words, is so
deeply inscribed in human nature that no ruler could sustain a peaceful and stable state
relying solely on fear. While fear can serve as a constructive form of uncertainty, the
problem to be avoided is a single-minded reliance on fear, which necessarily increases
civically damaging forms of superstition and goes against the human desire to live free
from fear. The broader point is that hope or fear can effectively be used as means to
rule since they are deeply ingrained motivating factors. As Spinoza notes when discuss-
ing the motivating factors to enter a contract:
For it’s a universal law of human nature that no one neglects to pursue what he judges
to be good, unless he hopes for a greater good, or fears a greater harm. Nor does anyone
submit to any evil, except to avoid a greater one, or because he hopes for a greater good.

(TTP 285)
Consequently, any successful contract promises, and thus awakens hope for, peace
and security absent from the state of nature. The best state makes the further promise
of freedom. The promise of freedom is tantalizing as it mimics the freedom found in
the natural state. Democratic freedom, in particular, creates conditions where no citi-
zen is subject to the arbitrary rule of others. The problem, of course, is that democratic
freedom cannot amount to citizens ‘living as one likes’ in the way found in the natural
state. Otherwise, the problems found in the natural state would likewise plague democ-
racies. Spinoza, in fact, characterizes as seditious the thought that each person “ought
to live according to his own decision”. (TTP 348) Even in a free state, consequently,
mechanisms of restraint need to be implemented—such as laws, customs, and the like.

As Spinoza writes:
[a democratic state’s] foundation and end are precisely to avoid the absurdities of appe-
tite, and to confine men within the limits of reason, so far as possible, so that they may
live harmoniously and peacefully. (TTP 288)
Notice that not all appetites need to be avoided in a democratic state. To the con-
trary, an array of appetites will accompany a democratic state, as its freedoms allow
them to flourish. Instead, absurd appetites are chastised, as they place the peace and
harmony of the state at risk. Spinoza’s call to avoid absurd appetites corresponds with
his thoughts on entering a contract from the natural state, which requires agreeing to
restrain each person’s appetites ‘insofar as those appetites urge something harmful to
someone else’ (TTP 285). In effect, Spinoza argues for a liberal state where freedom
is extended to citizens as long as they do not interfere with others. The best state will
stretch this liberal principle with the aim of extending freedom.20 In it, citizens will not
be held in the grip of fear, but rather hopefully live towards the future. Spinoza explains
the limited role fear should have in a free state when he discusses the ultimate end of
a free state in the final chapter:
its ultimate end is not to dominate, restraining men by fear, and making them subject to
another’s control, but on the contrary to free each person from fear, so that he can live
securely, as far as possible, i.e., so that he retains to the utmost his natural right to exist
and operate without harm to himself or anyone else. (TTP 346)
In addition to a free state not relying on fear as a form of restraint, it should also aim
to free each person from fear. Since living beyond hope and fear is not possible for
20 Spinoza’s arguments for liberal like principles do not amount to him being a liberal in a com-
prehensive sense. Other parts of his political thought do not fit a liberal mold.

most, and on the whole politically undesirable when individually attained, hope should
instead flourish in a free state.21 Democracy facilitates a hopeful posture as it approaches
‘most nearly the freedom nature concedes to everyone’ (TTP 289). It fosters an envi-
ronment where citizens hopefully look towards the future in their private and public
lives.22
In public life democratic procedures allow hope to be maintained for both those
who support and oppose decisions reached in common. In a democracy it is ‘agreed
that the measure which had the most votes would have the force of a decree, but that
meanwhile they’d retain the authority to repeal these decrees when they saw better
ones’ (TTP 351). Democratic procedures do not solely reserve hope for citizens who
agree with decisions reached in common, they also facilitate a hopeful posture for those
that disagree with those decisions. In this way, democratic sovereignty approaches the
sovereign right each individual has in a natural state. After all, it is only in a democracy
where ‘no one so transfers his natural right to another that in the future there is no
consultation with him’ (TTP 289). Consequently, if a citizen believes he has a better
alternative to the current laws, he can remain hopeful that the laws might change in the
future. Notice how this is different from other regimes that preclude the people from
rule. In those regimes, if you disagree with a certain law you can grudgingly go along
with the ruling power or you might revolt against the ruling authority. There is little else
you can effectively accomplish considering you hold no political power to do otherwise.

Instead of hope, frustration and fear of the unknown have a greater likelihood to be
the norm in non-democratic regimes. Feeling powerless to alter the present and future,
it is unsurprising that those living in non-democratic regimes would turn to otherworldly
sources of hope.

In private life democratic freedoms allow citizens to look hopefully towards a future
they fashion. The hope accompanying democratic freedom is not limited to its proce-
dural means of instituting laws, in other words, but extends to the sphere of liberty it
allows in private life. The liberty granted in a democracy, after all, is the greatest among
regime types. As noted above, it is ‘the most natural’ in that it approximates the free-
dom found in the natural state. Consequently, in a democracy individuals should be
‘so governed that they can openly hold different and contrary opinions, and still live in
harmony’ (TTP 351). Formally allowing freedom of judgment without achieving har-
monious living among a diversity of views and ways of life, in other words, falls short of
21 ‘So, because those who neither fear nor hope for anything are to that extent their [5] own mas-
ters (by ii, 10), they are (by ii, 14) enemies of the state, whom it may rightly restrain.’ (PT 520-21).

22 Parts of what follows are echoed in Vergaray 2019.

the democratic ideal.23 Hence, the reliance on laws to restrain behavior should be kept
to a minimum. As Spinoza reminds, ‘Anyone who wants to limit everything by laws will
provoke more vices than he’ll correct’ (TTP 348).24 Hence the extensive freedoms
found in a democratic state generate hopes regarding private pursuits. Just as having a
say in how you are ruled in public life provides citizens hope, having liberty to choose
to think, speak, and behave in diverse ways facilitates hope in everyday life.

Both public and private democratic hopes generate forms of constructive uncer-
tainty. The form of uncertainty sustained in public life keeps citizens from feeling des-
pair at the current order of things, and thus facilitates political stability over time. In
private life the hope generated by the freedoms found in a democracy allows citizens
to seek their own advantage, which Spinoza calls ‘the mainstay and life of all human
actions’ (TTP 315). That is to say, democratic freedoms appeal to individual self-in-
terest by allowing individuals the space to flourish as they choose. That freedom, in
turn, creates a salutary hope as it generates gratitude for the regime that makes those
freedoms possible. That gratitude creates a loyalty to the state that, as we will see below,
is necessary for political stability. More broadly, both kinds of democratic hope (con-
structive uncertainties) keep citizens’ gaze oriented towards a better future. That orien-
tation, in turn, helps temper the human inclination to follow the passions to the neglect
of future goods. Instead, democratic hope creates an environment where the active
affect of joy is likely to flourish, allowing the intellectual virtues to multiply, which in
turn leads to the advancement of the arts and sciences (TTP 349).

While the constructive forms of uncertainty found in a democracy facilitate human
flourishing and support political and social stability, they are insufficient to temper the
fear driven uncertainties that generate the worst forms of superstition. Consider that a
hope-filled society cannot be maintained in perpetuity. Democracy may facilitate a
hope-filled society, but fear, its ugly partner, is never far behind. When fear overtakes
a democratic society, it opens itself to the worse forms of superstition that place political
stability in peril. Given the multiplicity of beliefs and ways of life allowed in a democ-
racy, illiberal hopes can rise to the surface when individuals or collectives are in the grip
of fear. Moderate religious or secular beliefs can become extreme when they are used
to deal with fearful uncertainty about the future. In short, it would seem Spinoza’s de-
mocracy could easily revert to the world of religious conflict Spinoza tried to overcome.

23 ‘The end of the Republic, I say, is not to change men from rational beings into beasts or autom-
ata, but to enable their minds and bodies to perform their functions safely, to enable them to use their
reason freely, and not to clash with one another in hatred, anger or deception, or deal inequitably with
one another. So the end of the Republic is really freedom.’ (TTP 346)
24 For example, laws cannot effectively prohibit ‘extravagant living, envy, greed, drunkenness, and
the like.’ (TTP 348)
Another problem is the tendency to move towards a wholly private life at times of
peace and stability. That is to say, what is to keep citizens from ignoring the public good
when peace and stability can make the pursuit of private goods seem like an end in
itself? This tendency towards private life can weaken public spiritedness and thereby
leave the state unprepared to defend itself in moments of crisis. It can also weaken any
sense of unity opening the state up to internal conflict that inflames superstitious beliefs.

In sum, the constructive hope-filled uncertainties unleashed in a democracy are insuf-
ficient to deal with the conditions that generate the destructive uncertainties underlying
superstition.

In order for the hope-filled uncertainties in a democracy to not devolve into a haven
for superstitions, Spinoza argues that devotion to the state is necessary to create citizens
that place loyalty to the state above their private interests. In the strongest terms, Spi-
noza notes: ‘It’s certain that piety toward a person’s country is the supreme piety he can
render’ (TTP 336).25 This claim must have startled his theologically minded contem-
poraries. After all, supreme piety, from a monotheistic perspective, should be rendered
to God alone. Yet, Spinoza insists that the preservation of the state needs to be at the
center of people’s pious devotion. After all, he notes, ‘if the state is destroyed, nothing
good can remain, but everything is at risk.’ In a democracy devotion to the state takes
the form of devotion to freedom. Devotion to freedom resonates at a visceral level as
it mimics the natural right all individuals possess. In a functioning democracy, moreo-
ver, the benefits of living in a free state are manifest for all to appreciate. Notice, devo-
tion to freedom is groundless if it is not accompanied by devotion to the state. Devotion
to the state makes free subjects recognize their dependence on the state, softening the
tendencies of free regimes to make individuals believe the fantasy that they are sover-
eign individuals. They implicitly recognize, in other words, that only in a state can free-
dom divorced from fear be protected.

Spinoza hoped that devotion to freedom would eventually reach a point where citi-
zens would be willing to make great sacrifices in the name of the state. Spinoza illus-
trates the power accompanying devotion to a free state at the end of the TTP when he
claims that martyrs for freedom are worth emulating and revering.26 Also, in chapter
XVII Spinoza suggests that fighting for ‘peace and freedom’ is preferable to fighting for
glory. If these examples weren’t enough, Spinoza upholds the example of Manlius Tor-
quatus’ execution of his son for disobeying orders as an example to be honored (TTP
25 See also, ‘Both reason and experience teach, as clearly as can be, that the preservation of the
state depends chiefly on the loyalty of its subjects, on their virtue, and on their constancy of heart in
carrying out commands.’ (TTP 298)
26 Honorable individuals, Spinoza claims, ‘think it…glorious to die for freedom.’ (TTP 350)
337).27 Put differently, devotion to the state creates conditions where public goods take
precedence over private ones. This is not to suggest that democratic citizens will obses-
sively be preoccupied with public goods. Rather, devotion to a free state will cultivate
citizens who are prepared and willing to make sacrifices when the freedoms prized in
the state are threatened.

More specifically, democrat’s willingness to fight, die, and kill for the freedoms they
enjoy leads them to defend the state against enemies both internal and external.28 En-
emies, in this context, refer to individuals or collectives that threaten or violate the free-
doms enjoyed in the state. Democratic peoples thus become the protectors of freedom,
and thereby protectors of the state. This protection inevitably involves restraining any
threat to the peace that is the precondition of that freedom, including devotion to reli-
gious sects that supersede that of the state. Fervent religious devotion in this context
appears as madness, a threat to the freedom of all.

In sum, devotion to the state protects the otherwise perilous condition that can result
from the uncertainties unleashed in a free state. Specifically, by encouraging the placing
of public goods above private interests, it protects against the damaging effects that re-
sult when fear rears its head in a democracy, as well as the democratic tendency to
indulge in private life. Together with the constructive hope-filled uncertainties un-
leashed in a democracy, devotion to the state creates a self-sustaining system that com-
bats destructive uncertainties that create and sustain the most socially pernicious forms
of superstition.

CONCLUSION
This paper has argued that according to Spinoza in the TTP, it is preferable to con-
front the socially debilitating uncertainties underlying superstition through the political
and social promotion of hope, a constructive form of uncertainty. Uncertainty, in other
words, is not simply a destructive force but potentially a constructive force that can
facilitate political stability and peace. The uncertain emotions of hope and fear are Spi-
noza’s prime examples of constructive forms of uncertainty. Hope, however, is a more
27 In this context, it is worth noting the next sentence, ‘it follows that the well-being of the people
is the supreme law. All laws both human and divine, must be accommodated to this.’ (TTP 337)
28 Spinoza uses the language of ‘enemies’ when he notes that individuals in a natural state are
‘permitted to regard as an enemy anyone who wants to prevent him from doing what he intends.’ (TTP
284)
effective means to lead, which finds its greatest expression in a democracy. A democ-
racy, after all, mirrors the type of freedom found in a natural state but with the requisite
safety and stability required for living in hope rather than fear.

I have also argued that understanding devotion to the state in the TTP is necessary
for understanding Spinoza’s recommendations for combating superstition. In particu-
lar, devotion combats dangerous superstitions by stabilizing its inconstant nature. The
foundational beliefs and loyalties that are part and parcel of devotion help cultivate
inward stability, which helps one weather outward uncertainties. It also protects the
sovereign power, as it enlists obedience and loyalty to the state. In a democracy, devo-
tion to freedom translates to a devotion to the state, the protector of freedom. Devotion
thereby encourages patriots who are willing to defend the freedoms enjoyed in the state.

In addition to devotion enlisting support for the state, reason also “urges us to defend
the state with all our powers” (TTP 287).

Spinoza’s emphasis on the motivating factors of loyalty and devotion to the state
follows a tradition that goes back at least to Plato’s discussion of the necessity of political
myths.29 Political myths are necessary for cultivating public-spirited citizens. Without
that inducement, most people would place their personal loyalties and pursuits above
public matters. Reason for most, in other words, takes a backseat to the passions and
thus inclines humans toward private concerns. Consequently, Spinoza notes, if all hu-
mans were led by reason, there would be no need for laws (TTP 144). Perhaps human
frailty requires a superstitious belief in the special status of the state in order to foster
political and social stability.30 Spinoza is silent on this matter.

REFERENCES
Carlisle, C. 2021. Spinoza’s Religion; A Reading of the Ethics. Princeton: Princeton
University Press.

29 See chapter 5 in Michael LeBuffe’s (2018) comments on the problems and benefits of using Plato’s
noble lie when thinking about Spinoza. What I offer here is suggestive, not exhaustive.

30 James (2006) observes that “the encouragement of devotion cannot be neatly separated from the
production of superstition, nor is it clear that the first is invariably fruitful and the second destructive”
(17). See also Curley’s thoughts on superstition in “Spinoza’s Exchange with Albert Burgh.” I do not
mean to suggest that devotion to the state only, or even primarily, requires myth according to Spinoza in
the TTP. It is a piece of a puzzle that was partially explored in this essay.

Curley, E. 1990. “Notes on a Neglected Masterpiece (II): The Theologico-Political
Treatise as a Prolegomenon to the Ethics.” In J. A. Cover and Mark Kulstad, eds.,
Central Themes in Early Modern Philosophy, Indianapolis: Hackett, 109–59.

Curley, E. 2010. “Spinoza’s Exchange with Albert Burgh.” In Y. Melamed and M.

Rosenthal, eds., Spinoza’s Theological-Political Treatise; Cambridge: Cambridge
University Press, 11-28.

Hacking, I. 2006. The Emergence of Probability: A Philosophical Study of Early Ideas
About Probability, Induction and Statistical Inference. Cambridge: Cambridge University
Press.

James, S. 2021. ‘The Interdependence of Hope and Fear,’ Contemporary Political The-
ory 20: 200-231.

James, S. 2012. Spinoza on Philosophy, Religion, and Politics; The Theologico-
Political Treatise. Oxford: Oxford University Press.

James, Susan. 2006. Spinoza on Superstition: Coming to Terms with Fear (Mededelingen
Vanwege Het Spinozahuis) 88. Budel, The Netherlands: Uitgeverij Damon.

Kaminsky, G. 1990. Spinoza: La Politica de Las Pasiones. Barcelona, Spain: Gedisa.

LeBuffe, M. 2018. Spinoza on Reason. Oxford: Oxford University Press.

Modd, D. 2002. When All Else Fails; Government as the Ultimate Risk Manager. Cam-
bridge: Harvard University Press.

Nadler, S. Spinoza: A Life. Cambridge: Cambridge University Press, 2018.

Nadler, S. 2005. ‘Hope, Fear, and the Politics of Immortality.’ In Tom Sorrell and G. A.

J. Rogers, eds., Analytic Philosophy and History of Philosophy (Mind Association Occa-
sional), New York, NY: Oxford University Press, USA. 201-217.

Power, D. 2007. Organized Uncertainty; Designing a World of Risk Management. Ox-
ford: Oxford University Press.

Spinoza, Benedictus de. Spinoza Opera, vol. 3. Edited by Carl Gebhardt. Heidelberg:
Winter.

Spinoza, Benedictus de. (1677) 1985. The Ethics. In The Collected Works of Spinoza,
vol 1, Edited and translated by Edwin Curley. Princeton, NJ: Princeton University Press.

Spinoza, Benedictus de. (1670) 2016. Theological-Political Treatise. In The Collected
Works of Spinoza, vol. 2, Edited and translated by Edwin Curley. Princeton, NJ:
Princeton University Press.

Steenbakkers, P. 2021. “Spinoza’s Life.” In Yitzhak Melamed, ed., A Companion to
Spinoza, Hoboken: Wiley Blackwell, 3–14.

Steinberg, J. 2018. Spinoza’s Political Psychology: The Taming of Fortune and
Fear. Cambridge: Cambridge University Press.

Vardoulakis, D. 2020. Spinoza, the Epicurean: Authority and Utility in Materialism. Ed-
inburgh: Edinburgh University Press.

Vergaray, A. 2019. ‘Thinking With Spinoza About Uncertainty Today; Preliminary Re-
flections on Uncertainty in Spinoza’s Political and Social Thought,’ In Circolo 8: 119-129.

Yovel, Y. 1989. Spinoza and Other Heretics; The Marrano of Reason. Princeton:
Princeton University Press.

